### ISSUE TITLE
Sample

### ISSUE THREAD

**Issue by edcable** [openMF/web-app#1]
**Goal:**
As a <USER PERSONA> I want <FEATURE> so that I can <PURPOSE of FEATURE>  
i.e. 

As DevOps I want Health liveness Probe on the microservice so that the health of the service can be monitored.

*Tasks:* 

Add negative use-cases to Unit tests
  Add Integration tests
*Acceptance Criteria:*

  Negative use-cases for Unit Tests in the "common streaming library"
  Integration tests in the "common streaming library"
*Dependencies:*

  #148

**Comment by anweshknayak** [comment]
@edcable can you give me merge access to the repo? so things can move on quickly.

Thanks
