### ISSUE TITLE
Loans: Transfer Fund Page

### ISSUE THREAD

**Issue by muskankhedia** [openMF/web-app#1060]
https://staging.mifos.io/#/accounttransfers/fromloans/76

![Screenshot from 2020-07-11 20-51-17](https://user-images.githubusercontent.com/36980003/87227431-89b59900-c3b8-11ea-911b-f1765ce0b7ec.png)

**Comment by karantakalkar** [comment]
@muskankhedia I think this belongs to account transfers module and not loans can you check?

**Comment by muskankhedia** [comment]
@karantakalkar Yes it belongs to account transfer module. We can either create a separate account transfer module as in community-app or design the particular pages per transfer fund action in the respective modules as been done till now.
