### ISSUE TITLE
use fetch client image api in clients layout

### ISSUE THREAD

**Issue by anweshknayak** [openMF/web-app#107]
- clients/view/

- using https://demo.openmf.org/api-docs/apiLive.htm#client_images

Currently the image is harcoded

**Comment by vatsal3333** [comment]
I would like to work on this issue.
@anweshknayak The link which you mentioned above is has an example in it which is showing error when opened. I used the api in the project by adding a getClientImage function in client service file and then used that function in view-client component
![screenshot from 2019-01-05 23-34-38](https://user-images.githubusercontent.com/29050693/50728640-30313600-1153-11e9-93f0-fe234d73b232.png)
![screenshot from 2019-01-05 23-34-28](https://user-images.githubusercontent.com/29050693/50728642-39220780-1153-11e9-9cb2-a06220697032.png)

 and I am getting the same error. Can you please help?

**Comment by abhaychawla** [comment]
Please explore and try to understand the error, the image has not been uploaded so how can it be fetched? You need to handle this case accordingly. Please see the community app for reference to implement the features.

**Comment by aashish-ak** [comment]
@abhaychawla I would like to work on this issue but the clients service, instead of HttpClient uses Http module which is deprecated, so should i use that module?

**Comment by aashish-ak** [comment]
@abhaychawla A little help needed here!

**Comment by abhaychawla** [comment]
@aashish-ak You need to make any relevant change necessary to implement this only using the latest implementation, without making any change in the current code which might be obsolete.

**Comment by Jov03** [comment]
issue already resolved via PR #414
