### ISSUE TITLE
Design 404 page for accessing wrong urls

### ISSUE THREAD

**Issue by anweshknayak** [openMF/web-app#110]

**Comment by Jp138233** [comment]
I would like to work on this

**Comment by abhaychawla** [comment]
@Jp138233 This issue is for GCI 2018 students. Please take up any other issue.

**Comment by Jp138233** [comment]
Ah, my bad. I didn't know what the acronym was for

**Comment by JonathanXu1** [comment]
Hi, I would like to work on this for GCI.

In which directory would you like me to create the NotFoundComponent? Also this is my first time using this framework, so if you could point me to the code where the routing module for the 404page is, that would be really appreciated! Also, I'm planning on using Particles.JS for an interactive background, so I'm wondering where you would like me to save the particles.json file for that.

**Comment by abhaychawla** [comment]
Hi @JonathanXu1, simply generate the NotFoundComponent following the guidelines in the wiki within the `src/app` folder. As I told you on the GCI portal, the app routing module specifies the code which currently redirects to home when an unintended route is accessed. You'll need to modify that so the NotFoundComponent is displayed instead. As far as the usage of `particle.js` is concerned, I want you to do some research about how it can be used with Angular on your own and try to implement it. We can reiterate if any changes would be required once you send the PR.

**Comment by JonathanXu1** [comment]
Thanks for the clarification. I've created a NotFound component in src/app folder. However I was having trouble getting particles.js working on Angular but other than that it is functional.

Pull request: https://github.com/openMF/web-app/pull/326
