### ISSUE TITLE
Date in notes feature

### ISSUE THREAD

**Issue by anweshknayak** [openMF/web-app#111]
Not sure how date feature is being used.

**Comment by santoshconflux** [comment]
Hi @anweshknayak , who requested this  feature?

**Comment by anweshknayak** [comment]
@santoshconflux it was there in older app so I thought. could you check the **Notes** tab in clients and tell if that is enough? Or I need to add a date stamp

**Comment by santoshconflux** [comment]
@anweshknayak , Date stamp  for the Notes in client page and loan account page is sufficient and it's already there.

![datestamp clientnotes](https://user-images.githubusercontent.com/23022667/42742933-261e8e0a-88dd-11e8-94d6-855fa5947c97.png)

**Comment by anweshknayak** [comment]
@santoshconflux I was talking about this only. I am unable to implement this one as I have some doubts regarding the implementation. Thus the issue.

I think we should use a tag **blocker** to indicate issues like this

**Comment by santoshconflux** [comment]
@anweshknayak ,  Got your point. Added new label 'Blocker and Urgent Attention Needed'   :)
