### ISSUE TITLE
Language and Date format settings need to be centralized

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#1213]
- [x] Develop centralized service

Replace all hard-coded instances:
        
- [x] Clients
- [x] Groups
- [x] Centers
- [x] Loans
- [x] Savings
- [ ] Shares
- [x] Recurring Deposits
- [ ] Fixed Deposits  
- [x] Account Transfer
- [ ] Accounting
- [x] Reports
- [x] Organization
- [ ] System
- [ ] Products 
- [x] Templates

Steps for replacement:
- Import settings service to the component.
- Replace hardcoded `locale` and `dateFormat` variable by settings service variables
- Check the feature after replacement
- In case of bugs check the same feature on demo.mifos.io or staging.mifos.io or dev.mifos.io

For each module there will be a single PR covering all cases, Kindly check all features once replaced and report bugs if any.
Also please specify the module for which you want to work on as this issue will have multiple PRs.

**Comment by rak108** [comment]
Hi! Can I take up this issue?

**Comment by karantakalkar** [comment]
@rak108 please specify the module for which you want to take up this issue

**Comment by rak108** [comment]
@karantakalkar hi! i'd like to work on the reports module.

**Comment by karantakalkar** [comment]
Go ahead then see #1223 to get context of what needs to be changed, to check if dateformat and language changes are in place see API request payload, df and locale can be changed in settings.

**Comment by rak108** [comment]
> Go ahead then see #1223 to get context of what needs to be changed, to check if dateformat and language changes are in place see API request payload, df and locale can be changed in settings.

okay thanks! i'll get started.

**Comment by rak108** [comment]
@karantakalkar Hey! So i think i've done the changes, how do i check the API request payload?

**Comment by karantakalkar** [comment]
Network tab in developer tools, see the triggered api request on form submission

**Comment by Abhirup-99** [comment]
@karantakalkar I have submitted a pr for 1250, can I work on any of the above modules?

**Comment by karantakalkar** [comment]
Go ahead, specify the module you want to work on

**Comment by Abhirup-99** [comment]
I would like to work on clients module.

**Comment by rak108** [comment]
Hi @karantakalkar , im getting a 404 error after im done with my work, Im confused if it is something i can fix or not

**Comment by karantakalkar** [comment]
Changing df and language wont cause 404s its a backend problem

**Comment by rak108** [comment]
Okay cool, I'll make a PR now

**Comment by shobhi1310** [comment]
@karantakalkar 
Sir, I want to work on the **savings module**. Please assign me this issue.

**Comment by karantakalkar** [comment]
@shobhi1310 Go ahead

**Comment by Abhirup-99** [comment]
@karantakalkar can I pick up another module from here?

**Comment by stableapple** [comment]
@karantakalkar  Can I work on Recurring Deposits module?

**Comment by Abhirup-99** [comment]
@karantakalkar I am starting the groups module.

**Comment by shobhi1310** [comment]
@karantakalkar  Sir, Can I take up the **loans module**,  also do review my other PRs as well.

**Comment by shobhi1310** [comment]
@karantakalkar sir, do review my PR once.

**Comment by PANKAJ-DAHIYA123** [comment]
Hi @karantakalkar Plz assign me fixed deposits module.

**Comment by karantakalkar** [comment]
@PANKAJ-DAHIYA123 Go ahead

**Comment by BLasan** [comment]
@karantakalkar Please assign me for the Organization module

**Comment by Ddevendra** [comment]
@karantakalkar I would like to take centers module

**Comment by shan7030** [comment]
@karantakalkar  I would like to work on Fixed Deposits module

**Comment by karantakalkar** [comment]
Go ahead

**Comment by shubhamkorde** [comment]
I would like to work on accounting module

**Comment by raghu0812199** [comment]
hi @karantakalkar i would like to work on  Fixed Deposits module if it is still open

**Comment by karantakalkar** [comment]
@raghu0812199 FD has already been covered pick any other module
@shubhamkorde go ahead, sorry for the delay.

**Comment by raghu0812199** [comment]
can i work on share module

**Comment by abhishekkumar08** [comment]
@karantakalkar can I work on the products module?

**Comment by shubhamkorde** [comment]
Hii @karantakalkar the dateFormat which was hard-coded earlier is not the same as the one fetched from the service. This results in error "invalid parameters were passed in the request". I checked this by logging both. Please help!

**Comment by abhishekkumar08** [comment]
@karantakalkar I'm starting on shares module.

**Comment by BLasan** [comment]
> @karantakalkar I'm starting on shares module.

go ahead

**Comment by abhishekkumar08** [comment]
> 
> 
> > @karantakalkar I'm starting on shares module.
> 
> go ahead
@BLasan  Some files are yet to be refractored in savings module, working on that.

**Comment by abhishekkumar08** [comment]
> 
> 
> > @karantakalkar I'm starting on shares module.
> 
> go ahead

@BLasan  Some files are yet to be refractored in savings module, working on that.

**Comment by goel-aman** [comment]
@BLasan @karantakalkar can i work on system module if it is still open.

**Comment by karantakalkar** [comment]
Go ahead @goel-aman

**Comment by mittulmandhan** [comment]
Can I work on the Product module? @karantakalkar
