### ISSUE TITLE
Notifications: routing to notification blocked by missing `parentId` attribute

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#1228]
- Routing to certain notifications like "Loan Created" is being blocked because of change in routing structure from community app, to navigate to a certain loan account we must now know the `parent entity Id`.

![Screenshot from 2020-08-26 14-48-17](https://user-images.githubusercontent.com/54709463/91285840-4ddd6400-e7ab-11ea-98e4-bdfeccf7982a.png)

- Currently navigating by clicking on notification gives 404. Though parent entity Id is not required to fetch loan/savings data it is required to route with present scenario.

- Notifications code also need to be updated once back-end updates `isRead` parameter and returns appropriate notifications for given `isRead` http parameter.

Connected with: https://issues.apache.org/jira/browse/FINERACT-1132

**Comment by ayan-biswas0412** [comment]
can I work on this ? is this issue workable or I need some APIs ?
