### ISSUE TITLE
Clients: create client address step options

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#1229]
In-congruency between data fetched on demo and staging instances causes address step (add) options to disappear on staging instance.

`demo.mifos.io`

![Screenshot from 2020-08-27 18-29-50](https://user-images.githubusercontent.com/54709463/91445395-ae47d080-e893-11ea-8767-d86b5e29f3e3.png)

`staging.mifos.io`

![Screenshot from 2020-08-27 18-30-25](https://user-images.githubusercontent.com/54709463/91445393-ad16a380-e893-11ea-94fe-6c9127a0c237.png)

**Comment by karantakalkar** [comment]
@vorburger can the API response of this be made uniform across servers?

**Comment by vorburger** [comment]
@karantakalkar I'm not involved in demo.mifos.io and staging.mifos.io, that's @edcable & Co. I only run https://www.fineract.dev, and invite you to use it because it's most up to date.

**Comment by edcable** [comment]
@karantakalkar you should make the front end match the API for fineract.dev as the latest version of the back-end.

**Comment by karantakalkar** [comment]
@vorburger 
demo.fineract.dev doesn't return address field, can you check?

![Screenshot from 2020-11-16 19-28-34](https://user-images.githubusercontent.com/54709463/99260955-10382680-2842-11eb-9c74-6da4ed4658a0.png)

 API request on https://dev.mifos.io/fineract-provider/api/v1/clients/template does return address fields.

**Comment by vorburger** [comment]
@karantakalkar could you please email the Fineract Dev list about this? The code on fineract.dev is the latest, so perhaps this is some configuration option?
