### ISSUE TITLE
Entity Data Table Checks need to be developed

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#1230]
Develop EDTC functionalities for `CREATE`, `ACTIVATE`, `CLOSE` etc. for UIs in the following modules:

- [ ]  Clients
- [ ] Groups
- [ ] Centers
- [ ] Loans
- [ ] Savings 

Eg:
![Screenshot from 2020-08-27 18-55-15](https://user-images.githubusercontent.com/54709463/91447943-e13f9380-e896-11ea-9e4a-67ae35031d21.png)

**Comment by Abhirup-99** [comment]
@karantakalkar can I work on this issue?

**Comment by karantakalkar** [comment]
No, this will probably be a GSoC task. design and code arch. for this requires discussion.

**Comment by bharathcgowda** [comment]
@karantakalkar @edcable   can this be worked as a task under GSOC 2021, If not can we allow @Abhirup-99 to work on it? or any other interest Developer.

**Comment by Abhirup-99** [comment]
If it comes under GSOC 2021, I would love to work on it. I have already contributed a lot to this repo before, you can check my contribution [here](https://github.com/openMF/web-app/pulls?q=is%3Apr+author%3AAbhirup-99+)

**Comment by karantakalkar** [comment]
Yes @bharathcgowda but where will we list it ? ASF ? Mifos isn't in GSoC this year.

**Comment by bharathcgowda** [comment]
Hi, @karantakalkar  as you said Since Mifos isn't in GSoC this year, I am not sure we can work on this issue in 2021 by listing in ASF.
We might have to do it outside of GSoC as there is no code change required at Fineract End and all APIs are ready to connect.

**Comment by bharathcgowda** [comment]
Enhancement is complete, hence closing the ticket
![image](https://user-images.githubusercontent.com/65952533/169595724-22c6f292-f690-460d-b659-f6264732728e.png)
