### ISSUE TITLE
Client charges subsection needs to be improved

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#1233]
Code, functionality as well as Routing needs to be made consistent with rest of the app.

![Screenshot from 2020-08-28 14-59-51](https://user-images.githubusercontent.com/54709463/91545875-46e75a80-e93f-11ea-95cd-1d3a5312e7fc.png)

Access charges subsection on clients view page.
https://demo.mifos.io/#/viewclient/1

![Screenshot from 2020-09-18 11-19-18](https://user-images.githubusercontent.com/54709463/93560926-d7461780-f9a0-11ea-90b7-7e5c96c968f5.png)

**Comment by shobhi1310** [comment]
Can I look into this issue? I have sent a PR for #746

**Comment by karantakalkar** [comment]
Go ahead

**Comment by shobhi1310** [comment]
Can the issue be elaborated, like which component is it referring to where consistency is needed and what is this page ?

**Comment by karantakalkar** [comment]
See implementations of tables/forms/dialogs etc in rest of institution section (clients/groups/centers and sub-modules) and make it similar, charges can be accessed in a table, you can find relevant data on `demo` or `staging` servers as `dev` is not that populated.
In case this still seems intricate gain experience with app by contributing to good first issues or report your own issues and submit fix PRs.

**Comment by shobhi1310** [comment]
![image](https://user-images.githubusercontent.com/42507632/93496799-4c780500-f92d-11ea-81b1-197df87be742.png)
This page is navigable through the  Institution->Clients

How to reach to the page shown in the screenshot of the issue?

**Comment by karantakalkar** [comment]
Issue updated

**Comment by BLasan** [comment]
@karantakalkar Can I work on this?

**Comment by karantakalkar** [comment]
Go Ahead

**Comment by BLasan** [comment]
> Go Ahead

What are the changes we have to do? It's working fine btw

**Comment by BLasan** [comment]
@karantakalkar Please review

**Comment by Abhirup-99** [comment]
@karantakalkar can I work on this?
