### ISSUE TITLE
Clients: Create Self Service User

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#1234]
Screen accessible in `staging.mifos.io`

![Screenshot from 2020-08-28 15-04-22](https://user-images.githubusercontent.com/54709463/91546272-d12fbe80-e93f-11ea-9457-fa3a1abd00cc.png)

**Comment by BLasan** [comment]
@karantakalkar Can I work on this ?

**Comment by karantakalkar** [comment]
Go ahead, place the component in client actions folder make the routing and resolving similar to other actions.

**Comment by BLasan** [comment]
> Go ahead, place the component in client actions folder make the routing and resolving similar to other actions.

Sorry for the delay. I'll complete this by today

**Comment by BLasan** [comment]
Can you specify the path for this UI in staging.mifos.io ?

**Comment by karantakalkar** [comment]
It's one of the options in 'more' drop-down in clients view page.

**Comment by BLasan** [comment]
@karantakalkar I was busy with some works in last month. I'll make the PR ready by today
