### ISSUE TITLE
Improve Loan Tabs Design

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#1249]
Redesign various Loan account tabs to make them more aesthetic, also ensure design consistency with savings, RD/FD view pages.

General Tab
![Screenshot from 2020-10-01 13-07-23](https://user-images.githubusercontent.com/54709463/94781231-2b142000-03e7-11eb-9713-bf7524e3e29b.png)

Transactions Tab
![Screenshot from 2020-10-01 13-06-51](https://user-images.githubusercontent.com/54709463/94781235-2c454d00-03e7-11eb-87ed-1c13f10902bb.png)

Repayment Schedule Tab
![Screenshot from 2020-10-01 13-06-38](https://user-images.githubusercontent.com/54709463/94781238-2cdde380-03e7-11eb-9063-1129a5ff22d3.png)

Also see design of community app loan account pages accessed here: https://demo.mifos.io/#/viewclient/1

**Comment by BLasan** [comment]
@karantakalkar I'll work on this

**Comment by harichandana1406** [comment]
Hello, Can I work on this? and this is my first contribution to open source.

**Comment by BLasan** [comment]
> Hello, Can I work on this? and this is my first contribution to open source.

Hello @harichandana1406 , currently working on this

**Comment by harichandana1406** [comment]
> > Hello, Can I work on this? and this is my first contribution to open source.
> 
> Hello @harichandana1406 , currently working on this

So Can I also work on this ?

**Comment by BLasan** [comment]
@harichandana1406 PR will be ready soon. It's better to pick another issue. There are plenty of issues you can work on

**Comment by harichandana1406** [comment]
okay Thanks

**Comment by lizeth9797** [comment]
Hello @BLasan , is this issue still open?
