### ISSUE TITLE
Fix view user page design

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#1250]
![screenshot(1)](https://user-images.githubusercontent.com/54709463/94782286-a32f1580-03e8-11eb-8c22-2b46e3c10083.png)

**Comment by Abhirup-99** [comment]
@karantakalkar can I work on this?

**Comment by karantakalkar** [comment]
Go ahead

**Comment by BLasan** [comment]
@karantakalkar Can I work on this?

**Comment by karantakalkar** [comment]
@Abhirup-99 are you working on it?

**Comment by Abhirup-99** [comment]
@karantakalkar sorry had been a bit busy, would push a pr by today.

**Comment by harichandana1406** [comment]
Is this issue fixed? or can I work on this.

**Comment by Abhirup-99** [comment]
> Is this issue fixed? or can I work on this.

The corresponding pr is there, and it would be reviewed shortly.
