### ISSUE TITLE
Automatically deploy latest to a hosted site

### ISSUE THREAD

**Issue by vorburger** [openMF/web-app#1254]
It would be cool if there was Continuous Deployment to show the latest and greatest code in this repo to a server / site.

So similar to https://github.com/openMF/community-app/issues/3309, but for this project.

#786 should, IMHO, be addressed before this is done, so that it can be easily used with / pointed to different Fineract API servers.

@edcable

**Comment by abhaychawla** [comment]
@vorburger, The latest code is continuously deployed at https://openmf.github.io/web-app/ whenever a PR is merged into the master branch.
