### ISSUE TITLE
GLIM & GSIM interface is missing

### ISSUE THREAD

**Issue by francisguchie** [openMF/web-app#1262]
## Description
A new functionality / module was added to the latest build please read more here ===> https://github.com/openMF/community-app/pull/3244 

## Steps to Reproduce
Log into mifos using the web-app, go to groups and select a group of your choice, you should see the GLIM Application and GSIM Application options but they are missing

## Expected Behaviour
We need to add these functionalities too 

## Actual Behaviour
GLIM and GSIM is missing 

## Settings
- Mifos X version: latest build for both web-app and fineract
- Browser used: Firefox 81.xx

## Screenshots, if any
![image](https://user-images.githubusercontent.com/22683654/95880360-f4cf8c80-0d66-11eb-9da8-f73d5502ff1e.png)

**Comment by Abhirup-99** [comment]
@karantakalkar can I work on this?

**Comment by francisguchie** [comment]
@karantakalkar  it would be nice and if you do i will review

**Comment by karantakalkar** [comment]
@Abhirup-99 I think this feature is only there at latest version of community app and not the deployed ones...so you can go ahead and replicate the functionality but you will need to checkout that codebase to see how this is gonna come about.

**Comment by francisguchie** [comment]
@Abhirup-99  

I have implemented GLIM / GSIM on release 17.07.01 (as a modification for my users) so i will support you on any questions you have on industrial implementation

**Comment by Abhirup-99** [comment]
@francisguchie the default credentials for community app doesn't seem to work, any idea why?

**Comment by Abhirup-99** [comment]
@karantakalkar I can't log in to the community app with the default credentials. Can you suggest a way around or alternatives?

**Comment by Abhirup-99** [comment]
It's fixed now, I was accessing wrong url.

**Comment by Abhirup-99** [comment]
I have been able to use it in localhost, can either of you help me in adding loan products, without it, I can't view and implement the other UI.

**Comment by karantakalkar** [comment]
Ask the mailing list

**Comment by Abhirup-99** [comment]
I have been able to figure it out by changing the baseapiurl in community app.

**Comment by ramvr1256** [comment]
@bharathcgowda It is fixed in #1510 . Can you please check and close this
