### ISSUE TITLE
Credit Bureau Integration is missing under external services

### ISSUE THREAD

**Issue by francisguchie** [openMF/web-app#1270]
Looking at the image below, the latest version of  the community app has an extra external service that is missing under external services

![image](https://user-images.githubusercontent.com/22683654/98712123-c9e45280-237d-11eb-8c63-4e2edb2f6b32.png)

**Comment by abhishekkumar08** [comment]
@karantakalkar can I work on this issue?

**Comment by karantakalkar** [comment]
I am not sure about the scope of this task, it was a GSoC project this year or last year maybe. I'll suggest you to look for other simpler bugs before taking on such issues.

**Comment by abhishekkumar08** [comment]
Okay will look for the same as said.

**Comment by rrpawar96** [comment]
PR is been created, will be completed soon. https://github.com/openMF/web-app/pull/1299
