### ISSUE TITLE
Create dialog for users to add/remove custom servers.

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#1273]
![Screenshot from 2020-11-16 22-22-41](https://user-images.githubusercontent.com/54709463/99630197-71891100-2a5f-11eb-8647-7eba80d48741.png)

We need a dialog that will allow users to add/remove custom servers in a table, it should open on-click a small button beside server-select field.

Refer:
- Loan accounts table in clients view page (button)
- Add charge stepper in create-savings-account (for table)

Add remove operations should be done on localstorage by settings service.

**Comment by BLasan** [comment]
@karantakalkar Can I work on this?

**Comment by sankha555** [comment]
Hello @karantakalkar , I would like to work on this issue if it's still open for contribution. I have gone through the codebase and have tried to understand the requirements for the task and want to give it a good attempt. Could you please assign this issue to me? Thanks!

**Comment by karantakalkar** [comment]
Go ahead

**Comment by sankha555** [comment]
Hello @karantakalkar , I have made a pull request with the changes I have made to achieve the specifications in the issue. Please take a look at it and let me know your reviews and suggested changes regarding the work. Thanks!
