### ISSUE TITLE
Unable to create client on web app with fineract.dev back-end server

### ISSUE THREAD

**Issue by edcable** [openMF/web-app#1274]
## Description
I was attempting to create a client but receive the following error (invalid parameters were passed in the request):

![Screenshot 2020-11-19 at 5 14 26 PM](https://user-images.githubusercontent.com/823454/99743554-c7bf7980-2a8a-11eb-89ce-0eb75c9bf271.png)

**Comment by edcable** [comment]
I think it's likely due to the Address being enabled but once again I can't add an address field even though the address is enabled as global configuration value and there are available address types.

I get this error when clicking "add" from Address part of stepper. 
![Screenshot 2020-11-19 at 5 36 14 PM](https://user-images.githubusercontent.com/823454/99745074-cb083480-2a8d-11eb-9a54-9f6332461abc.png)

**Comment by karantakalkar** [comment]
@edcable updated.
