### ISSUE TITLE
Savings Account Application

### ISSUE THREAD

**Issue by francisguchie** [openMF/web-app#1278]
**Goal:**

As a user I want to be able to quickly apply for a savings account so that as I create the application, the system takes on the Product defaults
i.e.  Summary in Image below

![image](https://user-images.githubusercontent.com/22683654/101201777-2b879c00-3660-11eb-8fe6-ddef150f3a51.png)

**Comment by ksraj123** [comment]
We could also add the current as the default for Submitted on field in the details step.
<img width="1792" alt="Screenshot 2021-01-06 at 3 48 44 PM" src="https://user-images.githubusercontent.com/39027928/103757487-d5c75a80-5036-11eb-9611-9a81b4d30033.png">

**Comment by karantakalkar** [comment]
@ksraj123 please comment on the issue before starting to work on it.

**Comment by ksraj123** [comment]
@karantakalkar oh, sorry did not know this. Will keep in mind from next time. 

@francisguchie @karantakalkar can you please review my PR. Thanks

**Comment by ramvr1256** [comment]
@bharathcgowda It can be closed now if working as expected.

**Comment by bharathcgowda** [comment]
@ramvr1256  which is the PR for this ticket that has been merged?

**Comment by ramvr1256** [comment]
https://github.com/openMF/web-app/pull/1514

**Comment by bharathcgowda** [comment]
Thanks Ramveer
