### ISSUE TITLE
Predictive text input on Accounting Section for Products creation

### ISSUE THREAD

**Issue by francisguchie** [openMF/web-app#1280]
**Goal:**

As a user I want to be able to type a GL name / gl_code so that I can filter the list of the GLs when in-putting the GL information under the accounting section of the Product (all products) - API https://localhost/products/saving-products/create 
i.e. 
![image](https://user-images.githubusercontent.com/22683654/101210041-bff7fb80-366c-11eb-9c2a-df25c9102b88.png)

**Comment by Abhirup-99** [comment]
can I work on this issue?

**Comment by ksraj123** [comment]
Hey @Abhirup-99 I kind of also worked on this issue sometime back (last year :-) ), almost halfway done and would like to continue if that's not an issue. Thanks
![auto complete](https://user-images.githubusercontent.com/39027928/103820336-2c15b700-5092-11eb-934b-ae8017df462a.gif)

**Comment by Abhirup-99** [comment]
> Hey @Abhirup-99 I kind of also worked on this issue sometime back (last year :-) ), almost halfway done and would like to continue if that's not an issue. Thanks
> ![auto complete](https://user-images.githubusercontent.com/39027928/103820336-2c15b700-5092-11eb-934b-ae8017df462a.gif)

Mate, the issue is opened on Dec 5th. How could you have worked on it before?

**Comment by Abhirup-99** [comment]
You cloned the repo yesterday.
![screenshot-github com-2021 01 07-02_56_23](https://user-images.githubusercontent.com/48902681/103821374-0c7f8e00-5094-11eb-8db6-3d1500b7b1d9.png)
Are you literally kidding me?

**Comment by ksraj123** [comment]
@Abhirup-99 yeah, I forked the repo yesterday to make my first PR. Originally cloned this to my local machine sometime back to explore the codebase, tried to work on this issue for a bit as it seemed interesting. Already shared the state I left my work in.
Btw, there's plenty of room for everyone to contribute.
We are all here to learn.
You are free to work on this, if you want to.

**Comment by Abhirup-99** [comment]
> @ksraj123
> Mate, the issue was opened on Dec 5th. How could you have worked on it before? And if that was the case shouldn't you have mentioned it in the issue at least.

I guess this point still remains valid, no matter when you have cloned it.

**Comment by ksraj123** [comment]
> I guess this point still remains valid, no matter when you have cloned it.
I don't understand, does December 2020 not count as last year?. I too think not really, hence the smiley after "last year" in my original comment.

You can take this if you find this really find this interesting.

Apologies for not commenting sooner, just got to learn this yesterday that we need to comment first. Will keep in mind from next time.

**Comment by Abhirup-99** [comment]
> > I guess this point still remains valid, no matter when you have cloned it.
> 
> @Abhirup-99 I don't understand, does December 2020 not count as last year?. I too think not really, hence the smiley after "last year" in my original comment.
> 
> You can take this up if you really find this interesting.
> 
> Apologies for not commenting sooner, just got to learn this yesterday that we need to comment first. Will keep in mind from next time.

Issue wasn't specifically about December or my love for for this particular issue, it was the approach.Regardless, peace :v:

**Comment by francisguchie** [comment]
> Hey @Abhirup-99 I kind of also worked on this issue sometime back (last year :-) ), almost halfway done and would like to continue if that's not an issue. Thanks
> ![auto complete](https://user-images.githubusercontent.com/39027928/103820336-2c15b700-5092-11eb-934b-ae8017df462a.gif)

Yes @ksraj123 ,
This is what i meant - by predictive text input with account numbers showing on the GL names. Please raise a PR so that all of us can enjoy your efforts

**Comment by karantakalkar** [comment]
@ksraj123 Please work 1 issue at time and don't block multiple issues for yourself currently I assume you were working on #1281. @Abhirup-99 you can look around the app and test features for bugs in case you are short on issues to work on, that would be helpful to us.

**Comment by ksraj123** [comment]
@karantakalkar yes, working on it. This needed.just a little more work so finished this first.

@francisguchie @karantakalkar Please review the PR for this. Thanks

**Comment by francisguchie** [comment]
@ksraj123  thanks for this. I will review over the weekend ( I will do a functional review ) and make my comments here
