### ISSUE TITLE
Move away from travis ci.

### ISSUE THREAD

**Issue by Abhirup-99** [openMF/web-app#1286]
## Description
Travis ci now provides a one-time credit of 10,000 which means 1000 builds on Linux. This is the reason all current builds are not being processed. Move to Github Actions which is free for any public project.

## Steps to Reproduce
Please add as much detail as possible to reproduce the error/issue.
Don't assume the reader knows anything about the Mifos X Web App.

## Settings
- Mifos X version: 
- Browser used:

**Comment by Abhirup-99** [comment]
I can create a pr for the migration.

**Comment by karantakalkar** [comment]
Go ahead

**Comment by Abhirup-99** [comment]
@karantakalkar I have pushed a pr with the build file. I have 2 doubts, have added it in the pr itself, please take a look.
A running example of the file can be found on https://github.com/Abhirup-99/angular-actions-deploy.

**Comment by Abhirup-99** [comment]
I deployed my fork here https://github.com/Abhirup-99/web-app/tree/gh-pages.
Url:https://abhirup-99.github.io/web-app/
