### ISSUE TITLE
Date fields allow inputs in formats which won't be accepted by BE

### ISSUE THREAD

**Issue by Abhirup-99** [openMF/web-app#1295]
## Description
The date fields being text fields accept all types of input.
In the attachment below, I have added 3 types of input. The first two are technically correct but they are violations because of 
- it doesn't follow mm-dd-yyyy 
- it has a date that is invalid in the context as it's a future day.
The last one is a text.
## Steps to Reproduce
Try typing in the date fields.
Don't assume the reader knows anything about the Mifos X Web App.

## Expected Behaviour
Blocks you until you get the right input or right format.
## Actual Behaviour
Doesn't block you.
## Settings
- Mifos X version: 
- Browser used: 

## Screenshots, if any
![Screenshot from 2021-01-11 19-01-07](https://user-images.githubusercontent.com/48902681/104188560-6d65e800-543f-11eb-8d5d-33f9e6f23db8.png)

**Comment by Abhirup-99** [comment]
The issue can be easily solved by opening the calendar when those corresponding date fields are in focus. I can create a pr for this issue.

**Comment by prathameshbhalekar** [comment]
Can I work on this issue?

**Comment by prathameshbhalekar** [comment]
> Can I work on this issue?

@Abhirup-99 ?
