### ISSUE TITLE
improve login page performance and looks

### ISSUE THREAD

**Issue by abhiarrathore** [openMF/web-app#1296]
Currently the image in the login page is of very large size and is of jpg format. This gives a bad impression of overall load time of login page. I propose to reduce the image size and change its file type from jpg to webp. The webp file format is recommended file format for web as it gives better compression.

Original image size - 5.3MB
New image size - ~400KB

And I also wish to change how the login page looks.

Before:
![image](https://user-images.githubusercontent.com/35148394/104200598-e15bbc80-544e-11eb-88ae-909f16c012ad.png)

After:
![image](https://user-images.githubusercontent.com/35148394/104200745-07815c80-544f-11eb-88f9-0f2148a541ab.png)

**Comment by abhiarrathore** [comment]
Can I work on this?

**Comment by karantakalkar** [comment]
Go ahead for image size but don't change the appearance of login page.

**Comment by abhiarrathore** [comment]
ok. sure.

**Comment by edcable** [comment]
@abhiarrathore I would still like to see a mockup of how you might intend to redesign the log-in page. No need to implement a new page but seeing the proposed design would allow us to respond and give feedback. Thanks!

**Comment by abhiarrathore** [comment]
@edcable I will redesign the login page and post it here as soon as it is ready. Thanks!

**Comment by abhiarrathore** [comment]
![REDESIGN 1](https://user-images.githubusercontent.com/35148394/105758304-1c90dc00-5f75-11eb-8a1f-1b0abbf5f7da.png)

This is the first redesign I thought. This is mostly same as the previous one with some changes.

**Comment by abhiarrathore** [comment]
![REDESIGN 2](https://user-images.githubusercontent.com/35148394/105758657-7d201900-5f75-11eb-9af0-571145e54929.png)

This is the second redesign. Very minimal. Clicking on the login at the top-right corner can open a modal or a new page for login.

**Comment by abhiarrathore** [comment]
https://www.figma.com/file/OGQ89gFSyDkYsaCA8Q5MgQ/mifos-login?node-id=1%3A4

This is the figma link of the designs. It has 2 artboards, one for each design.
@edcable please have a look at it.
Thank You!

**Comment by Adityakushwaha142** [comment]
is this issue is still open now !!
