### ISSUE TITLE
TranslateModule not exported from SharedModule 

### ISSUE THREAD

**Issue by chairulakmal** [openMF/web-app#1304]
## Description
ngx-translate TranslateModule not yet imported in SharedModule. This will results in `ERROR in : The pipe 'translate' could not be found`

## Steps to Reproduce
Use the `translate` pipe on HTML components (for example in home.component.html):
```html
<button title="{{ 'Add item' | translate }}">+</button>
```

## Expected Behaviour

`translate` pipe works for i18n.

## Actual Behaviour

`ERROR in : The pipe 'translate' could not be found`

## Settings
- Mifos X version: Fineract 1.4.0
- Browser used: Chrome Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by Abhirup-99** [comment]
translate module hasn't been implemented for the entire app, so this might be part of some small minor additions, here and there.

**Comment by chairulakmal** [comment]
Thanks @Abhirup-99 for the information. I'm currently working on setting up translation, should I push it to upstream later when finished? Or is this not a priority for the project? Cheers!

**Comment by Abhirup-99** [comment]
Thanks for working on this. AFAIK this was supposed to be a GSOC project for this year.

**Comment by bharathcgowda** [comment]
issue resolved
