### ISSUE TITLE
Text not visible in dark mode

### ISSUE THREAD

**Issue by surbhigoel191** [openMF/web-app#1307]
## Description
In dark mode (i.e. last 2 color schemes), text is not visible in quite few places like Keyboard shortcuts.

## Steps to Reproduce
Choose any theme from the last 2 and observe difference.

## Expected Behavior
Text color should change according to the theme as to not hamper the visibility.

## Actual Behaviour
Text not visible.

## Settings
- Mifos X version: 0.0.0
- Browser used: New Edge

## Screenshots, if any
![image](https://user-images.githubusercontent.com/44471561/107073769-c857e880-680d-11eb-94a8-05f6eecd7aad.png)
![image](https://user-images.githubusercontent.com/44471561/107073818-d9085e80-680d-11eb-82b3-6273b613cc69.png)

**Comment by surbhigoel191** [comment]
I will start working on it.

**Comment by BLasan** [comment]
> I will start working on it.

Have you started working on this?

**Comment by bharathcgowda** [comment]
issue is fixed.
