### ISSUE TITLE
I tried to buid the web app in my localsystem but it showing  this eroor will anyone can help

### ISSUE THREAD

**Issue by Adityakushwaha142** [openMF/web-app#1309]
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory     
 1: 00007FF717FA5EBF napi_wrap+114095
 2: 00007FF717F50B46 v8::base::CPU::has_sse+66998
 3: 00007FF717F51946 v8::base::CPU::has_sse+70582
 4: 00007FF718766E4E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF71874EF21 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF71861B18C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF7186263C0 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF718622EE4 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF7186186E3 v8::internal::Heap::CollectGarbage+1283
10: 00007FF718616D54 v8::internal::Heap::AddRetainedMap+2452
11: 00007FF71863809D v8::internal::Factory::NewFillerObject+61
12: 00007FF71839E1E1 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1665
13: 00007FF718BBB3BD v8::internal::SetupIsolateDelegate::SetupHeap+546637
14: 000002D624695FCF

**Comment by Abhirup-99** [comment]
what command did you use?

**Comment by Abhirup-99** [comment]
use `npm run build:prod`

**Comment by Austin-Mislevy** [comment]
@Abhirup-99 Can we close this issue? Seems like there's no further action to take here.
