### ISSUE TITLE
Activation button of holiday is not working

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1315]
## Description
when we create a holiday, we have to activate it, but the Activation button is not working

## Steps to Reproduce
1. go to admin->organization->manage holidays
2. create a holiday
3. try to activate the holiday

## Expected Behaviour
activate button should activate the created holiday

## Screenshots, if any
![image](https://user-images.githubusercontent.com/65952533/112989554-aaaa5e00-9182-11eb-852c-828f29c9f439.png)

**Comment by samerdar123** [comment]
Is the expected functionality just to have the activate button to have a little lock signal and for the holiday to have an activated status on the user's end? Or is there something else that should be happening upon activation?
![image](https://user-images.githubusercontent.com/37407835/115785908-1badf180-a38e-11eb-8a1f-d57cd51895a7.png)

**Comment by bharathcgowda** [comment]
Holidays that are activated only will affect the schedules of loans. in other words, holidays are created to shift the payments and installments which fall on those days, system will do that for holidays that are activated, and not for "pending for activation" status.

clicking on Activate button should internally call the API https://DomainName/api/v1/holidays/{holidayId}?command=activate from where the fineract will take care(as the backend is completely functional in this module)
you can explore the API and parameters in the API doc
https://demo.mifos.io/api-docs/apiLive.htm

**Comment by gustavao** [comment]
Hi, I found the problem adding the request in the service. I've sent pull request 
https://github.com/openMF/web-app/pull/1345
greetings!

**Comment by bharathcgowda** [comment]
issue fixed.
