### ISSUE TITLE
create holiday should select all child offices when parent office is selected (to make it hierarchical)

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1316]
## Description
while creating a holiday, office selection is a checker where a user has to select one office at a time,
we have to make the office select hierarchical, for example, if we select head office by default all offices under head office should be selected.

## Steps to Reproduce
1. create multiple offices under head office (this is for an example to demonstrate hierarchical structure)
2. go to admin->organization->manage holidays->create office
3. select head office( it should auto-select all the offices under head office) but the app only selects head office

## Expected Behaviour
System should auto-select all the offices under the head office, (or any other parent office)
In general, system should select all the child offices when a parent office is selected
## Screenshots, if any
![image](https://user-images.githubusercontent.com/65952533/112990703-f7daff80-9183-11eb-8488-6b09e6430837.png)
![image](https://user-images.githubusercontent.com/65952533/112990772-0aedcf80-9184-11eb-8d5c-c727c5ec4c66.png)

**Comment by ramvr1256** [comment]
@bharathcgowda Can you please confirm that it is working as expected?
