### ISSUE TITLE
Survey functionality Edit option not working

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1323]
## Description
Provide a brief overview of the enhancement or issue.

## Steps to Reproduce
1. go to admin->system->manage surveys
2. create a survey
3. try to edit a survey

## Expected Behaviour
edit option should allow users to modify the survey fields

## Screenshots, if any
![image](https://user-images.githubusercontent.com/65952533/113413426-4f71a900-93d8-11eb-8ec2-55972898b10b.png)

**Comment by Austin-Mislevy** [comment]
Is this an old feature that was implemented and not working properly or has this not been implemented yet?

**Comment by bharathcgowda** [comment]
@Austin-Mislevy  It is an old feature already implemented. but not working.

**Comment by Austin-Mislevy** [comment]
@bharathcgowda Great. I can take a look at this issue.

**Comment by mittulmandhan** [comment]
This issue is resolved in Pull Request [#1282](https://github.com/openMF/web-app/pull/1282) but it is yet to be merged.

**Comment by bharathcgowda** [comment]
fixed
