### ISSUE TITLE
Need Scroll up/down bar to view the loans/savings/Shares in client page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#133]
Example: https://demo.openmf.org/#/viewclient/5 , here the following client has lot of loans/savings etc. 

 when there are more loans/savings/shares, scroll bar to view the clients would make it more efficient.

Scroll bar should be activated only if the number of loans/savings/shares exceed more than 5.

**Comment by meetcric** [comment]
@abhaychawla can I start working on this issue?

**Comment by abhaychawla** [comment]
Go ahead!
