### ISSUE TITLE
Collateral Module

### ISSUE THREAD

**Issue by BLasan** [openMF/web-app#1334]
**Is your feature request related to a problem? Please describe.**
It's better to have a collateral management module in order to manage the collateral data. This can be categorized in to 3 sub components.
1.) Product Level Collateral Module - Add, Edit, Delete and Update collateral

2.) Client Level Collateral Module - Add, Edit, Delete and Update client level collateral data which can then be used to attach to a particular loan.

3.) Loan Level Collateral Module - Attach the collateral in loan application creation process.

**Describe the solution you'd like**
See [PR](https://github.com/openMF/community-app/pull/3398)

**Describe alternatives you've considered**
Get a basic idea from the existing collateral management.

**Additional context**
Currently edit and delete options are not provided for loan level collateral once attached.

**Comment by bharathcgowda** [comment]
completed

**Comment by bharathcgowda** [comment]
@ramvr1256  @adamsaghy  thank you for working over this issue.

Here are the changes required to be made

1. Move the collateral selection screen at the loan level a step above the charges section( it is not related to charges, so we do not have to have it in the charge section)
2. There should not be any validations or configurations to mandate the collateral selection for a loan account
3. User will have the flexibility to select the collateral while creating the loan account from the collateral dropdown. if nothing is selected that means the loan doesn't have any collateral attached to it.
4. User should be able to create a loan account without selecting any collateral 
5. Only when the user attaches the collateral to the loan account, the collateral calculation should be done only for that loan account.
