### ISSUE TITLE
Change background colour

### ISSUE THREAD

**Issue by anweshknayak** [openMF/web-app#135]
Make background color a bit dark so cards are visible

**Comment by abhaychawla** [comment]
This is based on the angular material theme. The theme needs to be modified accordingly to give an appropriate background color throughout the application.

**Comment by anweshknayak** [comment]
The standard for background will be same for all themes. Just a bit darker in the main.scss

**Comment by abhaychawla** [comment]
Yes, the standard may be the same but all theme files will require modification including the angular-material default themes. I am not sure if it will be possible to implement this at main.scss only, based on the background all the components including text are affected.

**Comment by anweshknayak** [comment]
Will check. For now I will be following the above said

**Comment by karantakalkar** [comment]
Any color changes to effect from custom configured themes
