### ISSUE TITLE
Unable to create new Group Loan Application from Group 

### ISSUE THREAD

**Issue by edcable** [openMF/web-app#1351]
## Description

Link from Applications drop down under a Selected Group for Group Loan Application does nothing

## Steps to Reproduce
Navigate to any group, click applications, click Group Loan Application

## Expected Behaviour
Clicking link should trigger create new application
## Actual Behaviour

Nothing occurs
## Settings
Chrome, Mifos X 21.07
![Screenshot 2021-08-05 16 24 46](https://user-images.githubusercontent.com/823454/128434898-7b129218-77ef-49ea-ae17-a67e4ed5752e.png)

**Comment by StevyMarlino** [comment]
hello  can i do that ?

**Comment by edcable** [comment]
Yes please feel free to.

**Comment by bharathcgowda** [comment]
issue is fixed
