### ISSUE TITLE
Link to create new JLG Loan Application from Member listing under Group doesn't work 

### ISSUE THREAD

**Issue by edcable** [openMF/web-app#1352]
## Description
The "plus sign" button create a new JLG loan application for an individual member of a group from the listing of group members at the group level should trigger creating a new loan application but rather it just links to the client record. 

## Steps to Reproduce
Navigate to any group, scroll down to list of members and click JLG Loan Application button next to any members. 

## Expected Behaviour
Window to open a new loan application should pop up. 

## Actual Behaviour

Link directs to the client record page for that individual member. 

## Settings
Mifos X 21.07, Chrome
![Screenshot 2021-08-05 16 43 29](https://user-images.githubusercontent.com/823454/128435207-e743806f-9c82-44a1-b8af-a14b2108737b.png)

**Comment by sksDonni** [comment]
Hi @edcable, just saw that this issue was open and the issue is still persisting in the web app. Can I take this up?
