### ISSUE TITLE
Payment type dropdown not working for make repayment

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1356]
## Description
Payment type dropdown not coming for make repayment

## Steps to Reproduce
1. go to admin->organization->payment type and add payment types.
2. create/disburse a loan account(with any configuration ) and try to make a repayment by selecting a payment type

## Expected Behaviour
expected behavior is that we need to get a drop down to select the payment type during the repayment
## Actual Behaviour
currently the payment type dropdown is empty while making the repayment

![image](https://user-images.githubusercontent.com/65952533/128838451-34f71f56-69a0-4121-8177-c90de93e1dec.png)

**Comment by tonic889** [comment]
I would like to take a look at this one, please assign to me.

**Comment by bharathcgowda** [comment]
Hi, @tonic889  thank you for your interest in looking into this issue, I have assigned the ticket to you now.
Feel free to reach out if you need any more information.

**Comment by adamsaghy** [comment]
Dear @tonic889
In the meantime @josehernandezfintecheandomx has already fixed this issue. Please forgive us to "snatch" this bug from you...
