### ISSUE TITLE
Loan Production Creation not working

### ISSUE THREAD

**Issue by shijesh-kumar** [openMF/web-app#1365]
Hi,

Loan Product Creation screen is not working.

## Steps to Reproduce
1. Click on menu Admin >Product
2. Select Loan product from the list
3.  Click on "Create loan Product" button
4.  In the screen which open on clicking "Create Loan Product" enter all the details
5. Click on Next Button

## Expected Behaviour
System should move to next page/step
## Actual Behaviour
Nothing happens on clicking next button
## Settings
- Mifos X version:  0.0.0.0 
- Browser used: Chrome

## Screenshots, if any
![image](https://user-images.githubusercontent.com/60940794/146434748-f2487625-c026-48b0-bc8a-24a1f0842e0f.png)

**Comment by edcable** [comment]
Confirming that I face this same issue as well. Thanks @shijesh-kumar for logging.

Here is my Chrome Console log:

https://pastebin.com/cDXDWv9c

**Comment by microfinancetest** [comment]
Hi,
[Create Loan Product - Chrome Browser Console Log.log](https://github.com/openMF/web-app/files/10389919/Create.Loan.Product.-.Chrome.Browser.Console.Log.log)
![Create Loan Product Issue](https://user-images.githubusercontent.com/122433959/211749082-8241d36e-59b9-403e-aac5-5a92c94ddf02.png)
[TomCat -catalina.2023-01-11.log](https://github.com/openMF/web-app/files/10389921/TomCat.-catalina.2023-01-11.log)

     Same issue happened in Mifos 21.07.02.Patch release file in Windows Installation. I have installed all Prerequisite Software with your mentioned version. Everything is successful. I can able to log in and do other activities except loan product creation, loan application creation in web-app. 
  
 But loan creation is working perfectly in community-app but only issues with web-app

I have attached tomcat log file , chrome browser console log file and screenshot for your review.
