### ISSUE TITLE
Angular snackbar colour 

### ISSUE THREAD

**Issue by anweshknayak** [openMF/web-app#137]
Change color

Red : Error
Yellow : Warning 
Green : Success

**Comment by anweshknayak** [comment]
@santoshconflux notifications for this color type. Is it okay? Or any other color.

**Comment by abhaychawla** [comment]
@anweshknayak as I told you this will violate the material design guidelines. And this won't be simple to implement and would require theme customization.

**Comment by anweshknayak** [comment]
It won't. Its a standard to be used

**Comment by abhaychawla** [comment]
Have you read the guidelines? The only colors we have are the material theme colors primary, accent and warn. If we change the color explicitly this won't work as they are already fixed within the theme. Changing the color like this would require customizations to the theme and the text colors as well. According to the guidelines, the snack bar should have a solid background color. This is being followed by angular-material by default.

**Comment by anweshknayak** [comment]
I will see and change accordingly

**Comment by anweshknayak** [comment]
The colors mentioned in angular material guidelines. I will pick the green, yellow red rgb variant which is material compatible.

Thanks

**Comment by abhaychawla** [comment]
A particular theme has its colors fixed you cannot choose another three of them for the same. Please ask the mentors before implementation.
