### ISSUE TITLE
Replace Material Icons by Angular Font Awesome Icons

### ISSUE THREAD

**Issue by anweshknayak** [openMF/web-app#138]
Following components have been updated:
- [x] Shared Components
- [x] Login Components
- [x] Shell Components
- [x] Self Service Components
- [x] Accounting Components
- [x] Client Components
- [x] Group Components
- [x] Center Components

**Comment by abhaychawla** [comment]
INFO: Once all components are refactored to use angular font awesome icons, we can remove material icons cdn from `index.html` and font awesome reference from main.scss

**Comment by love-opensource** [comment]
Hello, I'm new here an outreachy applicant.
Can I work on this?

**Comment by abhaychawla** [comment]
Go ahead. Have a look at Clients, Groups and Centers components and replace all the material icons by angular font awesome icons.

**Comment by love-opensource** [comment]
Ok thanks.

**Comment by abhaychawla** [comment]
Kindly do not comment/send email/message on gitter to get your PR reviewed unless a significant amount of time has passed. I know you made a PR. Please be patient while its reviewed.

**Comment by krishnu9** [comment]
Why is this readded in ToDo, @abhaychawla ? What are the things that still need to be done ? I can work on this.

**Comment by abhaychawla** [comment]
Go ahead. The material icons need to be removed from any components that are still using them and replaced by equivalent font awesome icons.

**Comment by krishnu9** [comment]
@abhaychawla, There are no more material icons used in any components.

**Comment by abhaychawla** [comment]
Okay, I will check.

**Comment by Rishabh106** [comment]
There are a few material icons in these files with `<i class="fa {fa-icon-name}"></i>`
https://github.com/openMF/web-app/blob/master/src/app/clients/clients-view/general-tab/general-tab.component.html
https://github.com/openMF/web-app/blob/master/src/app/centers/centers.component.html
https://github.com/openMF/web-app/blob/master/src/app/groups/groups.component.html
![Screenshot_7](https://user-images.githubusercontent.com/36294070/73355072-40b3d180-42bd-11ea-8570-6572538481c5.png)
![Screenshot_8](https://user-images.githubusercontent.com/36294070/73355080-43aec200-42bd-11ea-82d4-e0eab40b5af2.png)

**Comment by Mutahar-Majid** [comment]
@Rishabh106  I've checked the components mentioned by you and would like to replace the font-awesome icons with the Angular Font Awesome Icons.

**Comment by vabshere** [comment]
@Rishabh106 those are regular font awesome icons, not material icons.
