### ISSUE TITLE
Chart of Accounts Tree View does not display

### ISSUE THREAD

**Issue by edcable** [openMF/web-app#1382]
## Description
Clicking the tree view button for chart of accounts results in blank page. 

## Steps to Reproduce
Navigate to accounting, click chart of accounts, click tree view button. 
## Expected Behaviour

Chart of accounts to be displayed in nested tree view. 
## Actual Behaviour

Chart of accounts not displayed on screen. 

## Settings
- Mifos X version: 
- Browser used: 

## Screenshots, if any
![Screenshot 2022-03-11 20 35 45](https://user-images.githubusercontent.com/823454/158004082-155e92a3-554e-444e-8caa-24694205960a.png)

**Comment by bharathcgowda** [comment]
@edcable  there is an existing ticket with more details
Ticket number #578 
Shall we close this ticket to avoid the duplicate tickets?
