### ISSUE TITLE
Unable to click through to any client from clients tab

### ISSUE THREAD

**Issue by edcable** [openMF/web-app#1383]
## Description
When trying to navigate to a client from the clients table, it displays this error - 
Reporting meta-data entry not found. 

## Steps to Reproduce
Navigate to clients, attempt to click any client. 
## Expected Behaviour

Navigate to the client page for the name that was clicked. 
## Actual Behaviour
Doesn't navigate anywhere and only displays this error. 

Reporting meta-data entry not found. 

## Settings
Fineract 1.6
Chroe
## Screenshots, if any
![Screenshot 2022-03-11 20 35 45](https://user-images.githubusercontent.com/823454/158004213-d5a1cdbe-0305-4344-9510-9ad7dd123a59.png)

**Comment by bharathcgowda** [comment]
issue no longer exists
![image](https://user-images.githubusercontent.com/65952533/169595482-fdf57810-b3e9-4c1c-97dc-25e7cfe7935f.png)
