### ISSUE TITLE
Can't view general tab of client

### ISSUE THREAD

**Issue by edcable** [openMF/web-app#1384]
## Description
Unable to view and see the general tab of the client that contains summary of all their accounts. 

## Steps to Reproduce
Navigate to a client and/or click general tab. 

## Expected Behaviour
List of accounts to be displayed 

## Actual Behaviour

Reporting meta-data entry not found error displayed. 

## Settings
- Mifos X version: 
- Browser used: 

## Screenshots, if any

![Screenshot 2022-03-11 20 49 04](https://user-images.githubusercontent.com/823454/158004552-8b5ad57d-d65a-41cb-bd06-82d0e862aca5.png)

**Comment by ren276** [comment]
I think this error is fixed, but if still there then I can help!

**Comment by bharathcgowda** [comment]
Closing this as this issue no longer exists
![image](https://user-images.githubusercontent.com/65952533/169595409-daede979-43b9-46c0-b099-aa47ce966097.png)
