### ISSUE TITLE
Ability to configure targeted server via environment variables

### ISSUE THREAD

**Issue by galovics** [openMF/web-app#1393]
**Is your feature request related to a problem? Please describe.**
Currently there's no way to configure the targeted fineract server via environment variables.
The only way to change it is via editing the web-app.components.ts and environment.prod.ts files but it's definitely more cumbersome than just providing an environment variable configuration.

**Describe the solution you'd like**
Be able to configure the targeted server via environment variable for the docker image and for the frontend application.
If only a single server is configured, the server selector on the login screen should not be visible.

**Comment by bharathcgowda** [comment]
issue is fixed
