### ISSUE TITLE
Audit Trail button not working

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1394]
## Description
Audit Trail button not working when we click on it

## Steps to Reproduce
go to admin->system ->audit trail

## Expected Behaviour
audit trail screen should open
## Actual Behaviour
currently it is not going to audit trail screen
## Settings
- Mifos X version: 
- Browser used: 

## Screenshots, if any
![image](https://user-images.githubusercontent.com/65952533/169591693-5565a3d8-bd47-4ea1-acee-1c606fd222bb.png)

**Comment by adamsaghy** [comment]
**Observation**

It works now :)

**Comment by bharathcgowda** [comment]
it works now, I dunno the reason why it was throwing the "internal server error before". Closing this ticket for now
