### ISSUE TITLE
Unable to add new chart of accounts

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1395]
## Description
not able to add a new chart of account 

## Steps to Reproduce
1. Go to the accounting tab->chart of accounts and click on add account button
2. now try to create any GL.

## Expected Behaviour
A New Ledger should be created when submitted

![image](https://user-images.githubusercontent.com/65952533/169592861-7a53a574-e377-4d70-bb06-8fdcb05b738a.png)

**Comment by adamsaghy** [comment]
**Observation**

When submitting a new GL account, the page does not get refreshed, so it may seems it  was not submitted. However it was. If you click again, you will get an error message as an entry is already exists with the provided GL code.

**Proposal**
UI should be fixed to be redirected to the list of GL accounts after a new entry got submitted

**Comment by bharathcgowda** [comment]
currently being worked by https://github.com/anika-001
