### ISSUE TITLE
Unable to create a Frequent Posting Entry

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1396]
## Description
Unable to create a Frequent Posting Entry

## Steps to Reproduce
go to accounting and client on "frequent postings"

## Screenshots, if any
![image](https://user-images.githubusercontent.com/65952533/169593281-b4b5ef7b-8154-4243-bbc0-158d257fddb7.png)

**Comment by bharathcgowda** [comment]
GSoC student Ramveer is working on this issue
https://github.com/ramvr1256

**Comment by ramvr1256** [comment]
Get API for getting Accounting rules is failing from the backend. Raised a fineract ticket [https://issues.apache.org/jira/browse/FINERACT-1630](https://issues.apache.org/jira/browse/FINERACT-1630)

**Comment by bharathcgowda** [comment]
Issue is fixed at backend, and working as expected
