### ISSUE TITLE
Not able to create a manual journal entry

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1397]
## Description
Not able to pass a manual journal entry, when you click on submit button, it is showing internal server error

## Steps to Reproduce
1. go to accounting
2. click on "create journal entries"
3. enter the details and press submit

## Expected Behaviour
need to submit the the manual journal entry which clicked on submit button
## Settings
- Mifos X version: 
- Browser used: 

## Screenshots, if any
![image](https://user-images.githubusercontent.com/65952533/169593950-e9be903c-05c7-411a-8fe6-f6b736c66ae6.png)

**Comment by adamsaghy** [comment]
Error:
{"timestamp":"2022-05-24T23:43:24.569+00:00","status":500,"error":"Internal Server Error","path":"/fineract-provider/api/v1/journalentries"}

Needs further investigation...

**Comment by adamsaghy** [comment]
Fixed
