### ISSUE TITLE
Not able to add "Accounting rules"

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1398]
## Description
Not able to add "Accounting rules"

## Steps to Reproduce
Go to accounting and click on the "Accounting rules" option
## Screenshots, if any
![image](https://user-images.githubusercontent.com/65952533/169594309-12b2479b-222d-4a89-9f37-19080544e3b1.png)

**Comment by bharathcgowda** [comment]
GSoC student Ramveer is working on this issue
https://github.com/ramvr1256

**Comment by ramvr1256** [comment]
Get API for getting Accounting rules is failing from the backend. Raised a fineract ticket [https://issues.apache.org/jira/browse/FINERACT-1630](https://issues.apache.org/jira/browse/FINERACT-1630)

**Comment by bharathcgowda** [comment]
Issue is fixed at backend, and working as expected
