### ISSUE TITLE
Modification of Existing Datatables not working

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1403]
## Description
Modification of Existing Datatables not working

## Steps to Reproduce
1. Go to admin->systems->manage datatables
2. select existing datatable, modify any field and submit

## Settings
- Mifos X version: 
- Browser used: 

## Screenshots, if any
![image](https://user-images.githubusercontent.com/65952533/170038896-6ed002e5-4660-4a4e-8b4e-769793287855.png)

**Comment by bharathcgowda** [comment]
this issue is assigned to https://github.com/anika-001

**Comment by Rolence** [comment]
![image](https://user-images.githubusercontent.com/11888675/171567601-d782ee10-2b6b-466b-8e1b-ec9529998a70.png)
The field for subEntityType has been removed totally. Datatables can't be created again

**Comment by bharathcgowda** [comment]
Hi @anika-001 did you get any change to look into this issue?

**Comment by anika-001** [comment]
Hi, yes, on my system, after editing an existing data-table, the information is stored successfully, without any error messages.

(before editing): 
![image](https://user-images.githubusercontent.com/62497183/181614690-85ab0693-50a4-4b3c-a5fd-cff01a9d820d.png)

(after editing)
![image](https://user-images.githubusercontent.com/62497183/181614836-528db871-41b5-4216-8eab-3716d9679d7f.png)

**Comment by bharathcgowda** [comment]
@anika-001  Did you fix this issue locally?  if yes can you send the PR for the same?

**Comment by anika-001** [comment]
Yes, I'll create a PR for the same.

**Comment by anika-001** [comment]
In community app, we similarly show the dropdown(attached), with the name legal form for EntitySubType.  
![image](https://user-images.githubusercontent.com/62497183/189038069-6d3082f8-1a46-4b78-b169-f84d60e4655a.png)
