### ISSUE TITLE
Unable to create new loan product or share product

### ISSUE THREAD

**Issue by edcable** [openMF/web-app#1406]
## Description
Go to admin >> products and attempt to create either a loan product or share product. Upon submission after fully specifying all parameters, the following error is displayed: 

<img width="1364" alt="Screen Shot 2022-05-25 at 3 04 45 PM" src="https://user-images.githubusercontent.com/823454/170377156-03789aef-7852-4ceb-b143-100f5411a556.png">

Functionality works fine for deposit, fixed deposit, and recurring deposit products. 

## Steps to Reproduce
Configure loan product with all required parameters. 

## Expected Behaviour

Loan to be successful created. 

## Actual Behaviour

Error message displayed - Invalid parameters were passed in the request!

## Settings
Fineract 1.7 on Chrome browser.

**Comment by adamsaghy** [comment]
@edcable I was able to create a Loan account. Could you please retest and share your configuration if the issues is still persisting?
