### ISSUE TITLE
mandatory date fields flash red during submission of any transaction

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1416]
## Description
mandatory date fields flash red during submission of any transaction
any transactions actions like 

make loan approval
make loan disbursement
make repayment 
add loan charge
make foreclose
make prepay loan
waive interest
etc
 any financial entry on the loan account having mandatory date field is having this issue

Same issue with respect to the savings account, FD account, RD account and shares account

## Steps to Reproduce
Please add as much detail as possible to reproduce the error/issue.
Don't assume the reader knows anything about the Mifos X Web App.

## Expected Behaviour
when the mandatory fields are filled, the system should again not flash the mandatory again, check screenshots for reference

## Screenshots, if any
![image](https://user-images.githubusercontent.com/65952533/170715638-d252ea36-2390-4b40-8295-76e172cdc8c7.png)
![image](https://user-images.githubusercontent.com/65952533/170715666-3acc4b7a-b8f1-4a91-8628-ef569949731e.png)

**Comment by adamsaghy** [comment]
@bharathcgowda I challenge you! I strongly believe the  Make Repayment do not have the flash and the red during submission! :)

However if you still see it that means 1 thing:
- You need to clear the cache because something old got cached on your machine

**Comment by bharathcgowda** [comment]
@adamsaghy  aah Yes, you fixed it yesterday :), I just wanted to give as much information as possible on the screens, and forgot about the fix which came yesterday. 
can you share how you fixed it here? the hint which was discussed on slack?
that could be helpful for others who picks this

**Comment by bharathcgowda** [comment]
fixed
