### ISSUE TITLE
Date Selection Improvement

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1417]
## Description
any screen which is having a date to enter, it is not poping up the date-picker automatically once the field is selected.

## Steps to Reproduce
-go to create client
- Click on Date of Birth Field
## Expected Behaviour
when you go to any date field, a date picker should automatically pop up
## Settings
- Mifos X version: 
- Browser used: 

## Screenshots, if any
![image](https://user-images.githubusercontent.com/65952533/170716110-a2dbcaac-d7ce-400c-9a55-699cbfdb2c5c.png)

**Comment by ramvr1256** [comment]
Working as expected throughout the App. The issue Can be closed.

**Comment by bharathcgowda** [comment]
fixed
