### ISSUE TITLE
view client screen is not showing the client who are pending for activation

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1418]
## Description
the view client screen is not showing the client who is pending activation
with status: Pending

## Steps to Reproduce
-create a client( do not activate )
- go back to view client screen (institution->clients)

## Screenshots, if any
![image](https://user-images.githubusercontent.com/65952533/170717650-6955890e-f6dd-4ba5-98ab-84adac6397ef.png)

**Comment by adamsaghy** [comment]
@bharathcgowda You will find them under the "closed clients" and thats a bug...

**Comment by bharathcgowda** [comment]
fixed
