### ISSUE TITLE
Checker Inbox & tasks button not working

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1436]
## Description
Checker Inbox @ tasks button not working, showing internal server error while clicking on the button

## Steps to Reproduce
->login
->click on Checker Inbox & tasks button

## Screenshots, if any
![image](https://user-images.githubusercontent.com/65952533/173342136-9b885a57-96aa-49f5-8401-f090c6b45642.png)

**Comment by josehernandezfintecheandomx** [comment]
This is related to a Fineract SQL sentence with bad grammar in the group by @bharathcgowda
