### ISSUE TITLE
Breadcrumbs Issues on many screens

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1437]
## Description
Breadcrumbs Issues on many screens like clients, groups, and centers don't show the links properly.
refer to screenshots for an example

## Steps to Reproduce
1. go to client->loan_application, breadcrumbs should have names instead of IDs similar to community-app
2. go to groups ->clients->loan,  breadcrumbs should have names instead of IDs similar to community-app
3. same issue with center hierarchy
4. same issue with admin->products->loan/savings/other products 

## Screenshots, if any
![image](https://user-images.githubusercontent.com/65952533/173381856-1da2268c-b1f7-49ea-b2e5-c33a902f522f.png)

**Comment by ramvr1256** [comment]
@bharathcgowda  I have covered as many screens as I found. Can you once check what all other places I need to implement this breadcrumb fix?

**Comment by bharathcgowda** [comment]
Thanks @ramvr1256 , for tracking purposes I will close this issue for now, as all the Important places it has been fixed.
