### ISSUE TITLE
Passing wrong parameter into API related to Home/Organization/Bulk Loan/Reasssignment

### ISSUE THREAD

**Issue by duyhungdh10** [openMF/web-app#1440]
## Description
Something wrong in Home/Organization/Bulk Loan/Reasssignment.
Passing wrong parameter into API: /loans/loanreassignment/template?fromLoanOfficerId=abc&officeId=xyz
I have checked code in web-app\src\app\organization\organization.service.ts (line 97) and found this:

```
  /**
   * Get Officer Template.
   * @param officerId Officer Id.
   * @param officeId Office Id.
   */
  getOfficerTemplate(officerId: string, officeId: string): Observable<any> {
    const httpParams = new HttpParams()
                       .set('fromLoanOfficerId', officerId.toString())
                       .set('officeId', officerId.toString()); 
    return this.http.get('/loans/loanreassignment/template', { params: httpParams });
  }
```

In line 97, why did you use `officerId.toString()` insteal of  `officeId.toString()` ? I think it's a misstake.

## Screenshots, if any
![image](https://user-images.githubusercontent.com/49611362/174220652-d4bdc724-9041-4d9d-869a-74f1467cafa8.png)

**Comment by bharathcgowda** [comment]
@ramvr1256 Could you look into this issue?

**Comment by bharathcgowda** [comment]
fixed
