### ISSUE TITLE
After login the screen is not refreshed: stuck on login page

### ISSUE THREAD

**Issue by adamsaghy** [openMF/web-app#1452]
## Description
After login the screen is not refreshed: stuck on login page.

## Steps to Reproduce
1. Login
2. It says it was logged in, however the input fields are emptied and error message is shown for them to be provided
3. The screen is not refreshed, stuck on the login page
4. If you remove everything after the / and refresh you are got on the homepage.

## Expected Behaviour
After login, it goes to the homepage and not stuck on the login screen
## Actual Behaviour
Stuck on the login screen
## Settings
- Mifos X version: 
- Browser used:

**Comment by ramvr1256** [comment]
Fixed now.
