### ISSUE TITLE
Cannot create overdue charge from UI

### ISSUE THREAD

**Issue by adamsaghy** [openMF/web-app#1461]
## Description
The UI is preventing to create overdue charge as the request does not contain the **mandatory** "penalty" field.

Request:
{"chargeAppliesTo":1,"name":"Random Overdue charge","currencyCode":"EUR","chargeTimeType":9,"chargeCalculationType":1,"amount":"500","active":true,"chargePaymentMode":0,"monthDayFormat":"dd MMM","locale":"en"}

## Steps to Reproduce
Try to create a new charge where the Charge time type is "Overdue Fees".

## Expected Behaviour
The charge can be created.

## Actual Behaviour
Error occurs

## Settings
- Mifos X version: 
- Browser used: 

## Screenshots, if any
<img width="1548" alt="image" src="https://user-images.githubusercontent.com/7602740/177994449-c2b3c306-706a-4a74-a0e5-49b387faa66b.png">

**Comment by josehernandezfintecheandomx** [comment]
@adamsaghy PR sent to Fix that

**Comment by bharathcgowda** [comment]
fixed
