### ISSUE TITLE
Stuck on the login page

### ISSUE THREAD

**Issue by HARSH-nith** [openMF/web-app#1473]
## Description
Stuck on the login page of the openmf web app (https://openmf.github.io/web-app/)
An error message is also showing on the top right corner of the screen

## Steps to Reproduce
Click on the link (https://openmf.github.io/web-app/)

## Settings
- Mifos X version: 
- Browser used:  Chrome

## Screenshots, if any
![login page issue 1](https://user-images.githubusercontent.com/75531664/179391168-9f1dd845-f8f5-4815-a894-57ade91135a1.jpg)

**Comment by ramvr1256** [comment]
Working now.
