### ISSUE TITLE
Savings Product - Edit Product - Accounting - Previously saved accounts are not pre-selected in the drop-downs

### ISSUE THREAD

**Issue by peter-santa-dpc** [openMF/web-app#1475]
## Description
When opening a Savings Product for edit, the Accounting related fields are not pre-filled with the previously saved values.

## Steps to Reproduce
1. Have GL accounts created of each type (Asset, Liability, Income, Expense) on Accounting / Chart of Accounts. Set "DETAIL" as Account Usage. Have unique GL code for each (does not matter, what number, just unique in the system). Account name is irrelevant, just remember it for step 3.
2. Have a Fee and a Penalty typed Charge created on Admin / Products / Charges. (They will be needed for Advanced Accounting Rules)
3. Create a Savings product on Admin / Products / Savings Products. Details are irrelevant, just fill the mandatory fields with random values. Only important: on **Accounting screen** set the radio button to **"Cash"**, and **select a GL account in every dropdown, including Advanced Accounting Rules**.
4. Save the product.
5. On Admin / Products / Savings Products click on the product. On the opening details view, in the Accounting section, the saved accounting rules can be seen. So far it is OK.
6. Open the product for edit, with clicking the Edit button, and navigate to the "Accounting" view.

## Expected Behaviour
The previously saved accounts should be pre-selected in the drop-downs of the accounts.

## Actual Behaviour
The "Cash" radio button is correctly selected, but none of the drop-downs have the previously saved accounts. Neither the Advanced Accounting Rules

## Settings
- Mifos X version: according to the UI: Version 0.0.0 :) This might be a bug also... It is reproducible with the commit hash 6e973dd50aba148edc26e7b8e6bb2433c1522b71
- Browser used: Chrome Version 103.0.5060.114 (Official Build) (x86_64)

## Screenshots, if any
![1  After filling the Accounting rules](https://user-images.githubusercontent.com/45198877/179537596-d3fbfb99-30be-41eb-a492-8c49cdc4f927.png)
![2  Checking the saved accounting rules](https://user-images.githubusercontent.com/45198877/179537867-1a8b48c0-2925-4fcb-bc77-c2073b4b7160.png)
![3  Editing the Savings Product](https://user-images.githubusercontent.com/45198877/179537979-e52517d6-ccf5-4fb4-96d8-6d1dec6517c1.png)

**Comment by adamsaghy** [comment]
@peter-santa-dpc Can you please retest?
