### ISSUE TITLE
Chart of Accounts - Tree view does not work

### ISSUE THREAD

**Issue by peter-santa-dpc** [openMF/web-app#1476]
## Description
It is expected to see the hierarchy of accounts in Accounting / Chart of Accounts / Tree View. But it does not work.

## Steps to Reproduce
1. Have GL accounts created of each type (Asset, Liability, Income, Expense, Equity) on Accounting / Chart of Accounts. Set "HEADER" as Account Usage. Have unique GL code for each (does not matter, what number, just unique in the system).
2. Have GL accounts created of each type (Asset, Liability, Income, Expense, Equity) on Accounting / Chart of Accounts. Set "DETAIL" as Account Usage. Have unique GL code for each (does not matter, what number, just unique in the system). **Have a parent set for each.**
3. On Accounting / Chart of Accounts click on Tree view.

## Expected Behaviour
The hierarchy of accounts should be shown:

- Asset
- - Asset account with "HEADER" usage
- - - Asset account, with "DETAIL" usage
- - - Asset account, with "DETAIL" usage
- - Asset account with "HEADER" usage
- - - Asset account, with "DETAIL" usage
- - - Asset account, with "DETAIL" usage
- Liability
- - Liability account with "HEADER" usage
- - - Liability account, with "DETAIL" usage
- - - Liability account, with "DETAIL" usage
- - Liability account with "HEADER" usage
- - - Liability account, with "DETAIL" usage
- - - Liability account, with "DETAIL" usage
- Income
- - Income account with "HEADER" usage
- - - Income account, with "DETAIL" usage
- - - Income account, with "DETAIL" usage
- - Income account with "HEADER" usage
- - - Income account, with "DETAIL" usage
- - - Income account, with "DETAIL" usage
- Expense
- - Expense account with "HEADER" usage
- - - Expense account, with "DETAIL" usage
- - - Expense account, with "DETAIL" usage
- - Expense account with "HEADER" usage
- - - Expense account, with "DETAIL" usage
- - - Expense account, with "DETAIL" usage
- Equity
- - Equity account with "HEADER" usage
- - - Equity account, with "DETAIL" usage
- - - Equity account, with "DETAIL" usage
- - Equity account with "HEADER" usage
- - - Equity account, with "DETAIL" usage
- - - Equity account, with "DETAIL" usage

## Actual Behaviour
The Tree view does not work. Sometimes totally empty, sometimes shows the Account Types (have not found out, depends on what). But **it never shows the correct hierarchy.**

## Settings
- Mifos X version: Version 0.0.0 :) This might be a bug also... It is reproducible with the commit hash https://github.com/openMF/web-app/commit/6e973dd50aba148edc26e7b8e6bb2433c1522b71
- Browser used: Chrome Version 103.0.5060.114 (Official Build) (x86_64)

## Screenshots, if any
![Chart of Accounts - List view](https://user-images.githubusercontent.com/45198877/179544055-2e67aaee-7c25-4ac6-8628-863396fb5207.png)
![Chart of Accounts - Tree view](https://user-images.githubusercontent.com/45198877/179544061-862714e4-1d20-4920-96b9-dd5c423bc86a.png)

**Comment by anika-001** [comment]
The issue is no longer present in web app, tree structure loads as expected. [Attached Image]
![image](https://user-images.githubusercontent.com/62497183/189034144-b38c6ee5-c0ae-4002-83e4-07cce0c00c38.png)
