### ISSUE TITLE
Manage Offices: List Offices - Tabular View

### ISSUE THREAD

**Issue by edcable** [openMF/web-app#148]
**Goal:**

As an operations manager or system administrator I want to view a list of offices in tabular format so that I can see the offices created and create new ones. 

For this task, we need to re-implement the view for listing offices in a tabular view along with the available actions at the top of the page located at https://demo.openmf.org/#/offices

Resources
* User Manual: https://mifosforge.jira.com/wiki/spaces/docs/pages/67141727/Manage+Offices
*  API Docs: https://demo.openmf.org/api-docs/apiLive.htm#offices

See
![screen shot 2018-07-24 at 12 05 29 pm](https://user-images.githubusercontent.com/823454/43160661-a5502cfc-8f3a-11e8-9a69-b2cb0f633ec3.png)

**Comment by An0u** [comment]
@edcable  I'd like to work on this as part of my contributions.

**Comment by abhaychawla** [comment]
@An0u you may go ahead. But make sure that you implement this view only and not any other view/component which is not a part of this issue.
