### ISSUE TITLE
Manage Offices: List Offices - Tree View

### ISSUE THREAD

**Issue by edcable** [openMF/web-app#149]
**Goal:**

As an operations manager or system administrator I want to view a list of offices in tree view so that I can see the full office hierarchy and in a nested view which offices belong to which parent offices as seen at https://demo.openmf.org/#/offices

Resources:

* User Manual: https://mifosforge.jira.com/wiki/spaces/docs/pages/67141727/Manage+Offices
* API Docs: https://demo.openmf.org/api-docs/apiLive.htm#offices

 See
![screen shot 2018-07-24 at 12 12 09 pm](https://user-images.githubusercontent.com/823454/43160708-cfdebf1a-8f3a-11e8-89d7-3a0be3ddc457.png)

**Comment by shobhi1310** [comment]
@karantakalkar 
Sir, 
Is this issue still active, like @Rishabh106 has made a PR to it, so asking or else can I try to look into it ?
