### ISSUE TITLE
Currency Configuration: Add/Edit Currency

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#152]
Goal:
As an operations manager or system administrator, I am able to add or remove currencies. 
https://demo.openmf.org/#/currconfig

Resources:
https://demo.openmf.org/api-docs/apiLive.htm#configs

https://mifosforge.jira.com/wiki/spaces/docs/pages/67141734/Currency+Configuration

![add edit currency](https://user-images.githubusercontent.com/23022667/43181037-dc6f71a2-8ff8-11e8-8676-1e3272d415d5.png)

**Comment by aditya-sarkar441** [comment]
@santoshconflux  I'll like to work on this.

**Comment by aditya-sarkar441** [comment]
@santoshconflux  I'll like to work on this.
