### ISSUE TITLE
Manage: Holidays: Holidays List

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#153]
Goal:
As a System Administrator, I want to view list of holidays which are already defined, as seen at 

https://demo.openmf.org/#/holidays

Resources: 
https://mifosforge.jira.com/wiki/spaces/docs/pages/67141730/Manage+Holidays

https://demo.openmf.org/api-docs/apiLive.htm#holidays

![manage holidays holiday list](https://user-images.githubusercontent.com/23022667/43181222-a8cdd310-8ff9-11e8-8876-a468ebf2d5f6.png)

**Comment by i-am-g2** [comment]
I want to work on this, please assign this to me.

**Comment by abhaychawla** [comment]
Go ahead but make sure you only implement this screen and not any of the other screens which this is dependent upon.

**Comment by gaganeggday** [comment]
Hey!! Can I start working on this issue if its incomplete!!

**Comment by abhaychawla** [comment]
Go ahead. Make sure you follow what I said above.

**Comment by Rishabh106** [comment]
Can I work on this issue? @abhaychawla

**Comment by abhaychawla** [comment]
Go ahead.

**Comment by Rishabh106** [comment]
@abhaychawla I'm facing an issue while updating the data table after selection of an Office, I'll show how I tried on gitter.

**Comment by abhaychawla** [comment]
What is the issue?
