### ISSUE TITLE
500 error trying to retrieve a loan application

### ISSUE THREAD

**Issue by josephgodwinkimani** [openMF/web-app#1535]
## Description

I am getting an error trying to pull loan applications for **all or single client**:

```
{
    "timestamp": 1663398527370,
    "status": 500,
    "error": "Internal Server Error",
    "message": "",
    "path": "/fineract-provider/api/v1/loans/6"
}

```

## Steps to Reproduce

1. Make a Loan Application for an active client `web-app/clients/1/loans-accounts/create`
2. As an Administrator pull loan application `web-app/clients/1/loans-accounts/2/general`

## Expected Behaviour

I expected a loan summary from this backend GET request `/fineract-provider/api/v1/loans/2?associations=all&exclude=guarantors,futureSchedule`

## Actual Behaviour

The network monitor shows this error for said request:

```
{
    "timestamp": 1663398527370,
    "status": 500,
    "error": "Internal Server Error",
    "message": "",
    "path": "/fineract-provider/api/v1/loans/6"
}

```

## Settings

- Mifos X version: Mifos 21.0.7.2
- Browser used: Firefox 104.0.2 (64-bit)
- instance: `some-domain/fineract-provider/api/v1`

**Comment by adamsaghy** [comment]
@josephgodwinkimani Please share some extra information. Which backend instance you were targeting with the UI? Is it one of the demo backend or your own?

The above mentioned type of error is indicating an error happened in the backend.

**Comment by josephgodwinkimani** [comment]
> @josephgodwinkimani Please share some extra information. Which backend instance you were targeting with the UI? Is it one of the demo backend or your own?
> 
> The above mentioned type of error is indicating an error happened in the backend.

True. For some peculiar reasons MifosX 21.0.7.2 only works with openjdk 15.0.2 only. Therefore this issue is not related to Mifos X Web App
