### ISSUE TITLE
Manage Holidays: Create Holiday

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#154]
Goal:
As a system administrator, I want to define holiday for branch office or Head office  which is applicable to all branch offices.  

Resources:

https://mifosforge.jira.com/wiki/spaces/docs/pages/67141730/Manage+Holidays

https://demo.openmf.org/api-docs/apiLive.htm#holidays

![create holiday](https://user-images.githubusercontent.com/23022667/43181352-3e93b392-8ffa-11e8-9e32-09cdb3c01ce7.png)

**Comment by e-stephane** [comment]
Hello @santoshconflux can i work on this issue?

**Comment by DivineWisdom** [comment]
Hello I would like to work on this issue

**Comment by DivineWisdom** [comment]
@abhaychawla 
 I have submitted a PR for this issue
