### ISSUE TITLE
Create Client with basic required fields errors with 400 Bad request

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1555]
## Description

I'm using https://sandbox.mifos.community/#/clients/create. I fill the required(*) fields, after `submit`, I get `400` error code on console. 

User error on app: `Invalid parameters were passed in the request!`.

Is there something I'm missing?

## Steps to Reproduce

Fill required fields (only) as `Person`: 

<img width="1532" alt="Screenshot 2022-11-09 at 6 17 38 PM" src="https://user-images.githubusercontent.com/4143778/200834340-9f005af1-fdbd-4ce2-ae59-44d074e1634b.png">

## Expected Behaviour

Should create client successfully.

## Actual Behaviour

User error on app: `Invalid parameters were passed in the request!`. 
Error code: 400 Bad request.

## Settings
- Mifos X version: https://sandbox.mifos.community/#/clients/create
- Browser used: Version 105.0.5195.125 (Official Build) (x86_64)

## Screenshots, if any

Added. A few more:
<img width="1552" alt="Create Client" src="https://user-images.githubusercontent.com/4143778/200835217-0fc705f5-d808-400f-98d1-752a56756911.png">

<img width="1552" alt="Basic Fields Create Client" src="https://user-images.githubusercontent.com/4143778/200835286-54aa239e-ae1e-4b50-b34c-d1365d55bf1e.png">

<img width="1552" alt="Family members empty" src="https://user-images.githubusercontent.com/4143778/200835332-48cd7df7-491e-40ef-859a-cd233155f916.png">

<img width="1552" alt="submit" src="https://user-images.githubusercontent.com/4143778/200835393-7277c98f-2483-4d8c-9470-d230f3de32a3.png">

Ref: https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

cc @edcable.

**Comment by bharathcgowda** [comment]
@tapaswenipathak  could you please try with adding all the fields for family details?
