### ISSUE TITLE
Search on dashboard is a 404

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1556]
## Description

Search on dashboard is a 404

## Steps to Reproduce

https://sandbox.mifos.community/#/dashboard

## Expected Behaviour

Search success.

## Actual Behaviour

404.

## Settings
- Mifos X version: https://sandbox.mifos.community/#/dashboard
- Browser used: Google Chrome Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

<img width="1434" alt="Screenshot 2022-11-10 at 11 16 11 AM" src="https://user-images.githubusercontent.com/4143778/201010527-e3897bd0-f296-49f7-b1d5-2d2b3ffbcaa2.png">
<img width="1434" alt="Screenshot 2022-11-10 at 11 16 57 AM" src="https://user-images.githubusercontent.com/4143778/201010626-6a191b01-a59a-41e7-b5aa-f52380bd849a.png">
<img width="1424" alt="Screenshot 2022-11-10 at 11 17 10 AM" src="https://user-images.githubusercontent.com/4143778/201010655-40f655c8-83d8-47bb-9865-5c850ccda01d.png">

Ref: https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

cc @edcable.

**Comment by bharathcgowda** [comment]
@anika-001  could you please review this issue?
