### ISSUE TITLE
Tree view button doesn't work

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1557]
## Description

Tree view doesn't change anything or send a query on console or a network call.

## Steps to Reproduce
https://sandbox.mifos.community/#/organization/offices

1. Add 4 offices.
2. Office A -> Parent Office: Head Office
3. Office B -> Parent Office: Office A
4. Office C -> Parent Office: Head Office
5. Office D-> Parent Office: Office B

## Expected Behaviour

Tree view (in some form, a binary tree in this case):

A
B C
D

## Actual Behaviour

Nothing.

## Settings
- Mifos X version: https://sandbox.mifos.community/#/organization/offices
- Browser used: Google Chrome Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

<img width="1440" alt="Screenshot 2022-11-13 at 3 47 40 PM" src="https://user-images.githubusercontent.com/4143778/201516909-79c58b4d-f4e2-402b-b6f7-52cc3ee1dcc2.png">

Ref: https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

cc @edcable.

**Comment by bharathcgowda** [comment]
@anika-001  could you please review this issue?
