### ISSUE TITLE
Busy/Polling/status bar on top keeps on moving from left to right

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1558]
## Description

Create something, and till reload or reopen of tab, the Busy/Polling/status bar keeps on moving from left to right.

## Steps to Reproduce

Create anything.

## Expected Behaviour

Just a few times, indicating the time taken to fulfill user process/request.

## Actual Behaviour

Continues to move, in a infinite loop.

## Settings
- Mifos X version: https://sandbox.mifos.community/
- Browser used: Google Chrome Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

GIF attached.

https://user-images.githubusercontent.com/4143778/201517532-37e37e01-99d5-408d-873b-f59059b44930.mov

Ref: https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

cc @edcable.

**Comment by bharathcgowda** [comment]
@anika-001  could you please review this issue?

**Comment by anika-001** [comment]
Hi, I'm unable to replicate the issue. I've created client, group, and center (attached videos), the bar stops moving post the submission.

![Untitled design (7)](https://user-images.githubusercontent.com/62497183/202846467-f5660b47-afd5-4fd2-8525-1f8f3fcb8626.gif)
