### ISSUE TITLE
Not all employees shown in a group

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1559]
## Description

Not all employees shown in a group, while assigning staff.

## Steps to Reproduce

1. Create 5 employees.
2. Create 5 groups.
3. Assign staff to group B as Employee B.
4. Only 3 Employees shown.

## Expected Behaviour

All employees should be listed.

## Actual Behaviour

Only 3 Employees shown.

## Settings
- Mifos X version: https://sandbox.mifos.community/
- Browser used: Google Chrome Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

List of Employees:

<img width="1436" alt="Screenshot 2022-11-13 at 4 02 48 PM" src="https://user-images.githubusercontent.com/4143778/201517658-aac287e1-e82a-402c-bc5b-839e8139959c.png">

List in Assign Staff for Group B:

<img width="1433" alt="Screenshot 2022-11-13 at 4 12 04 PM" src="https://user-images.githubusercontent.com/4143778/201517668-cbe0267a-d2bb-4db5-9859-1f839a26c0ab.png">

Ref: https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

cc @edcable.

**Comment by bharathcgowda** [comment]
@anika-001 could you please review this issue?

**Comment by anika-001** [comment]
Hi, I wanted to clarify, is this issue occurring when we go to the group created and try to assign staff? (here:http://localhost:4200/#/groups/93/actions/Assign%20Staff)

I've created 5 groups and 5 employees, was getting all the 5 employees in the dropdown to select.
Attached Image:
![image](https://user-images.githubusercontent.com/62497183/202852671-946c8073-946f-482d-b8ca-e1d5eeeb53a7.png) 
(I created the Emp1-ann to Emp5-ann)

**Comment by bharathcgowda** [comment]
@anika-001 thank you for adding your observation, while we get some review on this, could you please look into other assigned tickets?

**Comment by anika-001** [comment]
Yes, will do that.

**Comment by tapaswenipathak** [comment]
Doesn't work.

<img width="1438" alt="Screenshot 2023-01-29 at 6 28 12 PM" src="https://user-images.githubusercontent.com/4143778/215327701-0724df97-dbbe-498a-8897-ef4e482fde29.png">

<img width="1432" alt="Screenshot 2023-01-29 at 6 28 31 PM" src="https://user-images.githubusercontent.com/4143778/215327711-808518b1-dd98-4d79-bcaa-2e138a2e1466.png">
