### ISSUE TITLE
Click on + in Manage Groups Shows Internal Server Error

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1561]
## Description

Click on + in Manage Groups Shows Internal Server Error

https://sandbox.mifos.community/#/centers/1/actions/Manage%20Groups

## Steps to Reproduce

1. Open any center.
2. Click on Manage Groups.
3. Click on +.

## Expected Behaviour

User error.

## Actual Behaviour

Internal Server Error.

## Settings
- Mifos X version: https://sandbox.mifos.community/#/centers/1/actions/Manage%20Groups
- Browser used: Google Chrome Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

<img width="1440" alt="Screenshot 2022-11-13 at 4 26 26 PM" src="https://user-images.githubusercontent.com/4143778/201518235-ef1e600c-d486-40c3-b0f3-546392577115.png">

Ref: https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

cc @edcable.

**Comment by bharathcgowda** [comment]
@anika-001  could you please review this issue?
