### ISSUE TITLE
Create Client lists Office in random order

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1562]
## Description

Create Client lists Office in random order
## Steps to Reproduce

1. Create client using: https://sandbox.mifos.community/#/clients/create
2. Click on Office.

## Expected Behaviour

1. Alphabetical or creation date or activate date order.

## Actual Behaviour

1. Random order.

## Settings
- Mifos X version:  https://sandbox.mifos.community/#/clients/create
- Browser used: Google Chrome Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

Create Client:

<img width="1440" alt="Screenshot 2022-11-13 at 4 31 27 PM" src="https://user-images.githubusercontent.com/4143778/201518387-adce9001-b9db-42ee-9d9f-b3fa9cdc4d17.png">

List of offices:

<img width="1426" alt="Screenshot 2022-11-13 at 4 33 21 PM" src="https://user-images.githubusercontent.com/4143778/201518420-7a22fd72-1937-4c86-abfb-75b1e4dc3843.png">

Ref: https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

cc @edcable.

**Comment by bharathcgowda** [comment]
@tapaswenipathak  it is not random, it displays in the parent-child relation order.
This is the current working way in community-app, hence closing this issue.
