### ISSUE TITLE
Name Decorated field has 4 dots prepended to its value in Manage Offices

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1563]
## Description

Name Decorated field has 4 dots prepended to its value in Manage Offices

## Steps to Reproduce

1. Create Office.
2. Go to Manage Office.
3. Click on any office other than Head Office.

## Expected Behaviour
Name Decorated should show Name of the office, for example: Head Office.

## Actual Behaviour

```
Name Decorated : ....Office A
```

## Settings
- Mifos X version: https://sandbox.mifos.community/#/organization/offices/2/general
- Browser used: Google Chrome Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

Office A:
<img width="1439" alt="Screenshot 2022-11-13 at 4 35 12 PM" src="https://user-images.githubusercontent.com/4143778/201518574-a05df38e-cdd0-4a78-a6a1-568dda02ecdd.png">

Head Office:
<img width="1433" alt="Screenshot 2022-11-13 at 5 38 15 PM" src="https://user-images.githubusercontent.com/4143778/201520892-4260822e-da40-4258-b9d1-dabafef97d2a.png">

Ref: https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

cc @edcable.

**Comment by bharathcgowda** [comment]
@tapaswenipathak  this is not an issue, all the child branches are appended with the dots, which is the current way working in community-app as well, hence closing this issue.
