### ISSUE TITLE
Add Clients + Errors as "ERROR TypeError" in Manage Members in a Group 

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1565]
## Description

Unable to add clients in Manage Members in a Group.

## Steps to Reproduce

1. Create Group.
2. Open created Group.
3. Click Manage Members.
4. Type in Add Clients on https://sandbox.mifos.community/#/groups/6/actions/Manage%20Members.
5. Click on +

## Expected Behaviour

Successful addition of Client.

## Actual Behaviour

Console Error:

```
ERROR TypeError: Cannot read properties of undefined (reading 'includes')
    at t.addClient (main.6c52092b92530a765916.js:1:3965595)
    at main.6c52092b92530a765916.js:1:3967713
    at uh (main.6c52092b92530a765916.js:1:354417)
    at Y (main.6c52092b92530a765916.js:1:354584)
    at HTMLButtonElement.<anonymous> (main.6c52092b92530a765916.js:1:1260103)
    at f.invokeTask (polyfills.c7e0f5ea238f0d7415bb.js:1:8294)
    at Object.onInvokeTask (main.6c52092b92530a765916.js:1:436317)
    at f.invokeTask (polyfills.c7e0f5ea238f0d7415bb.js:1:8215)
    at f.runTask (polyfills.c7e0f5ea238f0d7415bb.js:1:3350)
    at f.invokeTask [as invoke] (polyfills.c7e0f5ea238f0d7415bb.js:1:9429)
Mh @ main.6c52092b92530a765916.js:1
value @ main.6c52092b92530a765916.js:1
pm @ main.6c52092b92530a765916.js:1
uh @ main.6c52092b92530a765916.js:1
Y @ main.6c52092b92530a765916.js:1
(anonymous) @ main.6c52092b92530a765916.js:1
f.invokeTask @ polyfills.c7e0f5ea238f0d7415bb.js:1
onInvokeTask @ main.6c52092b92530a765916.js:1
f.invokeTask @ polyfills.c7e0f5ea238f0d7415bb.js:1
f.runTask @ polyfills.c7e0f5ea238f0d7415bb.js:1
f.invokeTask @ polyfills.c7e0f5ea238f0d7415bb.js:1
b @ polyfills.c7e0f5ea238f0d7415bb.js:1
R @ polyfills.c7e0f5ea238f0d7415bb.js:1
M @ polyfills.c7e0f5ea238f0d7415bb.js:1
```

## Settings
- Mifos X version: https://sandbox.mifos.community/#/groups/6/actions/Manage%20Members
- Browser used: Google Chrome Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any
<img width="1439" alt="Screenshot 2022-11-13 at 5 57 24 PM" src="https://user-images.githubusercontent.com/4143778/201521618-26e0e715-abde-44fb-a17a-e1accf0d397b.png">

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

cc @edcable.

**Comment by bharathcgowda** [comment]
Hi @anika-001  could you please review this issue?

**Comment by anika-001** [comment]
Hi, can you share if the created group had 'active' or 'pending' status? @tapaswenipathak 

My understanding is that we can't add clients to a pending status group. To resolve the same, I can disable the message and add a notification to notify user for the same.

**Comment by bharathcgowda** [comment]
@anika-001  if we are able to add clients from the active groups, then this is not an issue. you can disable the add buttons when the group is inactive.
