### ISSUE TITLE
Gender not getting updated while creating client: No dropdown or text writing enabled

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1566]
## Description

Gender not getting updated while creating client: No dropdown or text writing enabled: https://sandbox.mifos.community/#/clients/create.

## Steps to Reproduce

1. Create Client in https://sandbox.mifos.community/#/clients/create.
2. Try updating Gender field.

## Expected Behaviour

Gender field updating, dropdown or text update enabled?

## Actual Behaviour

Nothing happens.

## Settings
- Mifos X version: https://sandbox.mifos.community/#/clients/create
- Browser used: Google Chrome Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any
<img width="1440" alt="Screenshot 2022-11-14 at 10 38 41 AM" src="https://user-images.githubusercontent.com/4143778/201580159-20522d2d-0eea-4ed4-bf92-16bc0d04affa.png">

https://user-images.githubusercontent.com/4143778/201580257-03edcae6-e603-4121-8b59-889af5b00fcd.mov

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

cc @edcable.

**Comment by bharathcgowda** [comment]
Hi @tapaswenipathak
This is not an issue
did you add the gender code values in the manage codes?

All the drop downs in Mifos are dynamic where you can list the dropdown values under "admin-> systems->manage codes.
Then the drop downs will come.

**Comment by tapaswenipathak** [comment]
<img width="1440" alt="Screenshot 2023-01-29 at 4 37 12 PM" src="https://user-images.githubusercontent.com/4143778/215322116-e6c644ce-8254-4d38-98e5-a586fc1813f3.png">

<img width="1439" alt="Screenshot 2023-01-29 at 4 37 20 PM" src="https://user-images.githubusercontent.com/4143778/215322102-87ead89b-625b-4678-8949-c13e5d8f3e8f.png">


https://user-images.githubusercontent.com/4143778/215322125-bed2a44d-1f55-45bf-bbb4-7139b24c7ea7.mov

`Gender` dropdown doesn't work still.

(I didn't add `Gender` in manage codes)

cc @edcable.

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.
