### ISSUE TITLE
Not able to Create Savings Account: Savings Product not working while creating client

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1567]
## Description

Savings Product not working while creating client: No dropdown or text writing enabled: https://sandbox.mifos.community/#/clients/create

## Steps to Reproduce
1. Create client: https://sandbox.mifos.community/#/clients/create.
2. Enter the required fields.
3. Try entering Savings Product.

## Expected Behaviour

1. Saving Product field take the data.

## Actual Behaviour

Nothing happens.

Errors save as it is a required field for Opening Savings Account.

## Settings
- Mifos X version: https://sandbox.mifos.community/#/clients/create
- Browser used: Google Chrome Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

<img width="1440" alt="Screenshot 2022-11-14 at 10 43 34 AM" src="https://user-images.githubusercontent.com/4143778/201580710-5844124f-cd47-4fb1-b473-5242ab0089d9.png">

https://user-images.githubusercontent.com/4143778/201580817-519ed26e-8f4e-4964-ade4-770143b20472.mov

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

cc @edcable.

**Comment by bharathcgowda** [comment]
Hi @tapaswenipathak  this is not an issue. in order to create a savings account, we need to create a savings product first
Under admin->products->savings products.

**Comment by tapaswenipathak** [comment]
https://github.com/openMF/web-app/issues/1664.
