### ISSUE TITLE
Negative value is allowed in Age field while creating Family Member of Client

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1568]
## Description

Negative value is allowed in Age field while creating Family Member of Client

## Steps to Reproduce

1. Add a Family Member of Client.
2. Try updating Age.

## Expected Behaviour

1. 0 to N

## Actual Behaviour

1. -N to N

## Settings
- Mifos X version: https://sandbox.mifos.community/
- Browser used: Google Chrome Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

<img width="1301" alt="Screenshot 2022-11-14 at 10 46 05 AM" src="https://user-images.githubusercontent.com/4143778/201581166-bbb0ea9f-ea32-41eb-a37d-6879e20a8b76.png">

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

cc @edcable.

**Comment by bharathcgowda** [comment]
@anika-001  can you please review and fix this issue?

**Comment by bharathcgowda** [comment]
fixed

**Comment by tapaswenipathak** [comment]
Adding `age` errors on console.

<img width="1434" alt="Screenshot 2023-01-29 at 5 48 00 PM" src="https://user-images.githubusercontent.com/4143778/215325716-3621d55e-64bb-4e7d-9db8-ae65d3c97fa6.png">

Ref https://github.com/openMF/web-app/issues/1666.
