### ISSUE TITLE
Relationship Update not working in Add Family Member of Client

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1569]
## Description

Relationship Update not working in Add Family Member of Client: https://sandbox.mifos.community/#/clients/create

## Steps to Reproduce

1. Create a Client.
2. Add Family Member.
3. Try updating the Relationship.

## Expected Behaviour

1. Relationship field working.

## Actual Behaviour

1. Relationship field doesn't work,

## Settings
- Mifos X version: https://sandbox.mifos.community/#/clients/create
- Browser used: Google Chrome Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

<img width="1436" alt="Screenshot 2022-11-14 at 10 48 15 AM" src="https://user-images.githubusercontent.com/4143778/201581359-02fdb600-9faa-4938-a644-fdf999c5c54d.png">

https://user-images.githubusercontent.com/4143778/201581405-5aba2a2b-3ad7-494b-9063-e8d009f818fd.mov

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

cc @edcable.

**Comment by bharathcgowda** [comment]
Hi @tapaswenipathak  
This is not an issue
did you add the relationship code values in the manage-codes?

Most of the drop downs in Mifos are dynamic where you can list the dropdown values under "admin->systems->manage codes.
Then the drop downs will come.
for now I have added the relationship 'father' in that instance, so you should be able to see the father value in the dropdown now. In the same way you can add all the retaionships
![image](https://user-images.githubusercontent.com/65952533/202128735-b6aa918a-bc1b-46f3-bb84-9ab3ad93aa20.png)
