### ISSUE TITLE
Manage Employees: Create an Employee

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#157]
Goal:

As a System Admin, I must be able to create an employee/staff, as seen at https://demo.openmf.org/#/createemployee/

![create employee](https://user-images.githubusercontent.com/23022667/43181826-a036563e-8ffc-11e8-9a0d-334904c77239.png)

Resources: 
https://mifosforge.jira.com/wiki/spaces/docs/pages/67141732/Manage+Employees

https://demo.openmf.org/api-docs/apiLive.htm#staff_create

!

**Comment by abhaychawla** [comment]
@love-opensource Do not comment and try to claim multiple issues at once. You can work on a single issue at a time only. I will not allow this.

**Comment by love-opensource** [comment]
Sorry for that @abhaychawla.
I won't do that next time.

Thanks.

**Comment by Claude-Kamaha** [comment]
@abhaychawla  please can I work on this?
