### ISSUE TITLE
No Client Profile in Navigation

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1570]
## Description

No Client Profile in Navigation

## Steps to Reproduce
1. Follow this https://docs.mifos.org/mifosx/user-manual/side-bar-features/navigation
2. Last step feature is not present in https://sandbox.mifos.community/#/navigation

## Expected Behaviour

@edcable.

## Actual Behaviour
1. No Client Profile.

## Settings
- Mifos X version: https://sandbox.mifos.community/#/navigation
- Browser used: Google Chrome Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any
<img width="1440" alt="Screenshot 2022-11-14 at 11 12 00 AM" src="https://user-images.githubusercontent.com/4143778/201584398-0bf3fdd8-fdff-4425-a760-0883446576fb.png">

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

**Comment by bharathcgowda** [comment]
@anika-001  can you please review this?

**Comment by anika-001** [comment]
Yes, on it.
