### ISSUE TITLE
Bulk Loan Reassignment

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#158]
As a System Admin, I want assign all the loans from a loan officer to other loan officer belonging to other office or same office as seen at https://demo.openmf.org/#/bulkloan

![bulkloan](https://user-images.githubusercontent.com/23022667/43181916-02ed52e6-8ffd-11e8-815c-57bd2541501a.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67141738/Bulk+Loan+Reassignment

**Comment by michealmikeyb** [comment]
Can I take on this. I'm new to angular but this one doesn't seem as hard. Also there currently is no organization folder in the project, should this go in some other folder or should I create an organization folder.

**Comment by abhaychawla** [comment]
@michealmikeyb We have a pending PR for organisation section where the folder was created and I have requested some changes. To avoid conflicts if you create another folder its better you take up some other issue for the time being.
