### ISSUE TITLE
Teller Cashier Management: List View

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#159]
Goal: 
As a system admin, I want to view all the tellers as seen at, https://demo.openmf.org/#/tellers

![tellercashier](https://user-images.githubusercontent.com/23022667/43182198-0b65484c-8ffe-11e8-971c-d9f40d2e6c4c.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/86114424/Teller+Cashier+Management

https://demo.openmf.org/api-docs/apiLive.htm#tellercashmgmt

**Comment by abhaychawla** [comment]
Edit/Delete button to be removed from this component and shifted into view teller to ensure consistency. `View` button to be renamed to `view cashier`.

**Comment by punwai** [comment]
@abhaychawla to ensure consistency, should I not remove the View button entirely? In other pages, clicking on the row redirects to the specific item instead anyways.

**Comment by abhaychawla** [comment]
@punwai Its a bit different case here. We will still have the case where clicking on the row will get us to `view teller` page with data of that teller. The `view cashier` button on the other hand will take us to the list of cashiers related to that teller once fully developed.
