### ISSUE TITLE
Teller Cashier Management: Create Teller

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#160]
Goal:
 As a system admin, I want to create a teller, as seen at,
https://demo.openmf.org/#/createTeller

![createteller](https://user-images.githubusercontent.com/23022667/43182298-711e0e44-8ffe-11e8-9db6-ebbb164c3288.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/86114424/Teller+Cashier+Management

https://demo.openmf.org/api-docs/apiLive.htm#createtellers

**Comment by spider0061** [comment]
@abhaychawla I would like to work on this issue.

**Comment by abhaychawla** [comment]
Ok
