### ISSUE TITLE
New Loan Application: Page missing on https://demo.mifos.community/?

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1600]
## Description

Where can I find New Loan Application Page? on https://demo.mifos.community/.

Search doesn't show anything and I couldn't find in categories.

## Steps to Reproduce

Images Provided on : https://docs.mifos.org/mifosx/user-manual/for-all-users/untitled/form-page

App URL: https://demo.mifos.community/

Search URL: https://demo.mifos.community/#/search?query=loan%20application&resource=clients,clientIdentifiers,groups,savings,shares,loans

## Expected Behaviour

New Loan Application form page somewhere.

## Actual Behaviour

Couldn't find anything.

## Settings
- Mifos X version: https://demo.mifos.community/
- Browser used: 

## Screenshots, if any

<img width="1409" alt="Screenshot 2022-12-19 at 7 29 46 PM" src="https://user-images.githubusercontent.com/4143778/208443414-e8c14ade-adcc-45cb-94c8-d361cb880d6e.png">

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

cc @edcable.

**Comment by PC-11-00** [comment]
- Go to Clients
- Select the active client
- Click the hamburger icon 
- Click applications, and then choose new loan account

https://user-images.githubusercontent.com/76156941/220904549-d0366af4-2750-4c42-a8eb-17c68139e9f0.mov
