### ISSUE TITLE
Not able to create loans product

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1601]
## Description

1. Create loans product using https://demo.mifos.community/#/products/loan-products/create with basic and necessary fields.

## Steps to Reproduce

Create loans product using https://demo.mifos.community/#/products/loan-products/create as shown in the screenshots below 

delinquency bucket dropdown configuration is mandatory, but not shown in the UI, and error msg is wrong

## Expected Behaviour
The system has to through a proper readable error msg "that delinquency bucket configuration is missing" 
Loans Product created.

## Actual Behaviour

Error: `Invalid parameters were passed in the request!`.

## Settings
- Mifos X version: https://demo.mifos.community/
- Browser used: Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

1st Screen:

<img width="1438" alt="Screenshot 2022-12-19 at 8 51 14 PM" src="https://user-images.githubusercontent.com/4143778/208459449-5fce408c-2e08-45cc-8110-1ba5c64d4874.png">

2nd Screen:

<img width="1439" alt="Screenshot 2022-12-19 at 8 51 53 PM" src="https://user-images.githubusercontent.com/4143778/208459577-83c1cd52-d01b-466e-b4d5-e8e45cb55be1.png">

3rd Screen:

<img width="1440" alt="Screenshot 2022-12-19 at 8 52 41 PM" src="https://user-images.githubusercontent.com/4143778/208459763-555c22a2-ae71-429b-aba3-b66e3c580daf.png">

<img width="1436" alt="Screenshot 2022-12-19 at 8 52 56 PM" src="https://user-images.githubusercontent.com/4143778/208459830-367aaa7c-41c9-486b-9fc5-62c3cf7bc1e8.png">

4th Screen:

<img width="1440" alt="Screenshot 2022-12-19 at 8 53 17 PM" src="https://user-images.githubusercontent.com/4143778/208459901-f52e436c-5737-4801-889e-c62bf63000c3.png">

<img width="1438" alt="Screenshot 2022-12-19 at 8 54 01 PM" src="https://user-images.githubusercontent.com/4143778/208460038-18bd1d64-ece3-4f8f-a38d-209b54cf6eda.png">

<img width="1437" alt="Screenshot 2022-12-19 at 8 54 15 PM" src="https://user-images.githubusercontent.com/4143778/208460083-aa7483ec-e624-4f72-a4e1-abbc9267fb7f.png">

5th Screen:

<img width="1440" alt="Screenshot 2022-12-19 at 8 55 06 PM" src="https://user-images.githubusercontent.com/4143778/208460304-df8c17a9-caeb-41cb-b07f-bedd1d5396b4.png">

6th Screen:

<img width="1440" alt="Screenshot 2022-12-19 at 8 56 08 PM" src="https://user-images.githubusercontent.com/4143778/208460545-1a0b5508-b402-496a-a469-913f75bf1974.png">

Final Screen:

<img width="1440" alt="Screenshot 2022-12-19 at 8 56 28 PM" src="https://user-images.githubusercontent.com/4143778/208460631-7794202f-f232-4d57-b880-c23eba2d74e0.png">

<img width="1440" alt="Screenshot 2022-12-19 at 8 56 54 PM" src="https://user-images.githubusercontent.com/4143778/208460698-ef20b40b-0ce6-4336-9ad1-9be658c3f1d7.png">

<img width="1440" alt="Screenshot 2022-12-19 at 8 57 11 PM" src="https://user-images.githubusercontent.com/4143778/208460755-879380a2-6b20-4408-9b50-8516a7d19102.png">

<img width="1440" alt="Screenshot 2022-12-19 at 8 57 27 PM" src="https://user-images.githubusercontent.com/4143778/208460808-a423e329-052e-48dd-a1b6-54be0f1cba42.png">

Error after submit:

<img width="1440" alt="Screenshot 2022-12-19 at 8 57 51 PM" src="https://user-images.githubusercontent.com/4143778/208460903-9262cfaa-4e93-435e-b65f-f50346b2d34a.png">

Ref https://github.com/openMF/mifos-documentation/issues/14.

cc @edcable.

**Comment by bharathcgowda** [comment]
This issue is because the "delinquency bucket" is not classified for the loan product.
However, the error msg is wrong.

I have edited the tickets for the proper error msg fix
