### ISSUE TITLE
Not able to create loans account

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1602]
## Description

Not able to create a loans account on https://demo.mifos.community/#/clients/2/loans-accounts/create.

This is for last three screenshots present on https://docs.mifos.org/mifosx/user-manual/for-all-users/untitled/loan-product-and-accounting-with-mifos.

Ref https://github.com/openMF/web-app/issues/1601.

## Steps to Reproduce

1. Create loans account https://demo.mifos.community/#/clients/2/loans-accounts/create.
2. Product Name dropdown doesn't show anything.

## Expected Behaviour

Create loans account.

## Actual Behaviour

Error in Product Name field.

## Settings
- Mifos X version: https://demo.mifos.community/
- Browser used: Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

<img width="1440" alt="Screenshot 2022-12-19 at 9 02 28 PM" src="https://user-images.githubusercontent.com/4143778/208462341-2744a817-543a-49ea-a3c2-5cec8834a889.png">

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

cc @edcable.

**Comment by bharathcgowda** [comment]
not able to reproduce the issue. once the loan account is created, the drop-down appears properly
