### ISSUE TITLE
Pop Over Issue in Home Screen Tour

### ISSUE THREAD

**Issue by PC-11-00** [openMF/web-app#1609]
## Description
The pop over of frequent postings is not visible in Google Chrome browser in Mac Os Ventura, it's coming below the screen.
## Steps to Reproduce
- Open the demo website: https://demo.mifos.community/
- Click on the configuration wizard from head tool baar
- Then start the Home Screen Tour
- Then click on next until we reach the frequent postings.
- When we reach on Frequent postings pop over ,then we will not able to see the next button.
- I have to reload the website.
## Expected Behaviour
-It should show the pop over above the frequent posting option so that we can click on the next button and proceed forward 
## Actual Behaviour
-It is showing the pop over below the frequent posting option and we can't able to proceed forward and we have to reload the website.
## Settings
- Mifos X version: Demo Website (https://demo.mifos.community/)
- Browser used: Google Chrome(MAC OS)

## Screenshots, if any
<img width="1440" alt="Screenshot 2022-12-28 at 10 14 11 PM" src="https://user-images.githubusercontent.com/76156941/209859147-09cbc063-0d88-48fe-8511-059da2f27bf5.png">

**Comment by Gingaaa** [comment]
Hi i am new to the open source can you assign me this task so i can check the popup and correct the position of it.

**Comment by PC-11-00** [comment]
Hi Gingaaa , I have already solved this issue and sent the pr: https://github.com/openMF/web-app/pull/1636 .
