### ISSUE TITLE
Teller Cashier Management: Create Cashier

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#161]
Goal: 
As a system admin, I want to create a cashier at https://demo.openmf.org/#/tellers/13/createCashierForTeller

![cccashier](https://user-images.githubusercontent.com/23022667/43182385-d7b7ce7e-8ffe-11e8-9e10-d33cdf7590c3.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/86114424/Teller+Cashier+Management

https://demo.openmf.org/api-docs/apiLive.htm#createcashier

**Comment by spider0061** [comment]
Can I work on it?

**Comment by pembemiriam** [comment]
@abhaychawla I wish to work on this issue.

**Comment by abhaychawla** [comment]
Go ahead.

**Comment by aditya-sarkar441** [comment]
@santoshconflux I'll like to work on this.
