### ISSUE TITLE
Tab name is variable {{ 'APP_NAME' | translate }} on demo.mifos.commmunity version

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1615]
## Description

Open login page: https://demo.mifos.community/

<img width="1089" alt="Screenshot 2023-01-02 at 3 01 33 PM" src="https://user-images.githubusercontent.com/4143778/210214039-df882071-c808-423e-b255-1629ed97d991.png">

May be it should be hardcoded?

## Steps to Reproduce
Please add as much detail as possible to reproduce the error/issue.
Don't assume the reader knows anything about the Mifos X Web App.

## Settings
- Mifos X version: 
- Browser used: 

## Screenshots, if any

cc @edcable.

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

**Comment by khanjasir90** [comment]
@tapaswenipathak can i work on this?
