### ISSUE TITLE
Working Days

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#162]
Goal:
As a system admin, I want to define working and non-working days and move the payments to other day, as seen at, https://demo.openmf.org/#/workingdays

![workingdays](https://user-images.githubusercontent.com/23022667/43182538-6562481c-8fff-11e8-9363-e417050a036b.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/90243212/Working+Days

https://demo.openmf.org/api-docs/apiLive.htm#workingdays

**Comment by abhaychawla** [comment]
@love-opensource Do not comment and try to claim multiple issues at once. You can work on a single issue at a time only. I will not allow this.

**Comment by sayamss** [comment]
hello, i am currently working on this issue as part of google code in task, Anything you want me to know?

**Comment by giorgiozoppi** [comment]
Ok i will review deeply soon. The first observations is that working days should be take in account an API like holidayapi.com  with a selection box on the week of the year on the top right. This allows to define the behavior of payments during the year by location and nationality.

**Comment by abhaychawla** [comment]
Another student is working on the task now. The API already exits for the same. Its a reimplementation from the community app.
