### ISSUE TITLE
Not able to create client

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1622]
## Description

Create client using https://demo.mifos.community/#/clients/create, errors as `Internal Server Error. Please try again late`.

## Steps to Reproduce

1. Create client using https://demo.mifos.community/#/clients/create
2. Fill in basic/asterisk/required fields.
3. Error code `500`.
4. Error on console:

```
headers
: 
Ne {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}
message
: 
"Http failure response for https://demo.mifos.community/fineract-provider/api/v1/clients: 500 OK"
name
: 
"HttpErrorResponse"
ok
: 
false
status
: 
500
statusText
: 
"OK"
url
: 
"https://demo.mifos.community/fineract-provider/api/v1/clients"
```
<img width="1440" alt="Screenshot 2023-01-04 at 8 49 30 PM" src="https://user-images.githubusercontent.com/4143778/210587942-ad421758-1c4f-4053-b1c0-0acb50bd19d4.png">

## Expected Behaviour

Create client success.

## Actual Behaviour

Internal server error, might be a temp.

## Settings
- Mifos X version: https://demo.mifos.community/
- Browser used: Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

<img width="1431" alt="Screenshot 2023-01-04 at 8 51 44 PM" src="https://user-images.githubusercontent.com/4143778/210588433-9ec17e4f-e0b1-481f-becf-9278d45a03a3.png">

cc @edcable.

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

**Comment by PC-11-00** [comment]
It's resolved, it will update on the [demo  ](https://demo.mifos.community/) soon.

https://user-images.githubusercontent.com/76156941/220996661-d6c9f4b1-b410-4bed-9de5-58bde2f879db.mov
