### ISSUE TITLE
No way to refresh on Transfer Client: Office field if office created in another tab/window

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1625]
## Description

No way to refresh on Transfer Client: Office field if office created in another tab/window. After creating `Office A` in separate tab, another API call doesn't get triggered to fetch newly created offices.

<img width="1440" alt="Screenshot 2023-01-04 at 9 18 24 PM" src="https://user-images.githubusercontent.com/4143778/210594140-0deeaf5c-d734-4fec-97df-e5e456328765.png">

## Steps to Reproduce

1. Select any existing client and Transfer Client https://demo.mifos.community/#/clients/2/actions/Transfer%20Client.
2. Create another Office in another window or tab, https://demo.mifos.community/#/organization/offices.
3. Select `office` field dropdown in Transfer Client.
4. Only previous list of offices are shown, appears after a reload of the page.

## Expected Behaviour

1. As the API call is triggered on clicking on the dropdown of `Office` field on Client Actions Page, it should fetch all existing offices, even if they are created in different tab or windows.

## Actual Behaviour
1. Newly created offices shown only after a reload.

## Settings
- Mifos X version: https://demo.mifos.community/
- Browser used: Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

<img width="1435" alt="Screenshot 2023-01-04 at 9 22 27 PM" src="https://user-images.githubusercontent.com/4143778/210594985-97649a25-1d8a-4e63-ba27-a27efcea6031.png">

<img width="1435" alt="Screenshot 2023-01-04 at 9 22 37 PM" src="https://user-images.githubusercontent.com/4143778/210595024-28d8bc47-be26-48ea-bc4d-91e0d342f0e3.png">

cc @edcable.

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

**Comment by adolfobcruz** [comment]
Hi! 
Is this still open? I think that I can help. :)
