### ISSUE TITLE
Not able to create data table

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1627]
## Description

Not able to create data table. Fill required fields, add a column, click on submit.

Error code: 400
Error message: 

```
Invalid parameters were passed in the request!
```
## Steps to Reproduce

1. Create data table: https://demo.mifos.community/#/system/data-tables/create
2. Fill required fields.
3. Add column.
4. Click on submit.
5. Error message: `Invalid parameters were passed in the request!`
6. Console error:

<img width="1440" alt="Screenshot 2023-01-04 at 9 42 35 PM" src="https://user-images.githubusercontent.com/4143778/210599295-f570b39e-02b9-4ab9-9ecc-06bad80a91e5.png">

## Expected Behaviour

1. New data table created.

Am I missing something? Any hidden field(s)?

## Actual Behaviour

1. Error: `Invalid parameters were passed in the request!`

## Settings
- Mifos X version: https://demo.mifos.community/
- Browser used: Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

cc @edcable.

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.
Ref https://github.com/openMF/web-app/issues/1626.

**Comment by Subzer0570** [comment]
Hello @tapaswenipathak 
I wouldlike to work on this issue
Can you please assign this issue to me

**Comment by josehernandezfintecheandomx** [comment]
In this specific case, Datatable for a `Client` entity is required a `Subtype` for the entity, for example If this datatable will be for `Entity` Clients or `Person` Client
