### ISSUE TITLE
Add Clients: Create Group: Search for a client does not show Client Details

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1629]
## Description

Add Clients: Create Group: Search for a client does not show Client Details
<img width="1430" alt="Screenshot 2023-01-05 at 12 55 58 PM" src="https://user-images.githubusercontent.com/4143778/210724864-4e27606c-2903-497c-a4ac-2951dad4335f.png">

<img width="1439" alt="Screenshot 2023-01-05 at 12 56 15 PM" src="https://user-images.githubusercontent.com/4143778/210724909-1fc5573a-742c-4ae0-a0c1-3f6655f76852.png">

## Steps to Reproduce

1. Create a few clients.
2. Create group using: https://demo.mifos.community/#/groups/create.
3. In `Add Clients` field, search for existing clients.
4. Client details, empty.

## Expected Behaviour

1. Last I created, I was able to see client details.
2. May be a temp?

## Actual Behaviour

1. Client details empty in `Add Clients` after search.

## Settings
- Mifos X version: https://demo.mifos.community/
- Browser used: Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

cc @edcable.

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

**Comment by Subzer0570** [comment]
Hello
I would like to work on this issue
Also can you guide me on setting mifos local server
