### ISSUE TITLE
Payment Types : List

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#163]
Goal:
As an organization admin, I want to view payment channels (Ex; cash, cheque) used for transactions as seen at, 
https://demo.openmf.org/#/viewpaymenttype/

![ptype](https://user-images.githubusercontent.com/23022667/43182711-1c02d352-9000-11e8-87f3-1d860ceb28f1.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/90243216/Payment+type
https://demo.openmf.org/api-docs/apiLive.htm#paymenttype

**Comment by aashish-ak** [comment]
@abhaychawla  Interested in working on this.

**Comment by abhaychawla** [comment]
@aashish-ak You may go ahead but make sure that you take into account that there is already an existing PR for organization section using which you would need to link to this screen. You will have to take that into account. Do not create any files unrelated to this component. If you think that might be difficult then I'd suggest you take up some other issue.

**Comment by aashish-ak** [comment]
Thanks for the info @abhaychawla , I've almost completed my work on this issue, for now i'll take up another one, but please comment here and inform when the `organization` PR gets merged, i'll modify my code and then open a PR on this issue.

**Comment by aashish-ak** [comment]
Also should i avoid all the issues involving `organization` ?

**Comment by abhaychawla** [comment]
@aashish-ak You worked at your own risk. Please ask for working on the issue on your own when you see yourself fit to work on it. I will reiterate on the fact that you shouldn't work on multiple issues at once. Its at your own risk.

**Comment by aashish-ak** [comment]
Actually i worked on this one alone and completed it within a few hours before your comment, that's why, i took other issue only after your comment, i didn't work on multiple issues.
