### ISSUE TITLE
Groups: Group B: More: Attach Meeting: Error code: 400: Not able to attach meeting to a group

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1630]
## Description

Attach meeting to a group results into 400, `POST` call to API `polyfills.d6b90775acb5227c.js:1          POST https://demo.mifos.community/fineract-provider/api/v1/groups/4/calendars 400` is a 400.

<img width="1440" alt="Screenshot 2023-01-05 at 1 02 30 PM" src="https://user-images.githubusercontent.com/4143778/210725840-00c5ec04-5bba-47e1-8dc1-078f29210aa4.png">

## Steps to Reproduce

1. Open `Group B` or say, any group: https://demo.mifos.community/#/groups/4/general.
2. `Attach Meeting`: https://demo.mifos.community/#/groups/4/actions/Attach%20Meeting.
3. Pick any date.
<img width="1440" alt="Screenshot 2023-01-05 at 1 03 27 PM" src="https://user-images.githubusercontent.com/4143778/210726004-f6303ca8-170b-46e1-ad71-7c6375b3052e.png">
4. Click on submit.
5. Errors.

<img width="1437" alt="Screenshot 2023-01-05 at 1 03 51 PM" src="https://user-images.githubusercontent.com/4143778/210726115-4ff2daff-24fd-4823-b752-5513113550b3.png">

## Expected Behaviour

1. Able to attach meeting.

## Actual Behaviour
1. 400 error code.

## Settings
- Mifos X version: https://demo.mifos.community/
- Browser used: Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

cc @edcable.

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

**Comment by josehernandezfintecheandomx** [comment]
It's fixed in the PR https://github.com/openMF/web-app/pull/1647 

@bharathcgowda please close it

**Comment by bharathcgowda** [comment]
@josehernandezfintecheandomx  thank you for fixing
