### ISSUE TITLE
Group: Add Clients button unresponsive/nothing happens

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1631]
## Description

Click on `Add Clients` button on `Group B` or say any group. Nothing happens.

## Steps to Reproduce

1. Click on `Add Clients` button on : https://demo.mifos.community/#/groups/4

## Expected Behaviour

1. Able to add client.

## Actual Behaviour

1. seems like a no-op.

## Settings
- Mifos X version: https://demo.mifos.community/
- Browser used: Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

https://user-images.githubusercontent.com/4143778/210726932-09271806-def6-4d37-a0ff-880d9b3b1362.mov

cc @edcable.

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

**Comment by msaini0r** [comment]
I would like to work on this issue. @tapaswenipathak

**Comment by Yash2024** [comment]
Hi, 
I want to work on this issue, can you please assign me this issue @tapaswenipathak .

**Comment by josehernandezfintecheandomx** [comment]
It's fixed in the PR https://github.com/openMF/web-app/pull/1647

@bharathcgowda please close it

**Comment by bharathcgowda** [comment]
Thanks @josehernandezfintecheandomx
