### ISSUE TITLE
Unable to Edit an existing loan product

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1638]
## Description
Unable to Edit an existing loan product

## Steps to Reproduce
1. create a loan product with any configuration
2. edit the product and save the loan product
Edit is showing the error msg "invalid parameter was passed"

## Expected Behaviour
User should be able to edit, modify and save the existing loan product

## Settings
- Mifos X version: 
- Browser used: 

## Screenshots, if any
<img width="1440" alt="Screenshot 2023-01-10 at 7 15 31 PM" src="https://user-images.githubusercontent.com/65952533/211568467-67c97b91-a11e-4090-88d0-d54036fa8d97.png">

**Comment by ramvr1256** [comment]
@bharathcgowda I am able to edit loan product. Is there any special use case where it is giving error. Or we can have a short meet to show this error and rectify this.

**Comment by bharathcgowda** [comment]
@ramvr1256 can you try in this instance
https://webapp.ps.mifos.io (mifos/password)

You could replicate the same product as well as we are able to reproduce in that instance

**Comment by zzzwhythis** [comment]
> 

@bharathcgowda can we check which mifos version is working in backend for this webapp?
