### ISSUE TITLE
Floating rate configuration issue

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1639]
## Description
Not able to configure the floating rate product in the admin->products->floating rates

## Steps to Reproduce
1. go to admin->products->floating rates
create a floating-rate product

## Expected Behaviour
user should be able to create and define the floating rate product

## Screenshots, if any
<img width="1440" alt="Screenshot 2023-01-10 at 9 48 06 PM" src="https://user-images.githubusercontent.com/65952533/211605317-cb0c07a8-9a5b-4e0e-adb2-e4607e08d2b7.png">

**Comment by ramvr1256** [comment]
`{
    "developerMessage": "The request was invalid. This typically will happen due to validation errors which are provided.",
    "httpStatusCode": "400",
    "defaultUserMessage": "Validation errors exist.",
    "userMessageGlobalisationCode": "validation.msg.validation.errors.exist",
    "errors": [
        {
            "developerMessage": "The parameter `fromDate` must be greater than the provided date2023-04-20",
            "defaultUserMessage": "The parameter `fromDate` must be greater than the provided date2023-04-20",
            "userMessageGlobalisationCode": "validation.msg.floatingrate.fromDate.is.less.than.date",
            "parameterName": "fromDate",
            "value": null,
            "args": [
                {
                    "value": "2023-01-21"
                },
                {
                    "value": "2023-04-20"
                }
            ]
        }
    ]
}`

@bharathcgowda This error is coming .... In simple words Backend is throwing error if fromDate is less than 20 April 2023, and if we are putting date is greater then this value then product is getting created.... Mostly this seems a backend error. But need to understand more on this why 20April 2023 is coming.

**Comment by bharathcgowda** [comment]
@ramvr1256  thank you for analyzing the issue.
Backed is not allowing to create the floating rate product before the current date+1. 
Basically, we can define the floating rate interest only after the current date, which sounds right to me. however, the error msg doesn't mention that. can we correct the error msg as a part of this ticket?
