### ISSUE TITLE
Apache Superset Support for Dashboards and Insights

### ISSUE THREAD

**Issue by IOhacker** [openMF/web-app#1649]
**Is your feature request related to a problem? Please describe.**
Apache Superset is a great visualization tools which has a easy setup and an active commmunity so then the request is to support it for creating Dashboards and Insights using the Data generated by Apache Fineract. It will help to display information for decisioning about loans, savings, users (demographic data) and non functional actions done in Apache fineract (i.e. audit trail logging). 

**Describe the solution you'd like**
Using the Embedded SDK will help to acomplish this feature request https://www.npmjs.com/package/@superset-ui/embedded-sdk

**Describe alternatives you've considered**
Pentaho CDE
Redash

**Additional context**
NA

**Comment by edcable** [comment]
Re-opening issue as @PC-11-00 is taking up work on this as part of 2023 Google Summer of Code

**Comment by adamsaghy** [comment]
@edcable @IOhacker I have seen this PR: https://github.com/openMF/web-app/pull/1849, but i am having concerns whether it is a good idea.

The implementation here was all the authentication details to be stored at UI side which is serious security concern...

In the other hand are we really sure the web-app should support 2 pretty separate app:
- fineract-backend
- apache superset backend?
