### ISSUE TITLE
overflow happing on landing page

### ISSUE THREAD

**Issue by mohdhaider07** [openMF/web-app#1651]
## Description
overflow happing on landing page due to image ,I guess

## Steps to Reproduce
1. Goto Home page
2. re-arrange the width to small screen 

## Expected Behaviour
overflow had to be hidden

## Actual Behaviour
Due to overflow Home screen is looking like this
https://user-images.githubusercontent.com/86488954/213880507-e7d67f4b-e8e5-4b84-90cd-98e4ce80743d.mp4

## Screenshots, if any

![footer](https://user-images.githubusercontent.com/86488954/213880571-ec4990a9-a792-4d7d-9dd0-914cb3f0a510.png)

**Comment by mohdhaider07** [comment]
@bharathcgowda  I am new to this Organisation I found this issue in frontend can you please assign this to me

**Comment by mohdhaider07** [comment]
I would like to discuss some ideas with you, but it seems that the platform we are currently using, Gitter, is inactive. Can you please suggest an alternative platform ?

**Comment by bharathcgowda** [comment]
@mohdhaider07  thank you for creating the issue and your willingness to contribute. 
I have assigned the ticket under your name.
Also, you can join the slack channel of web-app for communications, Mifos community actively uses slack so you should be able to post and discuss your ideas over there

https://join.slack.com/share/enQtNDY3NTU3ODE5NzA5NC02ZTAzM2IyOWJlMmRlMTljMTg3ZjA3MDhiMzFhNjllZjE0YjY5ZTU3MTI4ZDkzMTc3YWFiMDgwYTcxZTBmZWFi

**Comment by mohdhaider07** [comment]
> @mohdhaider07 thank you for creating the issue and your willingness to contribute. I have assigned the ticket under your name. Also, you can join the slack channel of web-app for communications, Mifos community actively uses slack so you should be able to post and discuss your ideas over there
> 
> https://join.slack.com/share/enQtNDY3NTU3ODE5NzA5NC02ZTAzM2IyOWJlMmRlMTljMTg3ZjA3MDhiMzFhNjllZjE0YjY5ZTU3MTI4ZDkzMTc3YWFiMDgwYTcxZTBmZWFi

Thank you sir

**Comment by mohdhaider07** [comment]
> @mohdhaider07 thank you for creating the issue and your willingness to contribute. I have assigned the ticket under your name. Also, you can join the slack channel of web-app for communications, Mifos community actively uses slack so you should be able to post and discuss your ideas over there
> 
> https://join.slack.com/share/enQtNDY3NTU3ODE5NzA5NC02ZTAzM2IyOWJlMmRlMTljMTg3ZjA3MDhiMzFhNjllZjE0YjY5ZTU3MTI4ZDkzMTc3YWFiMDgwYTcxZTBmZWFi

I have joined the workspace, please add me to a channel.
