### ISSUE TITLE
Dropdown not working in Create Client Form

### ISSUE THREAD

**Issue by PC-11-00** [openMF/web-app#1652]
## Description
When we try to create client , then we can't able to fill the create client form, because dropdown button is not working in staff , gender section.
## Steps to Reproduce
- Open the website(https://demo.mifos.community/#)
- Log in 
- Then open this link: https://demo.mifos.community/#/clients  
- Then click on Create Client option
- Then the form will come
- Try to fill staff and Gender section.
## Expected Behaviour
- Dropdown buttons should work and options should be visible ,so that we can select them to fill the form.
## Actual Behaviour
- Dropdown button is not working because options are not visible.
## Settings
- Mifos X version: 0.0.0 (https://demo.mifos.community)
- Browser used: Google Chrome (in MAC OS)

## Screenshots, if any

https://user-images.githubusercontent.com/76156941/213882707-e1c32095-e6b1-43bd-a9c4-da50c46708fd.mov

**Comment by SantoshNayak** [comment]
I can't see any signup link on the login page.
Can you please guide me to create an account so that I can look into this issue?

**Comment by PC-11-00** [comment]
You can just directly login using username and password as mifos and password ,respectively.

**Comment by SantoshNayak** [comment]
I checked the code and the issue.
The create client code is fine, it's just the API being used in this deployed version (https://demo.mifos.community/fineract-provider/api/v1/clients/template) doesn't provide the data for those drop-downs, while the other API (https://demo.mifos.io/fineract-provider/api/v1/clients/template) provides all the required data.


Here's the explanation - https://youtu.be/Cms5JY4rSRk

**Comment by PC-11-00** [comment]
I also knew that data is not fetched from the API ,then how are you going to resolve this issue

**Comment by Subzer0570** [comment]
@SantoshNayak Are you working on this issue?
If @SantoshNayak  is not, @PC-11-00 Can I work on this one
If there isn't data from which I can populate, I'll make one(But I need to dig that deeper yet)

**Comment by PC-11-00** [comment]
@Subzer0570 yeah sure , you can work.

**Comment by Subzer0570** [comment]
![image](https://user-images.githubusercontent.com/110231985/216774113-7f2a8aef-0b64-4ee2-872f-31b0a8c365de.png)
Can somebody suggest a solution for this?
@PC-11-00 @SantoshNayak

**Comment by PC-11-00** [comment]
It was my misunderstanding, after digging up the issue further I found out that these attributes are needed to be pre-configured from the admin panel.
