### ISSUE TITLE
Add Tooltips throughout Web App that didn't get re-implemented from Community App. 

### ISSUE THREAD

**Issue by edcable** [openMF/web-app#1654]
**Is your feature request related to a problem? Please describe.**
During the transition from the deprecated Community App to the new Web App on Angular, many of the tooltips that provided a valuable aid to understanding functionality of the system didn't get implemented in a majority of the screens.

**Describe the solution you'd like**
Ideally we can achieve a similar level of coverage (or an even higher presence of tooltips throughout the web app). 

For example, during Fixed Deposit Product creation:

### Old Community App

<img width="1198" alt="Screenshot 2023-01-23 at 11 52 17 AM" src="https://user-images.githubusercontent.com/823454/214136451-b3287cd3-a4b7-4af8-9c8e-b4398969850a.png">

### New Web App

<img width="631" alt="Screenshot 2023-01-23 at 11 53 27 AM" src="https://user-images.githubusercontent.com/823454/214136413-4376519b-987f-46e1-90a0-b619f226792a.png">

**Additional context**
Additional sub-issues will be created here to list out specific areas where tooltips should be implemented.

**Comment by adolfobcruz** [comment]
Hi! 
Is this still open? I think that I can help. :)

**Comment by Subzer0570** [comment]
I would like to work on this issue @edcable 
Also, I would need a brief guidance in order to get started to work on this issue
If you can provide steps/ guide  to work on this, it would be very much appreciated.
Waiting for your reply

**Comment by edcable** [comment]
@adolfobcruz and @Subzer0570 Yes this is still available to work on. I'll create some quick tickets for areas where the tooltips are missing. You can also compare https://demo.mifos.io vs https://demo.mifos.community as well to find where the tooltips aren't present in the new UI.

@Subzer0570 regarding guidance on how to contribute, please follow the steps in the readme for opening up a pull request. Regarding the actual implementation itself @ramvr1256 @abhaychawla or @mbj36 are you able to provide some guidance?

**Comment by Subzer0570** [comment]
Yes, I looked at new tickets you just created.
I'll pick one to get started
@ramvr1256 @abhaychawla @mbj36 your guidance to where and what to do in code would be really help a lot
I believe I need to do changes in web-app, right? @edcable

**Comment by mbj36** [comment]
Yes @Subzer0570 you need to do changes in web-app, Ed has already created a screen wise issue, Please pick up as you like

**Comment by Subzer0570** [comment]
![image](https://user-images.githubusercontent.com/110231985/216774171-60c84581-8d4b-4354-a678-8a1f4de65826.png)
Can somebody please help me to resolve this?
@edcable @mbj36 @Nayan @ramvr1256 @abhaychawla

**Comment by mbj36** [comment]
@Subzer0570 Could you please remove node_modules and try to install dependencies again ?
