### ISSUE TITLE
Actions in Loan Accounts not working

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1660]
## Description

Go to https://demo.mifos.community/#/clients/38/general and click on any action in Loan Accounts tab/heading/layout

- Approve
- Make Repayment

<img width="1439" alt="Screenshot 2023-01-29 at 4 02 36 PM" src="https://user-images.githubusercontent.com/4143778/215320522-0d64a178-21f5-4f57-98a7-e5d2c00687d9.png">

## Steps to Reproduce

1. Use https://demo.mifos.community/#/clients/38/general.
2. Go to `Loan Accounts`.
3. Click on any action.

## Expected Behaviour

Able to approve or make repayment as per `Actions`.

## Actual Behaviour

Seems like a no-op, nothing happens.

Console error code:

`ERROR Error: Uncaught (in promise): ChunkLoadError: Loading chunk 592 failed.`

## Settings
- Mifos X version: https://demo.mifos.community/
- Browser used: Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

https://user-images.githubusercontent.com/4143778/215320653-5a22bf56-0e79-4f57-9e45-7a28a86e986c.mov

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

cc @edcable.

**Comment by PC-11-00** [comment]
@tapaswenipathak it's working.

https://user-images.githubusercontent.com/76156941/220267219-fdecbf04-d06f-4be1-bb07-4a9a33808bdb.mov


https://user-images.githubusercontent.com/76156941/220267254-a1b23b1f-4000-4cb7-a68b-e420d26e99fa.mov

**Comment by PC-11-00** [comment]
@tapaswenipathak @bharathcgowda we can close this issue also.
