### ISSUE TITLE
Loans navigation doesn't work from Client profile

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1661]
## Description

1. Open https://demo.mifos.community/#/clients/38/loans-accounts/4/actions/Make%20Repayment
2. Click on loans in categories in navigation.

404 error code.

## Steps to Reproduce

1. Open https://demo.mifos.community/#/clients/38/loans-accounts/4/actions/Make%20Repayment
2. Click on loans in categories in navigation.

## Expected Behaviour

Able to navigate to `Loans`.

## Actual Behaviour

404 error code.

## Settings
- Mifos X version: https://demo.mifos.community/
- Browser used: Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

https://user-images.githubusercontent.com/4143778/215321187-3e538175-9115-4856-b9b2-e89fdec13f9e.mov

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

cc @edcable.

**Comment by niwogabajoel** [comment]
@tapaswenipathak let me perform more tests and fixes for this issue.
