### ISSUE TITLE
Feature doesn't work: Not able to create Savings Product 

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1664]
## Description

Create Savings product as per https://github.com/openMF/web-app/issues/1567#issuecomment-1316597425. Every field errors. Not able to create Savings Product.

## Steps to Reproduce

1. Open https://sandbox.mifos.community/#/products/saving-products/create.
2. First it doesn't load, nothing appears, only a bunch of errors on console.
3. After a while it loads and click on `Next` errors.

## Expected Behaviour

Able to create savings product.

## Actual Behaviour

Bunch of errors.

## Settings
- Mifos X version: https://demo.mifos.community/
- Browser used: Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

https://user-images.githubusercontent.com/4143778/215323006-7cfb143d-072e-4ff1-b751-b63af61584cf.mov

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

cc @edcable.

**Comment by PC-11-00** [comment]
@tapaswenipathak @bharathcgowda now we can create the saving product, there was some problem with the routing of the saving product in product-roting.module.ts, I also figured out the problem(there was no savingProductTemplate), but now these changes are now merged by @josehernandezfintecheandomx today.
Now we can close this issue.

**Comment by bharathcgowda** [comment]
Thank you for the fix @PC-11-00
