### ISSUE TITLE
Not able to Create Savings Account: Savings Product not working while creating client

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1665]
Ref https://github.com/openMF/web-app/issues/1567#issuecomment-1316597425.

Doesn't work.

cc @edcable.

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264.

https://user-images.githubusercontent.com/4143778/215323570-20dd1c3b-248a-43da-8fb3-2f193e05f8f6.mov

**Comment by PC-11-00** [comment]
Now we can create.

https://user-images.githubusercontent.com/76156941/220900913-a1d0e115-e786-445f-9e98-fd85a363b599.mov
