### ISSUE TITLE
Feature not working: Add Family Member in Create Client

### ISSUE THREAD

**Issue by tapaswenipathak** [openMF/web-app#1666]
## Description

Open https://demo.mifos.community/#/clients/create, add family member, `confirm` is disabled. `Age` errors on console.

<img width="1434" alt="Screenshot 2023-01-29 at 5 48 00 PM" src="https://user-images.githubusercontent.com/4143778/215325612-eee4ae2e-923d-443c-8ccc-524eab257cee.png">

## Steps to Reproduce

1. Create client using https://demo.mifos.community/#/clients/create
2. Add family member. 
3. Add age
4. `Confirm` button disabled.

## Expected Behaviour

Able to add family member.

## Actual Behaviour

Errors.

## Settings
- Mifos X version: https://demo.mifos.community/
- Browser used: Version 107.0.5304.110 (Official Build) (x86_64)

## Screenshots, if any

https://user-images.githubusercontent.com/4143778/215325480-daf01405-7ab7-448e-a084-6a7f2009dd1e.mov

Ref https://github.com/openMF/mifos-documentation/issues/14#issuecomment-1309069264

cc @edcable.

**Comment by sg1301** [comment]
Hi I wanted to work on this issue but while previewing the app on my local system I am getting the following error. Can you tell what is it about...
![out_of_memory_error](https://user-images.githubusercontent.com/88100978/216661075-75156a1c-e9d4-4b0d-a3b7-0eb97f80244c.png)
