### ISSUE TITLE
Add Tooltips to Create Savings Account screens

### ISSUE THREAD

**Issue by edcable** [openMF/web-app#1676]

**Comment by Subzer0570** [comment]
Hello @edcable 
I can start from here
(ref - https://github.com/openMF/web-app/issues/1654)

**Comment by Subzer0570** [comment]
Hello @edcable, how can I create a savings account?
I have local server running and I learnt about the chart of accounts
But didnt see any options to savings account.

**Comment by Subzer0570** [comment]
![image](https://user-images.githubusercontent.com/110231985/220178328-be0bc877-105b-4d19-9d31-9aab0abb1866.png)

I am creating saving product first, but its not moving to next section

**Comment by Subzer0570** [comment]
hello @edcable 
Can you please guide me?
