### ISSUE TITLE
Entity Data table checks: Create entity data table

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#169]
Goal:
As a system admin, I must be able to create new entity data table for client, loan etc, as seent at,
![createen](https://user-images.githubusercontent.com/23022667/43183667-90a37452-9003-11e8-9860-525015b19d5d.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/174882832/Entity+Data+Table+Checks
https://demo.openmf.org/api-docs/apiLive.htm#entitydatatablechecks_create

**Comment by pearlMat** [comment]
I would like to work on this issue please..

**Comment by abhaychawla** [comment]
Go ahead @pearlMat
