### ISSUE TITLE
Transfer funds option not working in savings account

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1699]
## Description
Transfer funds button not working in the savings account, it is giving 404 error message.

## Steps to Reproduce
1. go to any active savings account 
2. click more and click "tranfer funds" button (see attached screenshot)
3. system shows 404 error page
to reproduce you can use 
URL: https://demo.mifos.community/#/clients/38/savings-accounts/11/
CRED: mifos/password

## Expected Behaviour
The application should show the transfer funds screen to do the funds transfer(see attached screenshot from community-app)
To check the existing behaviour, you can check this instance
URL: https://default.ps.mifos.io/#/viewsavingaccount/1
CRED: mifos/password

## Screenshots, if 

![404 error](https://user-images.githubusercontent.com/65952533/223945774-550011e6-43b9-4f9d-a8a4-a75dfdfddc79.png)
![transfer funds](https://user-images.githubusercontent.com/65952533/223945782-d2e3e50d-36d7-46a4-97b4-555d68d099a6.png)
![expected screen](https://user-images.githubusercontent.com/65952533/223945785-2e06f56c-0e4c-4ad3-bec4-8770e6b76b81.png)

**Comment by bharathcgowda** [comment]
@PC-11-00  will you be able to have a look into this issue?

**Comment by PC-11-00** [comment]
okay , I wil look into it.

**Comment by PC-11-00** [comment]
@bharathcgowda it has already been resolved. It will get update soon on the site(https://demo.mifos.community/#/clients/38/savings-accounts/11/).

https://user-images.githubusercontent.com/76156941/223978324-6ec2c9bc-9533-4ffc-a5a1-ed7062d36a67.mov

**Comment by bharathcgowda** [comment]
thank you for looking into this @PC-11-00  I'll check the feature once the instance is updated. appreciate your help.
