### ISSUE TITLE
Manage Datatables: list

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#170]
Goal: 
As a system admin, I want to view all existing data tables as seen at,
https://demo.openmf.org/#/datatables

![manage datatables](https://user-images.githubusercontent.com/23022667/43183981-a424776e-9004-11e8-8435-aaa281967cb5.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/52592760/Manage+Data+Tables
https://demo.openmf.org/api-docs/apiLive.htm#datatables

**Comment by cabrelkemfang** [comment]
@abhaychawla I will like to work on this issue.

**Comment by abhaychawla** [comment]
@cabrelkemfang Please do not work on issues reserved for gci 2018 students.
