### ISSUE TITLE
Getting issue while installing web-app locally

### ISSUE THREAD

**Issue by ishqDehlvi** [openMF/web-app#1702]
Whenever I am using `ng serve ` command getting below error:

ERROR:
Warning: 'outputHashing' option is disabled when using the dev-server.
****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
⠸ Generating browser application bundles (phase: sealing)...
<--- Last few GCs --->

[9291:0x140008000]    57292 ms: Mark-Compact 1972.3 (2081.7) -> 1970.2 (2084.7) MB, 484.5 / 0.0 ms  (average mu = 0.876, current mu = 0.939) allocation failure; scavenge might not succeed
[9291:0x140008000]    58163 ms: Mark-Compact 1980.6 (2088.3) -> 1972.4 (2096.2) MB, 794.6 / 0.0 ms  (average mu = 0.763, current mu = 0.087) task; scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1044b8c64 node::Abort() [/opt/homebrew/Cellar/node/19.7.0/bin/node]
 2: 0x1044b9f30 node::ModifyCodeGenerationFromStrings(v8::Local<v8::Context>, v8::Local<v8::Value>, bool) [/opt/homebrew/Cellar/node/19.7.0/bin/node]
 3: 0x1046148b0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/opt/homebrew/Cellar/node/19.7.0/bin/node]
 4: 0x10461485c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/opt/homebrew/Cellar/node/19.7.0/bin/node]
 5: 0x1047afb34 v8::internal::Heap::GarbageCollectionReasonToString(v8::internal::GarbageCollectionReason) [/opt/homebrew/Cellar/node/19.7.0/bin/node]
 6: 0x1047aeb9c v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/opt/homebrew/Cellar/node/19.7.0/bin/node]
 7: 0x104817488 v8::internal::ScavengeJob::Task::RunInternal() [/opt/homebrew/Cellar/node/19.7.0/bin/node]
 8: 0x10451d2b4 node::PerIsolatePlatformData::RunForegroundTask(std::__1::unique_ptr<v8::Task, std::__1::default_delete<v8::Task> >) [/opt/homebrew/Cellar/node/19.7.0/bin/node]
 9: 0x10451cf78 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/opt/homebrew/Cellar/node/19.7.0/bin/node]
10: 0x106ea63c4 uv__async_io [/opt/homebrew/Cellar/libuv/1.44.2/lib/libuv.1.dylib]
11: 0x106eb61e0 uv__io_poll [/opt/homebrew/Cellar/libuv/1.44.2/lib/libuv.1.dylib]
12: 0x106ea67bc uv_run [/opt/homebrew/Cellar/libuv/1.44.2/lib/libuv.1.dylib]
13: 0x1043f18b8 node::SpinEventLoopInternal(node::Environment*) [/opt/homebrew/Cellar/node/19.7.0/bin/node]
14: 0x1044fb044 node::NodeMainInstance::Run(node::ExitCode*, node::Environment*) [/opt/homebrew/Cellar/node/19.7.0/bin/node]
15: 0x1044fadc4 node::NodeMainInstance::Run() [/opt/homebrew/Cellar/node/19.7.0/bin/node]
16: 0x1044802a8 node::LoadSnapshotDataAndRun(node::SnapshotData const**, node::InitializationResultImpl const*) [/opt/homebrew/Cellar/node/19.7.0/bin/node]
17: 0x10448042c node::Start(int, char**) [/opt/homebrew/Cellar/node/19.7.0/bin/node]
18: 0x1ac1efe50 start [/usr/lib/dyld]
zsh: abort      ng serve

**Comment by PC-11-00** [comment]
Run this command : export NODE_OPTIONS="--max-old-space-size=8192" 
, in your terminal and you will be able to run the web app locally.
