### ISSUE TITLE
Manage Datatables: Create/View/Delete/Edit Datatable

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#171]
Goal:
As a system admin, I want to define a template for a specific data table, applying  to a specific entity; client, loan etc. as seen at:

https://demo.openmf.org/#/createdatatable
![createdatable](https://user-images.githubusercontent.com/23022667/43184142-37b8638c-9005-11e8-8559-d43b558028b5.png)
https://demo.openmf.org/#/viewdatatable/A1
![1](https://user-images.githubusercontent.com/16948598/53683799-08adb280-3d2b-11e9-93ff-cd7064bdd04d.PNG)
![3](https://user-images.githubusercontent.com/16948598/53683801-0b100c80-3d2b-11e9-9c16-1f1dedd2ef3b.PNG)
https://demo.openmf.org/#/editdatatable/A1
![2](https://user-images.githubusercontent.com/16948598/53683805-119e8400-3d2b-11e9-948c-a0c2ec47ff94.PNG)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/52592760/Manage+Data+Tables
https://demo.openmf.org/api-docs/apiLive.htm

**Comment by luckyman20** [comment]
I am working on this.
