### ISSUE TITLE
DataTables - incorrect records shown

### ISSUE THREAD

**Issue by peter-santa-dpc** [openMF/web-app#1721]
## Description
Incorrect records are shown on data table view - records from a different data table.

## Steps to Reproduce

1. Have at least 2 data tables defined for Savings account.
2. Insert record into one of them, leave the other empty.
3. Open the savings account used for the test, navigate to the data table, that have records. The records will be shown correctly.
4. Navigate to the empty data table. It will show most of the columns and most of the data from the other data table.

The server side sends the data correctly on the API.

## Expected Behaviour
A view for a data table shows the records that are inserted into that one.

## Actual Behaviour
A view of data table shows records from another data table.

## Settings
- Mifos X version: 814bb87c
- Browser used: Firefox 111.0.1 (64-bit)

## Screenshots, if any

https://user-images.githubusercontent.com/45198877/228502030-826acc9b-78ba-4a90-a925-2979ecc7d116.mp4

**Comment by PC-11-00** [comment]
@bharathcgowda i think it is already resolved https://github.com/openMF/web-app/pull/1764

**Comment by bharathcgowda** [comment]
@PC-11-00 Ok thank you for checking this out.
