### ISSUE TITLE
Edit Charge - Tax group is mandatory by backend, but cannot be set on UI

### ISSUE THREAD

**Issue by peter-santa-dpc** [openMF/web-app#1722]
## Description
There is a charge, created without tax group. It was allowed.

## Steps to Reproduce
1. Edit charge, that does not have Tax Group. - Adding Tax Group is not possible, the dropdown is greyed out.
2. Save modified charge.

## Expected Behaviour
The Charge should be saved - but backend validation does not let -> On UI it should be allowed to modify tax group:
1. Should be able to select tax group (if exists)
2. If tax group is not selected, the UI shall not send empty string in the request: `taxGroupId: ""` which is invalid

## Actual Behaviour
Tax Group cannot be selected, the dropdown is greyed out.

## Settings
- commit hash: 814bb87c
- Browser used: Firefox 111.0.1 (64-bit)

## Screenshots, if any
![image](https://user-images.githubusercontent.com/45198877/228254983-821b9ae2-272b-40c7-893f-c18daa87eb09.png)

https://user-images.githubusercontent.com/45198877/228495131-dce145fc-5682-4916-87d5-a2fc57d8b05d.mov

**Comment by PC-11-00** [comment]
working on it
