### ISSUE TITLE
Data Table for Savings Account related Transactions

### ISSUE THREAD

**Issue by peter-santa-dpc** [openMF/web-app#1726]
### Goal
When https://issues.apache.org/jira/browse/FINERACT-1911 and related issues (listed below) will have been implemented, Data Table assignment will be possible to Transaction entities of Savings Accounts. It will be necessary for the UI to support showing and editing them.

### Solution Concept
On the /clients/{clientId}/savings-accounts/{accountId}/transactions/{transactionId} view there should be a possibility to show data tables assigned to transactions, and their content. Create, Update, Delete features should be supported on a similar way as it is supported for other data tables, e.g. assigned to savings accounts.

## Important notes
Consider the results of all the following issues, because they affected the related API:
- https://issues.apache.org/jira/browse/FINERACT-1917
- https://issues.apache.org/jira/browse/FINERACT-1912
- https://issues.apache.org/jira/browse/FINERACT-1911
- https://issues.apache.org/jira/browse/FINERACT-1910
- https://issues.apache.org/jira/browse/FINERACT-1943
- https://issues.apache.org/jira/browse/FINERACT-1915
- https://issues.apache.org/jira/browse/FINERACT-1916

Consider the up-to-date swagger also.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/45198877/228557539-6107bd0c-5765-467b-898b-9419f6bf6fa1.png)

**Comment by PC-11-00** [comment]
@peter-santa-dpc can you please tell exactly what’s the requirement on this page.
![Uploading Screenshot 2023-08-08 at 4.52.32 PM.png…]()

**Comment by PC-11-00** [comment]
@peter-santa-dpc  can you please tell exactly what’s the requirement on this page.
![Screenshot 2023-08-08 at 4 52 32 PM](https://github.com/openMF/web-app/assets/76156941/1631dce6-3e39-4bf9-8952-a6c57c33e11b)

**Comment by peter-santa-dpc** [comment]
Please consider the screenshot in the description.

**Comment by PC-11-00** [comment]
Hi @peter-santa-dpc 
I completed the datatable for saving transaction please check
I will make PR after your confirmation

https://github.com/openMF/web-app/assets/76156941/2a0e65e3-59c0-46e0-8eb2-01188a787c47
