### ISSUE TITLE
Data Table for Transactions in general

### ISSUE THREAD

**Issue by peter-santa-dpc** [openMF/web-app#1727]
### Goal
When https://issues.apache.org/jira/browse/FINERACT-1970 and related issues (listed below) will have been implemented, Data Table assignment will be possible to Transaction entities. It will be necessary for the UI to support showing and editing them.

Please consider, that the mentioned FINERACT story covers requirements for Savings Account related transactions, but if the solution of that development results a general solution for all the transactions (Loan, Share, etc.), then the UI needs to be aligned. The Savings account related UI part is covered by https://github.com/openMF/web-app/issues/1726, this ticket is for the rest.

### Solution Concept
On the transaction details views there should be a possibility to show data tables assigned to transactions, and their content. Create, Update, Delete features should be supported on a similar way as it is supported for other data tables, e.g. assigned to savings accounts.

## Important notes
Consider the results of all the following issues, because they affected the related API:
- https://issues.apache.org/jira/browse/FINERACT-1917
- https://issues.apache.org/jira/browse/FINERACT-1912
- https://issues.apache.org/jira/browse/FINERACT-1911
- https://issues.apache.org/jira/browse/FINERACT-1910
- https://issues.apache.org/jira/browse/FINERACT-1943
- https://issues.apache.org/jira/browse/FINERACT-1915
- https://issues.apache.org/jira/browse/FINERACT-1916

Consider the up-to-date swagger also.

**Comment by galovics** [comment]
Not stale.

**Comment by PC-11-00** [comment]
@galovics @peter-santa-dpc @bharathcgowda is the backend ready for this issue? 
if yes , can you tell me the point of contact who made the backend for this issue and if possible can you tell me the name of the entity types which it will effect, like in issue #1726 ,the entity type was "m_savings_account_transaction" and point of contact was Martha jankovics.

**Comment by PC-11-00** [comment]
As discussed with @peter-santa-dpc 
Peter said:
The general solution is on the backlog for the backend, with very low prio. https://issues.apache.org/jira/browse/FINERACT-1970
I think, the UI change can be skipped also for now, and get back later, when someone needs it
