### ISSUE TITLE
enable_business_date issue

### ISSUE THREAD

**Issue by hghost50** [openMF/web-app#1740]
Hello everyone,
I find it difficult to get rid of this issue in browser. Kindly review
Am using ubuntu 18, with a node version v16.15.1 and npm 8.11.0

**Comment by PC-11-00** [comment]
Can you describe more about the issue?

**Comment by hghost50** [comment]
When i start the ng serve on my terminal, it redirects me to the http://localhost:4200, after inserting my credentials to the login page, it shows on notifications unknow error, and when i inspect the browser, this is what the error displays: enable_business_date_issue

**Comment by PC-11-00** [comment]
On which server are you trying to log in?

**Comment by hghost50** [comment]
Am login on my localhost:4200, had already my mifos x server running on https://localhost:8443

**Comment by PC-11-00** [comment]
Follow the steps:
- Start the webapp using(ng serve) and then go to localhost:4200
- Start fineract server using(./gradlew bootRun) 
- Select the server from the dropdown in localhost:4200
<img width="540" alt="Screenshot 2023-04-24 at 12 18 37 PM" src="https://user-images.githubusercontent.com/76156941/233920190-0b8537fe-f587-4f63-9d01-fd4a7d152a88.png">
- open a new tab and go to this link `https://localhost:8443/` , remember to use https only
- then again try to log in 

https://user-images.githubusercontent.com/76156941/233920566-d0af24df-d86f-4601-bb56-ac999449995d.mov

**Comment by hghost50** [comment]
Ok, really appreciate, i will try that
