### ISSUE TITLE
Unable to create a savings account when "balance required for interest calculation" is added

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1754]
## Description
Unable to create a savings account when "balance required for interest calculation is added

## Steps to Reproduce
1. create a simple savings product with the balance required for interest calculation" field 
2. create a savings account with the savings product
## Expected Behaviour
should be able to create a savings account with the balance required for interest calculation" field provided
## Actual Behaviour
it is now showing the error message "The parameter minBalanceForInterestCalculation is not supported."

you can check the instance to reproduce
https://webapp.ps.mifos.io/ (mifos/password
use the savings product 'CEUR' to create a saving account 
## Screenshots, if any
![image](https://github.com/openMF/web-app/assets/65952533/fec6db0a-50b7-4ccb-8196-51428455f38d)

**Comment by bharathcgowda** [comment]
Hi @PC-11-00  could you please help in looking into this issue??
CC @edcable

**Comment by PC-11-00** [comment]
@bharathcgowda In this issue when min balance required for interest calculation is added, then when we send the post request to the server side, then it's giving error . I checked the backend API, and there is no key minBalanceForInterestCalculation to accept the value, therefore it's giving an error, either I can delete the minBalanceForInterestCalculation from the terms form, then it will not give an error, or the backend team needs to change the API.

**Comment by bharathcgowda** [comment]
@PC-11-00 could you please check how it is working here https://default.ps.mifos.io/ (mifos/password)
This is basically the old UI this might help you figure out how we can fix this

**Comment by bharathcgowda** [comment]
Ok, let's follow the same for webapp as well then. @PC-11-00  thank you for verifying on the same.
