### ISSUE TITLE
Adding module on toolbar

### ISSUE THREAD

**Issue by FRANCIS-KHUSH** [openMF/web-app#1765]
## Description
I cannot seem to see Accounting module on this mifos

## Steps to Reproduce
This mifos version when I log-in their is no accounting module on the toolbar, but  I can see "Chart of accounts" . How can I enable the module on the toolbar

## Actual Behaviour
![image](https://github.com/openMF/web-app/assets/65183442/8483afb6-3f42-4698-8991-b10c1a27ca58)

## Settings
Release version: v.23.53.11 | Mifos X Release Date:2023.05.11
- Browser used: 

## Screenshots, if any
![image](https://github.com/openMF/web-app/assets/65183442/20762141-7363-46f4-8543-1351fc0e7752)

**Comment by PC-11-00** [comment]
@FRANCIS-KHUSH which version are you using, this screenshot is of a community app(older client-side version of mifos) , this repo handles the issues of the latest client-side web app.
But in the community app also there is an accounting module in the header toolbar, may be you are using older version of community app. You can visit : https://demo.mifos.io/#/ for latest community app.
<img width="1464" alt="Screenshot 2023-06-11 at 3 35 10 AM" src="https://github.com/openMF/web-app/assets/76156941/fd859008-0df6-4a34-ba0d-dc05df5efc99">

**Comment by FRANCIS-KHUSH** [comment]
This is the version of Mifos I am using :- [Release Version: v.23.05.11 | Mifos X Release Date: 2023.05.11](https://mifosforge.jira.com/browse/MIFOSX/component/11710/?selectedTab=com.atlassian.jira.jira-projects-plugin:component-changelog-panel)
