### ISSUE TITLE
Configurations

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#178]
Goal: 
Configurations(or Global configurations) are the flags , used to enable  or disable certain feature in Mifos. 
https://demo.openmf.org/#/global
![configurations](https://user-images.githubusercontent.com/23022667/43185876-c5d918e6-900a-11e8-948d-0acaef473176.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67895362/Global+Configuration
https://demo.openmf.org/api-docs/apiLive.htm#configs_global

**Comment by luckyman20** [comment]
@abhaychawla I am working on this.

**Comment by abhaychawla** [comment]
Go ahead!
