### ISSUE TITLE
Client Search Returns Error

### ISSUE THREAD

**Issue by skemuel007** [openMF/web-app#1786]
## Description
When searching for a client via the search box in the body on the dashboard page, we got a toast message of 404.

## Steps to Reproduce

1. Visit https://corebanking2.test.vggdev.com/#/login
2. On the menu bar, click on "Institution", on the drop-down click on "Clients"

## Expected Behaviour
To search for a client and return results or not found

## Actual Behaviour
Shows a toast message of 404 not found

## Settings
- Mifos X version: 1.8.4
- Browser used: Chrome, Edge

## Screenshots, if any

![mifos_client_search_error](https://github.com/openMF/web-app/assets/11774340/0b77219b-6150-4a87-a060-b9d811b38bde)

**Comment by PC-11-00** [comment]
https://github.com/openMF/web-app/assets/76156941/ee402930-422a-42e3-9d81-39bc971f5e7c

Actually, in my local setup and remotely also it is working fine, I can't comment on the URL which you are using.

**Comment by bharathcgowda** [comment]
@PC-11-00 this issue exists on the release version of fineract.
We can to check the issue here
https://advancly-uat.mifos.community/#/clients
(mifos/password)

**Comment by PC-11-00** [comment]
<img width="1440" alt="Screenshot 2023-08-02 at 1 38 33 PM" src="https://github.com/openMF/web-app/assets/76156941/f77ffb7f-caf0-48b0-8428-736231d2dc18">
@bharathcgowda it's a 500 error ,means it's a backend problem.

**Comment by mismisgh** [comment]
@PC-11-00 I have the same issue also, can you share the api url? I see 404 on  https://51.132.133.200:8443/fineract-provider/api/v2/clients/search on my end

**Comment by mismisgh** [comment]
> @mismisgh on which API URL end are you hitting and please tell where are you using web-app ,are you using locally or remotely?

I am running it locally.

**Comment by PC-11-00** [comment]
> > @mismisgh on which API URL end are you hitting and please tell where are you using web-app ,are you using locally or remotely?
> 
> I am running it locally.

Which server are you using?

**Comment by mismisgh** [comment]
> > > @mismisgh on which API URL end are you hitting and please tell where are you using web-app ,are you using locally or remotely?
> > 
> > 
> > I am running it locally.
> 
> Which server are you using?

Tomcat 10 
Fineract 1.8.4

**Comment by PC-11-00** [comment]
> > > > @mismisgh on which API URL end are you hitting and please tell where are you using web-app ,are you using locally or remotely?
> > > 
> > > 
> > > I am running it locally.
> > 
> > 
> > Which server are you using?
> 
> Tomcat 10 Fineract 1.8.4

okay, actually there was a change in the backend with search client API , new version of Search API : fineract-provider/api/v2/clients/search and the end-point was also changed in the frontend so in your case: I have never used Tomcat so can't comment like is it updated or not, try to run finearact locally without using tomcat from here: https://github.com/apache/fineract or can you send some screenshot of the issue.

**Comment by mismisgh** [comment]
> > > > > @mismisgh on which API URL end are you hitting and please tell where are you using web-app ,are you using locally or remotely?
> > > > 
> > > > 
> > > > I am running it locally.
> > > 
> > > 
> > > Which server are you using?
> > 
> > 
> > Tomcat 10 Fineract 1.8.4
> 
> okay, actually there was a change in the backend with search client API , new version of Search API : fineract-provider/api/v2/clients/search and the end-point was also changed in the frontend so in your case: I have never used Tomcat so can't comment like is it updated or not, try to run finearact locally without using tomcat from here: https://github.com/apache/fineract or can you send some screenshot of the issue.

Thank you @PC-11-00 I got it working now.

**Comment by PC-11-00** [comment]
@bharathcgowda now we can close this issue.
