### ISSUE TITLE
Unable to view details an existing loan

### ISSUE THREAD

**Issue by skemuel007** [openMF/web-app#1789]
## Description
Clients with existing loans cannot view the details of their existing loan. There is an error thrown with the message "Unknown error. Please try again later".

## Steps to Reproduce

1. Visit Advancly's https://corebanking2.test.vggdev.com/
2. On the menu bar search for Client with account 000077011
3. On the Loans Account section click on the account with the number 000000578 to view its details and error **Unknown error. Please try again later"

## Expected Behaviour
View loan details

## Actual Behaviour
Throws an error while trying to view the loan details **Unknown error. Please try again later.**

## Settings
- Mifos X version: 1.8.4
- Browser used: Chrome, Edge

## Screenshots, if any
<img width="1397" alt="ExistingLoanDetailsError" src="https://github.com/openMF/web-app/assets/11774340/0051b1f5-12a8-4581-ac02-1ffb9be1b445">

**Comment by PC-11-00** [comment]
It's working fine, there can be problem in the link and deployment which he is using.

Uploading Screen Recording 2023-08-01 at 6.01.03 AM.mov…

**Comment by bharathcgowda** [comment]
@skemuel007  we are not able to reproduce the issue. 

I also tried on the new UAT instance with the release version created for advancly..we are not able to reproduce there as well
https://advancly-uat.mifos.community/#/clients/1/loans-accounts/1/general
