### ISSUE TITLE
Client unable to view loan repayment schedule during loan creation

### ISSUE THREAD

**Issue by skemuel007** [openMF/web-app#1790]
## Description
During loan creation, I was unable to view the loan repayment schedule details for the loan being created, the repayment schedule table is empty

## Steps to Reproduce

1. Visit Advancly's https://corebanking2.test.vggdev.com/
2. On the menu bar search for Client with account 000077011
3. Under the navigation link for Client, Home -> Client -> {{clientName}} -> General, in the client details section as show in supporting image below, kindly click on the Menu on the top right corner -> Click on **Applications** -> Select **New Loan Account**
4. Upon filling the details for tabs Loan **Details**, **Terms**, and **Charges**, on navigating to the **Repayment Schedule** tab, there are repayment schedule details displayed

## Expected Behaviour
Should be able to see loan repayment schedule details when trying to create a loan

## Actual Behaviour
No loan repayment schedule details was shown while trying to create a loan for a client

## Settings
- Mifos X version: 1.8.4
- Browser used: Edge, Chrome

## Screenshots, if any
![LoanRepaymentScheduleDetailsMissing](https://github.com/openMF/web-app/assets/11774340/507dc736-5481-40f5-b24f-280416f05564)

**Comment by bharathcgowda** [comment]
repayment schedule will not be loaded by default. you will have to click the "repayment info" button to generate the schedule.
