### ISSUE TITLE
Missing Principal Amount on Loan Creation Preview Summary

### ISSUE THREAD

**Issue by skemuel007** [openMF/web-app#1791]
## Description
Provide a brief overview of the enhancement or issue.

## Steps to Reproduce
1. Visit Advancly's https://corebanking2.test.vggdev.com/
2. On the menu bar search for Client with account 000077011
3. Under the navigation link for Client, Home -> Client -> {{clientName}} -> General, in the client details section as show in supporting image below, kindly click on the Menu on the top right corner -> Click on Applications -> Select New Loan Account
4. Upon fill the details for tabs **Loan Details, Terms, and Charges**, view the **Repayment Schedule** details on navigating to the Preview tabs, it was observed that the following item was not displayed, the **Principal Amount**

## Expected Behaviour
The loan creation **Preview** summary tab should display the **Principal Amount** along side other loan creation details

## Actual Behaviour
**Principal Amount** not displayed for Loan creation **Preview**

## Settings
- Mifos X version: 1.8.4
- Browser used: Edge, Chrome

## Screensh
![MissingPrincipalAmount](https://github.com/openMF/web-app/assets/11774340/9d9535c1-2cf6-4bce-aa5a-642b67189801)
ots, if any

**Comment by josehernandezfintecheandomx** [comment]
Solved! Thanks

**Comment by bharathcgowda** [comment]
fixed

**Comment by skemuel007** [comment]
Thanks @bharathcgowda and @josehernandezfintecheandomx for closing this out
