### ISSUE TITLE
Failure to perform loan creation for a client

### ISSUE THREAD

**Issue by skemuel007** [openMF/web-app#1792]
## Description
Loan creation for clients fails with error message **transactionProcessingStrategyId is mandatory**

## Steps to Reproduce

1. Visit Advancly's https://corebanking2.test.vggdev.com/
2. On the menu bar search for Client with account 000077011
3. Under the navigation link for Client, Home -> Client -> {{clientName}} -> General, in the client details section as show in supporting image below, kindly click on the Menu on the top right corner -> Click on Applications -> Select New Loan Account
4. Upon fill the details for tabs Loan Details, Terms, and Charges, view the Repayment Schedule details on navigating to the Preview tabs, an error was thrown while trying to submit the Loan for creation with the error message **transactionProcessingStrategyId is mandatory**

## Expected Behaviour
Should be able to create loan

## Actual Behaviour
Failure to create loan with error message **transactionProcessingStrategyId is mandatory**

## Settings
- Mifos X version: 1.8.4
- Browser used: Edge, Chrome

## Screenshots, if any
![LoanCreationFailure](https://github.com/openMF/web-app/assets/11774340/926e3392-533b-41d2-bed4-a1fa3cc33894)

**Comment by PC-11-00** [comment]
I am able to create a loan account, actually creating loan accounts depends on the loan products that you are using, and for a particular type of loan product, some fields are mandatory.

https://github.com/openMF/web-app/assets/76156941/54a073c5-5119-45d6-a669-71dfe55fdc2b

**Comment by bharathcgowda** [comment]
@skemuel007  Please share all the details you are filling in for creating this loan account where you are getting the error.
