### ISSUE TITLE
Creation of fixed deposit account does not debit the savings account

### ISSUE THREAD

**Issue by skemuel007** [openMF/web-app#1796]
## Description
Creation of fixed deposit account, does not debit savings account **

## Steps to Reproduce

1. Login to the site: https://corebanking2.test.vggdev.com/
2. Search for client with any account, for my test I used the following account **000077018**
3. View the details of the client
4. On the client details section in the "Client Details Menu" click  and in the drop-down select -> **Applications** -> **New Fixed Deposit Accounts**
5. Fill the sections **Details**, **Currency**, **Terms**, **Settings**, view the **Interest Chart** and enter **Charges** and **Preview**
6. Submit for creation
7. View savings product selected for the creation of fixed deposit
8. View transaction, no debit occurs, but the credit of fixed deposit was recorded

## Expected Behaviour
Should debit selected fixed savings product during Fixed deposit account creation

## Actual Behaviour
Credits fixed deposit account and fails to debit savings product account selected

## Settings
- Mifos X version: 1.8.4
- Browser used: Chrome, Edge

## Screenshots, if any
<img width="1397" alt="Screenshot 2023-07-18 at 10 10 18 AM" src="https://github.com/openMF/web-app/assets/11774340/9e03ebf0-0bb7-4225-b346-c9f448854e63">
<img width="1397" alt="Screenshot 2023-07-18 at 10 10 56 AM" src="https://github.com/openMF/web-app/assets/11774340/a13404e5-330b-494e-9625-36e6e31a2d9b">

**Comment by bharathcgowda** [comment]
Please check this issue again, as discussed this was not reproducible

**Comment by skemuel007** [comment]
Hello @bharathcgowda, please see a recording of issues expected and actual behaviour comparing old UI and new UI

https://github.com/openMF/web-app/assets/11774340/db361187-e697-4afe-8d1b-ecec8bfdd44f



https://github.com/openMF/web-app/assets/11774340/638b1ab9-cab3-4d75-bc61-72aad31d38d5
