### ISSUE TITLE
Failure to create fixed deposit product

### ISSUE THREAD

**Issue by skemuel007** [openMF/web-app#1797]
## Description
Failed to create fixed deposit product with error message **Failed data validation due to: chart.slabs.start.incorrect**

## Steps to Reproduce
Login to the site:
Click on the  **Admin Menu** Link Item on the menu bar -> click on the **Products** link -> click the **Fixed Deposit Product** section -> click on the **Create New Fixed Deposit Product** button

## Expected Behaviour
Should create a new Fixed deposit product

## Actual Behaviour
Failed to create fixed deposit product with error message **Failed data validation due to: chart.slabs.start.incorrect**

## Settings
- Mifos X version: 1.8.4
- Browser used: Chrome, Edge

## Screenshots, if any
<img width="1448" alt="Screenshot 2023-07-18 at 10 28 20 AM" src="https://github.com/openMF/web-app/assets/11774340/df58f042-a3e3-4816-8dc9-ccc90ba38a4b">

**Comment by josehernandezfintecheandomx** [comment]
In Fineract there is a rule or constraint about the values used in the charts definition, The values for Period To and Amount Range To in the Fixed Deposit Product creation must be nulls

So this is more for Fineract than the WebApp @bharathcgowda

**Comment by bharathcgowda** [comment]
Thanks for the feedback @josehernandezfintecheandomx 

@skemuel007  could you add the screenshot of interest rate chart data you have configured for this product?

**Comment by skemuel007** [comment]
Hello @bharathcgowda, please see attached screen shot of interest chart
<img width="1188" alt="Screenshot 2023-07-27 at 5 51 06 PM" src="https://github.com/openMF/web-app/assets/11774340/fbb0563f-4ea0-4933-9d50-1e714de97c1d">

**Comment by PC-11-00** [comment]
@skemuel007 follow the constraints given at :`https://mifosforge.jira.com/wiki/spaces/docs/pages/121831466/Interest+rate+chart+with+amount+range `
to make the fixed deposit product

https://github.com/openMF/web-app/assets/76156941/3d55b4c8-8ac6-42ba-bcb7-ba3f8969bebe

**Comment by skemuel007** [comment]
@PC-11-00 will follow the above steps and revert, thanks
