### ISSUE TITLE
Account drop down not populating while trying to make account transfer

### ISSUE THREAD

**Issue by skemuel007** [openMF/web-app#1833]
## Description
Account Button fails to populate on the new Mifos X UI when trying to carry out **Account Transfer** action

## Steps to Reproduce
Login to the site: https://corebanking2.test.vggdev.com
Search for the Client with id 77018
View details of the savings account (any, e.g, for our test we used, savings id 188546)
Click the Menu bar at the top right corner of the savings details -> Click on More -> Transfer Funds

## Expected Behaviour
I should be able to select an Account number

## Actual Behaviour
I cannot select an Account number

## Settings
- Mifos X version: 1.8.4
- Browser used: Chrome, Edge

## Screenshots, if any
<img width="1416" alt="Screenshot 2023-08-01 at 7 18 20 AM" src="https://github.com/openMF/web-app/assets/11774340/d825b02b-31ec-45be-9f06-ac91ee00293d">
<img width="876" alt="Screenshot 2023-08-01 at 7 20 45 AM" src="https://github.com/openMF/web-app/assets/11774340/2f245d6c-9f05-432d-879c-9be12b882581">

**Comment by bharathcgowda** [comment]
@skemuel007  this is not an issue.. you can transfer funds from one savings account to another savings account of the same currency only. 
In the example client - there are three savings acccount of 3 different savings products that have different currency to it. 
Hence the dropdown is empty.

You can transfer the funds from one savings account to another of the same currency only

**Comment by bharathcgowda** [comment]
able to reproduce with the same currency as well.
![image](https://github.com/openMF/web-app/assets/65952533/91473382-d356-4c79-88c0-fe7ad464b3b2)

you can test it on

**Comment by bharathcgowda** [comment]
@josehernandezfintecheandomx will you be able to check this issue?
