### ISSUE TITLE
How to config with keyclock 20.0.1 can you explain with front with backend also

### ISSUE THREAD

**Issue by Krishnainy** [openMF/web-app#1842]
How to config with keyclock 20.0.1 can you explain with front with backend also

**Comment by PC-11-00** [comment]
Exactly, what do you want to do by config keylock?

**Comment by Krishnainy** [comment]
For authentication

**Comment by PC-11-00** [comment]
Can you tell me the steps , how you are using webapp?

**Comment by Krishnainy** [comment]
I'm just changed the oauth configuration to true in the environment file
and run the webapp

**Comment by PC-11-00** [comment]
You don't need to change the varibles value in environment.ts to run the webapp

**Comment by PC-11-00** [comment]
What server were you using?

**Comment by Krishnainy** [comment]
Fineract server

**Comment by PC-11-00** [comment]
okay then you will be able to use the webapp 
send me the screenshot of the issue

**Comment by Krishnainy** [comment]
Can you help me with this issue
