### ISSUE TITLE
Surveys: Create  Survey

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#185]
Goal:
As a system admin, I want to create template for a survey which is used in client level. 
https://demo.openmf.org/#/surveys/add
![createsurvey](https://user-images.githubusercontent.com/23022667/43188126-02c2d610-9011-11e8-841c-3e79f60d1bb7.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/MIFOS/pages/73466240/Surveys

**Comment by akanksham3** [comment]
Hi!
I'd like to work on this :D

**Comment by abhaychawla** [comment]
Go ahead!

**Comment by akanksham3** [comment]
What does it mean to "activate" / "deactivate" a survey?
I can't seem to find detailed documentation for surveys in the [Apache Fineract API documentation](https://demo.openmf.org/api-docs/apiLive.htm) (also it's missing from the full API matrix)

I see in the [old app](https://github.com/openMF/community-app/blob/develop/app/scripts/services/ResourceFactoryProvider.js#L93) that it's actually `POST /surveys/{surveyId}/?command=[activate | deactivate]` but it doesn't seem to actually do anything.

According to the API docs, deactivating a survey is supposed to be `DELETE surveys/{surveyId}` and that probably deletes the record altogether, so how do we activate it back again?

The `status` field (denoting whether a survey is "Active" or "Deactivated") is dependent on the `validFrom` and `validTo` fields, the API doesn't seem to indicate such a field about activity at all.
