### ISSUE TITLE
Surveys: List

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#186]
Goal:
As a system admin, I want to view all the existing survey templates, as seen at,
https://demo.openmf.org/#/surveys

![managesurveys](https://user-images.githubusercontent.com/23022667/43188370-915472bc-9011-11e8-9c1c-dbcd94f622c7.png)

Resources:
https://demo.openmf.org/api-docs/apiLive.htm#survey_retrieve
https://mifosforge.jira.com/wiki/spaces/MIFOS/pages/73466240/Surveys

**Comment by akanksham3** [comment]
What does it mean to "activate" / "deactivate" a survey?
I can't seem to find detailed documentation for surveys in the [Apache Fineract API documentation](https://demo.openmf.org/api-docs/apiLive.htm) (also it's missing from the full API matrix)

I see in the [old app](https://github.com/openMF/community-app/blob/develop/app/scripts/services/ResourceFactoryProvider.js#L93) that it's actually `POST /surveys/{surveyId}/?command=[activate | deactivate]` but that doesn't seem to actually do anything in the app.

According to the API docs, deactivating a survey is supposed to be `DELETE /surveys/{surveyId}` and that probably deletes the record altogether, so how do we activate it back again?

The `status` field (denoting whether a survey is "Active" or "Deactivated") is dependent on the `validFrom` and `validTo` fields, the API doesn't seem to indicate such a field about activity at all.

**Comment by abhaychawla** [comment]
@akanksham3 This issue is reserved for GCI 2018 students and you cannot work on this right now. If you have any other queries please ask on the mailing list or the gitter channel.

**Comment by akanksham3** [comment]
Sure, I had asked because the issue I'm assigned to is related to this (creating surveys).
