### ISSUE TITLE
Hide Fund mapping option from front end

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1861]
## Description
Since fund mapping feature is not fully developed. In community-app the fund mapping button was hidden.
same has to be done on the web-app
More details/history  on the issue is here  https://github.com/openMF/community-app/issues/1624
![image](https://github.com/openMF/web-app/assets/65952533/1a654031-62e5-4a10-bff1-9caab52f272d)

## Steps to Reproduce
Please add as much detail as possible to reproduce the error/issue.
Don't assume the reader knows anything about the Mifos X Web App.

## Settings
- Mifos X version: 
- Browser used:

**Comment by ShivangRawat30** [comment]
I can work on this issue

**Comment by bharathcgowda** [comment]
@ShivangRawat30  thank you for volunteering on fixing this issue. I have assigned the same to you.

**Comment by PC-11-00** [comment]
As this issue is completed by @Onyx2406 and code is merged, so we can close this issue.
