### ISSUE TITLE
Savings Product - Edit - Advanced Accounting Rules

### ISSUE THREAD

**Issue by peter-santa-dpc** [openMF/web-app#1888]
## Description
Most of the "Fund Source" is not filled in the table.

## Steps to Reproduce

1. Have a saved Savings Product, with several Advanced Accounting Rules.
2. Open the product for Editing
3. Navigate to the Accounting view.

## Expected Behaviour
The Fund Source is shown in every row, where it is set correctly.

## Actual Behaviour
The Fund Source is not shown for most of the rows, even if the values can be seen in the Network tab of dev tools in a browser - so the API sends them.

## Settings
- Mifos X version: c8703adb
- Browser used: Firefox 119.0 (64-bit)

## Screenshots, if any
![Screenshot 2023-11-02 at 14 08 42](https://github.com/openMF/web-app/assets/45198877/a51bba93-168d-4cf3-b0ae-3967ea2f6c3a)

**Comment by PC-11-00** [comment]
Closing as it is resolved.
