### ISSUE TITLE
Savings Account / Transaction details / Back button does not work

### ISSUE THREAD

**Issue by peter-santa-dpc** [openMF/web-app#1889]
## Description
Navigate to a transaction on a Savings Account, open the details.
The "Back" button does not work.

## Steps to Reproduce
Navigate to a transaction on a Savings Account, open the details. e.g.:
{{url}}/clients/105/savings-accounts/209/transactions/430/general

## Expected Behaviour
The "Back" button should work as a back button.

## Actual Behaviour
The "Back" button does nothing.

## Settings
- Mifos X version: c8703adb
- Browser used: Firefox 119.0 (64-bit)

## Screenshots, if any
![image-20231030-083537](https://github.com/openMF/web-app/assets/45198877/1a4b647f-95ab-493e-b9b5-d2d547abc3ce)

**Comment by PC-11-00** [comment]
@peter-santa-dpc please close the issues that are resolved. Thanks

**Comment by PC-11-00** [comment]
Closing as it is finished.
