### ISSUE TITLE
Improve the description of the password-related checkboxes on the create user and edit user pages

### ISSUE THREAD

**Issue by zmezei-dpc** [openMF/web-app#1891]
**Is your feature request related to a problem? Please describe.**
Currently the create user and edit user pages show this:
<img width="639" alt="image" src="https://github.com/openMF/web-app/assets/59565282/50cd8bb9-32aa-4426-aed2-6389a7f11555">

**Describe the solution you'd like**
The first checkbox should say "Password never expires" the second one should say "Send password to email address".

**Comment by PC-11-00** [comment]
<img width="1438" alt="Screenshot 2024-01-05 at 9 03 46 AM" src="https://github.com/openMF/web-app/assets/76156941/b93301ea-d560-401f-b4ca-b6f837767c81">
It is resolved.
