### ISSUE TITLE
Searching for Client throws a 404 error

### ISSUE THREAD

**Issue by ichux** [openMF/web-app#1893]
## Description
Searching for Client throws a 404 error

## Steps to Reproduce
Clicking on a **running instance** of Mifos X Web App to access clients (Institution > Clients) or browsing to
> http://127.0.0.1:19090/#/clients 
throws a 404 error. On checking the query being sent to Fineract, below is what I saw

```
curl -u mifos:password 'http://127.0.0.1:19090/fineract-provider/api/v2/clients/search' \
-X POST -H 'Accept: application/json' -H 'Fineract-Platform-TenantId: default' \
-H 'Content-Type: application/json' --data-raw '{"request":{"text":""},"page":0,"size":50}'
```
On further analysis, it turns out that a non-existent **api/v2** route is being called.

However, if one searches for the same thing by clicking on the search icon on the _navbar_ and choosing the resource, **Clients**, then entering the search phrase, it works. The below is the request being sent

```
curl -u mifos:password 'http://127.0.0.1:19090/fineract-provider/api/v1/search?exactMatch=false&query=INSTANCEONE&resource=clients,clientIdentifiers' \
-H 'Accept: application/json' -H 'Fineract-Platform-TenantId: default'
```

## Expected Behaviour
Post searches are supposed to return results or empty list but not throw a 404 error

## Actual Behaviour
It's failing

## Settings
- Mifos X version: 231107
- Fineract: 1.8.4
- Browser used: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0

![Screenshot from 2023-11-08 11-43-37](https://github.com/openMF/web-app/assets/30695966/83a8517f-9804-4675-bb9b-bdc8777db0f3)

**Comment by PC-11-00** [comment]
It's working fine, both APIs are working on my local.
