### ISSUE TITLE
Support JSON object on UI

### ISSUE THREAD

**Issue by peter-santa-dpc** [openMF/web-app#1895]
**Background**
It is now supported by Fineract, to store JSON typed object in a Postgres DB field of a data table

- https://github.com/apache/fineract/pull/3513 
- https://issues.apache.org/jira/browse/FINERACT-1996

Currently the UI shows [object Object] instead of the data.

**Goal**
The UI should show a formatted JSON.

**Comment by PC-11-00** [comment]
Closing as it is completed
