### ISSUE TITLE
More than one similar names show up during the addition of event

### ISSUE THREAD

**Issue by ichux** [openMF/web-app#1896]
## Description
Choosing of options during the addition of events has a repeat of displayed option

## Steps to Reproduce
Browse to http://127.0.0.1:19090/#/system/hooks/create, please change **127.0.0.1:19090** to taste.

## Expected Behaviour
One option is enough and there should be no repeats

## Actual Behaviour
There is a repeat of options

## Settings
- Mifos X version: 231107
- Fineract: 1.8.4
- Browser used: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0

## Screenshots, if any
![Screenshot from 2023-11-08 12-20-55](https://github.com/openMF/web-app/assets/30695966/4e9069ad-2b13-4b1f-a55d-a327a9019e6b)

**Comment by PC-11-00** [comment]
It's not an error, someone made two actions with same name, and it's coming from backend, but there is an error, like actions were not dependent on entity so I am working on that.

**Comment by PC-11-00** [comment]
It is resolved.
Thanks
