### ISSUE TITLE
Savings Transaction - assigned data table - ID field shown as decimal

### ISSUE THREAD

**Issue by peter-santa-dpc** [openMF/web-app#1899]
## Description
Data tables can be assigned to savings transaction.
There is a view for data table details. The ID of the "parent" transaction is shown on the view. It is shown with 2 decimals, instead of integer.

## Steps to Reproduce

1. Have a Savings Account
2. Have data table assigned to savings accounts
3. Have a transaction inserted, have an entry inserted in the related data table.

## Expected Behaviour
The ID of the savings transaction is shown without decimals.

## Actual Behaviour
The ID of the savings transaction is shown with decimals.

## Settings
- Mifos X version: c8703adbc156a1bbc4f0d06dbd5250e37934aaac
- Browser used: Firefox 119.0.1 (64-bit)

## Screenshots, if any
![image](https://github.com/openMF/web-app/assets/45198877/979dbaa4-ee15-44b6-a610-da38d85a18d7)

**Comment by peter-santa-dpc** [comment]
https://issues.apache.org/jira/browse/FINERACT-2014 should resolve this issue.

**Comment by PC-11-00** [comment]
Closing as it is resolved.
