### ISSUE TITLE
Create a charge product

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#191]
Goal:
As a system admin, I want to create template for a charge(loan , savings, shares, etc)
https://demo.openmf.org/#/createcharge
![8_createchargepage](https://user-images.githubusercontent.com/23022667/43190142-f4d5bf72-9015-11e8-9218-1c9edaf1dcda.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/72908813/Charges
https://demo.openmf.org/api-docs/apiLive.htm#charges_create

**Comment by roony4** [comment]
can I work on this.?

**Comment by abhaychawla** [comment]
Go ahead.

**Comment by roony4** [comment]
Is it good that If I create 4 components for 4 categories?(Loan,savings,client,shares)

**Comment by abhaychawla** [comment]
No. I don't think so.
