### ISSUE TITLE
Create GL account with "allow manual entries" checkbox disabled not working

### ISSUE THREAD

**Issue by jogathogo** [openMF/web-app#1921]
## Description
Creating a GL account with "manual entries allowed" checkbox set to false disables the submit button

## Steps to Reproduce
Fill the create GL account form with details. Uncheck the "manual entries allowed" checkbox

## Expected Behaviour
Should allow user to submit even with this checkbox set to false

## Actual Behaviour
Submit button disabled when "Manual Entries Allowed" checkbox is disabled

## Settings
- Mifos X version: develop branch
- Browser used: Mozilla, Chrome

## Screenshots, if any
![Screenshot 2023-12-06 at 10 06 10](https://github.com/openMF/web-app/assets/8235531/432d200e-f92b-4c97-9a9a-64c8ddca851c)

**Comment by bharathcgowda** [comment]
@srexrg  yes you can.
@PC-11-00  CC

**Comment by PC-11-00** [comment]
@bharathcgowda is the expected behavior given in the issue correct?

**Comment by bharathcgowda** [comment]
@PC-11-00  yes, it is correct. User should be able to submit the CoA data even if the check box is ticked or not.

**Comment by PC-11-00** [comment]
okay!
Thanks for the confirmation.
