### ISSUE TITLE
Create Recurring Deposit Product

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#193]
Goal:
As a system admin, I want to create recurring deposit product, as seen at,
https://demo.openmf.org/#/createrecurringdepositproduct
![14_createrd](https://user-images.githubusercontent.com/23022667/43190390-8f4166c4-9016-11e8-899a-3a82ffc4c728.png)

Resources:
https://demo.openmf.org/api-docs/apiLive.htm#rdproducts_create
https://mifosforge.jira.com/wiki/spaces/docs/pages/102629552/Recurring+Deposit

**Comment by AashishChakravarty** [comment]
@abhaychawla I would like to work on this.
