### ISSUE TITLE
Standing Instruction "To Account" dropdown not working as expected

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1932]
## Description
Standing Instruction "To Account" dropdown is not showing any values

## Steps to Reproduce
1. go to any client
2. create two basic savings  account
3. go to more-> create standing instructions
4. fill in all details as shared in the screenshot
5. now check the "To Account" dropdown. it is empty
6.

## Expected Behaviour
It should show the relavent loan account/savings account drop downs 
## Settings
- Mifos X version: 
- Browser used: 

## Screenshots, if any
![image](https://github.com/openMF/web-app/assets/65952533/ea8134b6-2729-4861-aa8a-d5f2875ba7d7)

**Comment by PC-11-00** [comment]
@bharathcgowda you didn't fill to office and beneficiary name that's why To Account options didn't come 
<img width="1257" alt="Screenshot 2023-12-14 at 7 35 12 PM" src="https://github.com/openMF/web-app/assets/76156941/68a08826-f77a-4da5-a63b-4cfdd2e6a409">

**Comment by bharathcgowda** [comment]
@PC-11-00 please select the Destination as "own account" which will grey out the "to offfice" and "benificary" as it is the same client.

**Comment by PC-11-00** [comment]
Is To Office always required ? please check

**Comment by bharathcgowda** [comment]
So when the own_account is selected.
It should inherit the office and same client details in the API and from UI
those fields should he grayed out.

**Comment by PC-11-00** [comment]
ohh okay gotcha

**Comment by PC-11-00** [comment]
Resolved
