### ISSUE TITLE
Dividends  button not working on the shares product

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1933]
## Description
Dividends  button not working on the shares product.

## Steps to Reproduce
1.create a shares product
2. open the product and click on the dividends button

## Expected Behaviour
User should be able to see dividends screen and initiate dividends.
you can check the old UI working here and add it same way and same fields
https://dev.mifos.io (mifos/password)

## Settings
- Mifos X version: 
- Browser used: 

## Screenshots, if any
![image](https://github.com/openMF/web-app/assets/65952533/d8405709-4d20-4a32-bd8d-2c960272dd2b)

**Comment by PC-11-00** [comment]
Resolved
