### ISSUE TITLE
Not able to add charge for Reccuring deposit account creation

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1934]
## Description
Not able to add charge for Reccuring deposit account creation

## Steps to Reproduce
To reproduce
1. create a charge product for shares entity
2. create a shares product. but do not map the shares product with shares charge at the shares product level
3. now create a shares account and try to add charges from charge drop down - the charge drop down is empty

## Expected Behaviour
all shares charges with same currency should be available in dropdown

## Screenshots, if any
![image](https://github.com/openMF/web-app/assets/65952533/883315d6-1308-489b-8253-a8501d529ebe)

**Comment by PC-11-00** [comment]
It is resolved.
