### ISSUE TITLE
Maker and Checker Functionality not working

### ISSUE THREAD

**Issue by bharathcgowda** [openMF/web-app#1935]
## Description
Maker and Checker Functionality not working

## Steps to Reproduce
1. enable maker-checker at the admin-> system->configuration level
2. go to admin->system->configure maker and checker tasks.
- make sure "activate client" is checked
4. Now go and create a client
5. client on activate client
-System will activate the client by bypassing the maker and checker rule

## Expected Behaviour
System should hold the activation in pending and user with checker permission should approve or reject from "checker inbox and tasks menu

you can check the working behavior at the https://dev.mifos.io/
## Settings
- Mifos X version: 
- Browser used: 

## Screenshots, if any
![image](https://github.com/openMF/web-app/assets/65952533/4be8f113-a71d-4812-bf56-a777d73d93d4)

**Comment by PC-11-00** [comment]
@bharathcgowda I have resolved this issue but the method I am using for that I will need to change so many files, so @josehernandezfintecheandomx is trying find a way in which we don't need to change every file, I will let you know once if it will be possible to work without changing so many files.
Also, there is a problem in backend, the instance:  https://dev.mifos.io/ , in this instance it is using old backend, so in this maker checker is working but the instance:https://ps-dev1.dev.alluvial.cloud ,it's using latest backend, and in this maker checker is not working

**Comment by bharathcgowda** [comment]
@PC-11-00  ok Please keep the update posted here @josehernandezfintecheandomx CC
I'll slack you regarding the backend issue
