### ISSUE TITLE
Create/View/Edit Floating Rate

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#194]
Goal:
As a system admin, I want to define, view and update floating rate for a loan product, as seen at,
https://demo.openmf.org/#/createfloatingrate
![18_createflrate](https://user-images.githubusercontent.com/23022667/43190528-deae2116-9016-11e8-9d90-047737ddc337.png)
https://staging.openmf.org/#/viewfloatingrate/8
![view fr](https://user-images.githubusercontent.com/16948598/58336661-c3001200-7e61-11e9-80f3-293019a42be9.PNG)
https://staging.openmf.org/#/editfloatingrate/8
![edit fr](https://user-images.githubusercontent.com/16948598/58336713-de6b1d00-7e61-11e9-98a4-7aa5c9d3b881.PNG)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/111673386/Floating+Rate
https://demo.openmf.org/api-docs/apiLive.htm#floatingrates

**Comment by luckyman20** [comment]
@santoshconflux Can you please update this issue so it includes all the screens related to floating rates?

**Comment by karantakalkar** [comment]
@abhaychawla please close it
