### ISSUE TITLE
Transaction details - hard-coded currency sign

### ISSUE THREAD

**Issue by peter-santa-dpc** [openMF/web-app#1947]
## Description
At Home/Clients/”Any Client”/Savings/Transactions General tab the amount has a $ sign in front of them when the amount is in different currency.

## Expected Behaviour
The correct currency should be shown(, or nothing)

## Actual Behaviour
$ sign is shown, independently from the current behaviour.

## Settings
- Mifos X version: f6edab0dd503a720c769b8cd9483f59819412cb4
- Browser used: Firefox, Chrome

## Screenshots, if any
![image-20231221-142610](https://github.com/openMF/web-app/assets/45198877/b1af1363-3094-4727-afe9-4034907a1bc8)

**Comment by PC-11-00** [comment]
It is resolved.
