### ISSUE TITLE
Product Mix List

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#195]
Goal:
As a system admin, I want to view all product mix, as seen here
https://demo.openmf.org/#/productmix
![9_productmixlist](https://user-images.githubusercontent.com/23022667/43192268-c21d8812-901a-11e8-8d42-28589b69f5a9.png)

Resources:
https://demo.openmf.org/api-docs/apiLive.htm#loanproductmix
https://mifosforge.jira.com/wiki/spaces/docs/pages/103186467/Product+Mix

**Comment by jonathanzhang53** [comment]
[https://demo.openmf.org/fineract-provider/api/v1/loanproducts?associations=productMixes&tenantIdentifier=default&pretty=true](https://demo.openmf.org/fineract-provider/api/v1/loanproducts?associations=productMixes&tenantIdentifier=default&pretty=true)
[https://demo.openmf.org/api-docs/apiLive.htm#loanproductmix](https://demo.openmf.org/api-docs/apiLive.htm#loanproductmix)

`/loanproducts?associations=productMixes`

Would the above be a correct API request for this? I can't seem to get it to work while I was able to get it to work with datatables.

Service:

```
  getProducts(): Observable<any> {
    return this.http.get('/loanproducts?associations=productMixes');
  }
```

Resolver:
```
  resolve(): Observable<any> {
    return this.productsService.getProducts();
  }
```

Component.ts:

```
  ngOnInit() {
    this.setProductsMix();
  }
   /**
   * Initializes the data source, paginator and sorter for products mix table.
   */
  setProductsMix() {
    this.dataSource = new MatTableDataSource(this.productData);
    this.dataSource.paginator = this.paginator;
    this.dataSource.sortingDataAccessor = (product: any, property: any) => {
      switch (property) {
        case 'productName': return product.productName;
        default: return product[property];
      }
    };
    this.dataSource.sort = this.sort;
  }
```

Component.html:

```
    <table mat-table [dataSource]="dataSource" matSort>

      <ng-container matColumnDef="productName">
        <th mat-header-cell *matHeaderCellDef mat-sort-header> Product Name </th>
        <td mat-cell *matCellDef="let product"> {{ product.productName }} </td>
      </ng-container>

      <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
      <tr mat-row *matRowDef="let row; columns: displayedColumns;" class="select-row"></tr>

    </table>
```

I'm sure I've got all the routing/imports/exports correct as I have compared them with my current working PR on datatables #336

**Comment by abhaychawla** [comment]
Yes, this is the correct API request. Have a look at the community-app implementation to see the object property which is being used to access. Whenever you are taking up a task to replicate, you should first look into the community-app code to see how its implemented. This might not be the right property or the way you are trying to access it might also require changes.

**Comment by jonathanzhang53** [comment]
I looked into community-app. I got the property right and if the API request is correct, then I guess accessing is a bit different. Let's see.
