### ISSUE TITLE
updating the UI and having popup system structured

### ISSUE THREAD

**Issue by kunjgit** [openMF/web-app#1955]
**Describe the solution you'd like**
I will be implementing the toasts to show the popups and also making sure that I am changing the ui of the toasts according design as well

**Comment by kunjgit** [comment]
I would love to work on this issue assign me this issue :smile: !

**Comment by PC-11-00** [comment]
Please read the contribution guidelines first: https://github.com/openMF/web-app/blob/master/.github/CONTRIBUTING.md
and please share screenshot also how will it look like.

**Comment by kunjgit** [comment]
Hey @PC-11-00 !
I want to update popup system with modern toasts and want to replace that at all the popups with updated one 
toasts will look like below few examples with some good transition 
![Screenshot from 2024-01-16 21-54-09](https://github.com/openMF/web-app/assets/103763618/96b779a7-b5bf-48ff-8154-368b6af6d183)
![Screenshot from 2024-01-16 21-52-48](https://github.com/openMF/web-app/assets/103763618/3da3a62d-313c-4d4d-863a-4acb42b89248)
![Screenshot from 2024-01-16 21-52-24](https://github.com/openMF/web-app/assets/103763618/5ab4f146-b221-4ef2-8a90-34c1f43ce290)

even in form of long dialoags as well with positions customized and theme customization as well ! 
also want to fix this is overlapping and because of that we can't function the below item 
![Screenshot from 2024-01-16 21-58-49](https://github.com/openMF/web-app/assets/103763618/faea02b3-fe4c-4e25-8524-8609fea57692)


hope that I have put my point across would love to contribute !
also can you tell me how can I reach out to you in case of queries

**Comment by PC-11-00** [comment]
@kunjgit you can reach out to me on slack and regarding the pop-up updates you need to talk to @bharathcgowda and in last case of overlapping : you can work on that but don't change theme.

**Comment by kunjgit** [comment]
Okay @PC-11-00 ! @bharathcgowda can you assign me the issue so I can work on it :smile: !
