### ISSUE TITLE
FIRST KEY HIDE ON KEYBOARD SHORTCUTS

### ISSUE THREAD

**Issue by HitanshuPrasad** [openMF/web-app#1956]
## Description
First key is hidden on on Keybaord shortcuts.

## Steps to Reproduce
Click on the keyboard shortcuts tab on the navigation tab at left side of screen.

## Expected Behaviour

There should be proper margin  for first key to the top .
## Actual Behaviour
Key is partially hidden.

## Settings
- Mifos X version: Git latest
- Browser used: Google zChrome

## Screenshots, if any
![Screenshot from 2024-01-06 23-50-50](https://github.com/openMF/web-app/assets/96762115/36b2e886-70b2-4890-82fd-309047044244)

**Comment by liaozhuzhu** [comment]
Great solution! Quick side note, make sure not to do `git add .` when you commit your code. I noticed your `angular.json` and `env.ts` files have been updated in your PR.
