### ISSUE TITLE
Add/edit Product  Mix

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#196]
Goal:
As a system admin, I want to add/edit the product mix,as seen here:
https://demo.openmf.org/#/addproductmix
https://demo.openmf.org/#/editproductmix/5
![10_addprodmix](https://user-images.githubusercontent.com/23022667/43192423-2b458506-901b-11e8-888d-8d54aa582de5.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/103186467/Product+Mix
https://demo.mifos.io/api-docs/apiLive.htm#loanproductmix_create
https://demo.openmf.org/api-docs/apiLive.htm#loanproductmix_update

**Comment by abhaychawla** [comment]
**NOTE**: Use multi-select form field for restricted products.
