### ISSUE TITLE
Fix Label for External Asset Owner Sell Loan Button - Button Label currently reads "Sale Loan"

### ISSUE THREAD

**Issue by edcable** [openMF/web-app#1966]
## Description
The action the button enables is to "sell loan". Label incorrectly reads "sale loan" and should be corrected to be "sell loan"

## Steps to Reproduce
Navigate to any active loan and go to the External Asset owner tab and one will see the button labeled "Sale Loan"

## Expected Behaviour

Button should read "Sell Loan"

## Actual Behaviour

Button reads "Sale Loan"

## Screenshots, if any

<img width="1106" alt="Screenshot 2024-01-13 at 8 47 51 AM" src="https://github.com/openMF/web-app/assets/823454/0616321c-894a-43fc-8591-c4a468a563a3">

**Comment by PC-11-00** [comment]
It is resolved. Thanks.
