### ISSUE TITLE
Manage Tax Component

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#197]
Goal: 
As a system admin, I want to view tax components:
https://demo.openmf.org/#/taxcomponents
![15_managetaxcomponent](https://user-images.githubusercontent.com/23022667/43192616-8d5b3678-901b-11e8-9a57-48d63f80e0bd.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/129957925/Manage+Tax+configuration
https://demo.openmf.org/api-docs/apiLive.htm#taxcomponent

**Comment by Verdiane** [comment]
Hi abhaychawla, I will like to work on this issue

**Comment by abhaychawla** [comment]
Go ahead @Verdiane.

**Comment by Verdiane** [comment]
Thanks, I will send my PR soon

**Comment by Verdiane** [comment]
Hello @abhaychawla , I have already sent a PRs, Please can you review it
