### ISSUE TITLE
Fixed deposit product values should appear as default values when creating a fixed deposit account

### ISSUE THREAD

**Issue by jogathogo** [openMF/web-app#1974]
## Description
When creating a fixed deposit account, the values configured at the product level are not populated as default values.

## Steps to Reproduce
Configure a fixed deposit product
Attempt to create a fixed deposit account, the fields under "terms" tab are all blank and the user has to select them

## Expected Behaviour
Ideally, the values set at the product level should appear as defaults but allow the user to change them

## Actual Behaviour
T

https://github.com/openMF/web-app/assets/8235531/5a577932-bff6-45b9-8cb0-d3b88e20732e

he fields under "terms" tab are all blank and the user has to select them

## Settings
- Mifos X version: 
- Browser used:

**Comment by PC-11-00** [comment]
It's a backend problem deposit amount is not coming from the API
<img width="1438" alt="Screenshot 2024-01-26 at 7 36 56 PM" src="https://github.com/openMF/web-app/assets/76156941/be98304a-115f-4700-9475-db489fb306cf">
