### ISSUE TITLE
System freezes when post interest button clicked in fixed deposit

### ISSUE THREAD

**Issue by jogathogo** [openMF/web-app#1978]
## Description
The system freezes and has to be refreshed when post interest button is selected

## Steps to Reproduce
Create and activate a fixed deposit account
Click on post interest option found under more(the three thin icon)

## Expected Behaviour
Interest gets computed and posted into the FD account if FD has interest to be posted. If not, the FD account page is loaded

## Actual Behaviour
Whole application freezes

https://github.com/openMF/web-app/assets/8235531/c082a415-df8e-4be0-959f-fa32bfce6027

## Settings
- Mifos X version: 
- Browser used:

**Comment by shashank-iitbhu** [comment]
Hey, @jogathogo ! I am trying to reproduce this issue. 
I have set up the project locally and the server is running on port 4200, but when i am trying to open any services from the sidebar i am getting this warning popup: ```User has authority to view offices.```
<img width="1470" alt="Screenshot 2024-01-27 at 6 10 10 PM" src="https://github.com/openMF/web-app/assets/134289475/5892a072-c16b-433f-948f-b9baaaf1fecc">
How to bypass this issue?

**Comment by shashank-iitbhu** [comment]
Followed the steps in ```Readme.md``` correctly. Are there any configurations i need to set before serving?

**Comment by PC-11-00** [comment]
@shashank-iitbhu please ask setup regarding questions in slack channel only

**Comment by alberto-art3ch** [comment]
Please use the latest version of Web-App UI where we have more functionality and issues solved
