### ISSUE TITLE
Create Tax Component

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#198]
Goal:
As a system admin, I want to create new tax component.
https://demo.openmf.org/#/createtaxcomponent
![16_printtaxcomponent](https://user-images.githubusercontent.com/23022667/43192775-e829446e-901b-11e8-885a-20ef5b291b69.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/129957925/Manage+Tax+configuration
https://demo.openmf.org/api-docs/apiLive.htm#create_taxcomponent

**Comment by kerlynNkep** [comment]
Hello @abhaychawla , I wish to work on this issue but the product page doesn't exist. Can i create an issue for the product page and build it first or what do you suggest.

**Comment by tonic889** [comment]
Submitted PR #605 for this issue

**Comment by abhaychawla** [comment]
The issue was already fixed by another PR, please check before you start working. Also, comment on the issue before you start working on it.
