### ISSUE TITLE
Deposit to a recurring deposit account failing

### ISSUE THREAD

**Issue by jogathogo** [openMF/web-app#1980]
## Description
Deposit to a recurring deposit account failing

## Steps to Reproduce
Create and activate a recurring deposit account
Attempt to make a deposit
Error message appears: **The query parameter command has an unsupported value of: deposit**

## Expected Behaviour
Funds are deposited successfully

## Actual Behaviour
Error message appears: **The query parameter command has an unsupported value of: deposit**

## Settings
- Mifos X version: 
- Browser used:

**Comment by PC-11-00** [comment]
https://github.com/openMF/web-app/assets/76156941/c104b97f-107f-4733-a3d2-e66611ae6101

please give more information, because I can deposit, how you made recurring deposit account

**Comment by galanggg** [comment]
> Screen.Recording.2024-01-26.at.6.12.00.PM.mov 
> please give more information, because I can deposit, how you made recurring deposit account

Hi, @PC-11-00 maybe this is an OOT question, but I want to ask how did you run the web-app locally? I already tried it and can access it with the username and password provided in readme. But I get CORS when I try to access the client page. Are we using demo env to work on local?

Thanks.

**Comment by PC-11-00** [comment]
You can run backend locally using apache fineract: https://github.com/apache/fineract 
Then, choose server localhost:8443
