### ISSUE TITLE
Client transfer reject or undo fails with error message "The parameter date transfer is not supported"

### ISSUE THREAD

**Issue by jogathogo** [openMF/web-app#1983]
## Description
Rejecting a client transfer request fails with an error message "The parameter date transfer is not supported"

## Steps to Reproduce
Assumptions:
- There are atleast two active offices

1. Create and activate a client
2. Initiate client transfer
3. Attempt to reject client transfer

## Expected Behaviour
Client transfer request is rejected and the client reinstated to the original office

## Actual Behaviour
System raises error message: The parameter date transfer is not supported

https://github.com/openMF/web-app/assets/8235531/533fb5fd-faec-413d-ab40-55cdaaa3f97f

## Settings
- Mifos X version: 
- Browser used:

**Comment by shashankiitbhu** [comment]
I want to work on this, Can you assign this to me ? @jogathogo

**Comment by PC-11-00** [comment]
@jogathogo I can't tell without knowing your backend instance because at my end it's working fine.

https://github.com/openMF/web-app/assets/76156941/f096a2aa-548b-4f98-b565-154a0d3edc38

**Comment by Gifty1** [comment]
hi ,can i work on this ?or any one working on this problem?

**Comment by jogathogo** [comment]
Thanks for looking into this Rani, please go ahead.

**Comment by Gifty1** [comment]
ok sure
