### ISSUE TITLE
Accounting: Frequent Posting

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#199]
Goal:
As an accountant, I want to create Frequent postings as given here:
https://demo.openmf.org/#/freqposting
![frequentpostings](https://user-images.githubusercontent.com/23022667/43197853-31d138f2-902a-11e8-81d3-addbbc80f8fd.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/106430551/Frequent+Postings

Related tickets:
https://github.com/openMF/web-app/issues/130
https://github.com/openMF/web-app/issues/136
https://github.com/openMF/web-app/issues/139

**Comment by abhaychawla** [comment]
@santoshconflux I am currently working on the accounting component as assigned to me by @gauravsaini03 as part of my GSoC. I have already implemented this.

**Comment by santoshconflux** [comment]
@abhaychawla , did you create ticket for this pull request?
https://github.com/openMF/web-app/pull/140

**Comment by abhaychawla** [comment]
Yes @santoshconflux 
Here: 
https://github.com/openMF/web-app/issues/136
https://github.com/openMF/web-app/issues/139

**Comment by santoshconflux** [comment]
@abhaychawla , changed the labels. It won't be part of c4gw.

**Comment by abhaychawla** [comment]
Yes, currently I have been assigned the Accounting Component as the Self Service APIs aren't available.

**Comment by santoshconflux** [comment]
@abhaychawla ,Okay. let me confirm about this. T

**Comment by abhaychawla** [comment]
Okay.

**Comment by abhaychawla** [comment]
Closed via
https://github.com/openMF/web-app/commit/d8d05466a1e7e4d7203ff7b506e182e07060a315
https://github.com/openMF/web-app/commit/a22bd6d1e55593c22549ad48be0c1d737a5ce470
https://github.com/openMF/web-app/commit/ec7e871ac6f7aeb5b1c3f7a0789bfeaec3fcc14c
