### ISSUE TITLE
Accounting: Add Journal Entry

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#200]
Goal:
As an accountant, I want to create  manual journal entries as  given here:
https://demo.openmf.org/#/journalentry
![add journal entry](https://user-images.githubusercontent.com/23022667/43198024-beafd0d0-902a-11e8-9df1-a0e60293dfb3.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67895310/Add+Journal+Entries
https://demo.openmf.org/api-docs/apiLive.htm#journalentries_create

Related Tickets:
https://github.com/openMF/web-app/issues/143

**Comment by abhaychawla** [comment]
@santoshconflux Implemented this as well.
Issue: https://github.com/openMF/web-app/issues/143
Pull Request: https://github.com/openMF/web-app/pull/144

**Comment by abhaychawla** [comment]
Closed via https://github.com/openMF/web-app/commit/4f095b76cf70063a99c0da4e39a414d60224ad60
