### ISSUE TITLE
Accounting: Search Journal Entries

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#201]
Goal:
As an accountant, I want to search existing journal entries by office, date, transaction  id , etc, as given here: https://demo.openmf.org/#/searchtransaction
![searchjournalentri](https://user-images.githubusercontent.com/23022667/43198127-2d71bbe6-902b-11e8-8d9b-d22334b0617c.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67895312/Searching+Accounting+Transactions

**Comment by abhaychawla** [comment]
@santoshconflux Currently working on this. Could the accounting component be left out of the c4gw and made a part of GSoC instead?

**Comment by abhaychawla** [comment]
Closed via https://github.com/openMF/web-app/commit/bf989152e212758c62282db1823e12850bb44826
