### ISSUE TITLE
Bug : Keyboard shortcuts not working

### ISSUE THREAD

**Issue by kunjgit** [openMF/web-app#2012]
## Description
because of pre defined binding of the browser shortcuts the shortcuts are not working 
## Steps to Reproduce
shifting the keyboard shortcuts that are not conflicting with the browser shortcuts 

## Expected Behaviour
It should relocate us to the feature specified in shorcut binding 
## Actual Behaviour
As browser shortcuts are defined already it will not work as expected 
## Settings
- Mifos X version: 
- Browser used: 

## Screenshots, if any

https://github.com/openMF/web-app/assets/103763618/a803501b-9f8f-4dbd-b87a-e6ccfcd178a8

**Comment by kunjgit** [comment]
@PC-11-00 assign me this issue I will be moving forward with this 👀

**Comment by PC-11-00** [comment]
This is not an issue.

https://github.com/openMF/web-app/assets/76156941/2e011c58-6d37-4b59-8216-41a0c9f94045

**Comment by kunjgit** [comment]
@PC-11-00 it's because browsers shorcuts might be disabled or what ?
otherwise in all other browser shortcut starts with ctrl which is not letting these shortcuts work 🙁

**Comment by PC-11-00** [comment]
You should try with Linux Systems , I can't comment for windows.

**Comment by PC-11-00** [comment]
Last year I checked on windows too, they were working.

**Comment by kunjgit** [comment]
if it's the case we have to shift it to alt or any other combination as it's default for browser and I guess we can't prevent that default behaviour as far as I have checked it so only many of app keeps shortcuts either just character or any other combination !

**Comment by PC-11-00** [comment]
Please read this issue:https://github.com/openMF/web-app/issues/1716

**Comment by kunjgit** [comment]
Seems the same thing I was going to do ..
what do you think @PC-11-00 now ?
should we shift it to alt because there won't be any issues there I tried in my other machine as well having the same issue !

**Comment by PC-11-00** [comment]
Uploading Screen Recording 2024-03-04 at 10.13.17 PM.mov…

It's working on FireFox too and Alt and shift shortcuts don't work on MACs 
You need to tell on which key you are facing issue.

**Comment by kunjgit** [comment]
in windows ctrl only is creating issue ..
as almost each character is having some and another shortcut !

**Comment by kunjgit** [comment]
Have a look at this : https://support.google.com/chrome/answer/157179?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Cgoogle-chrome-feature-shortcuts%2Ctab-window-shortcuts

**Comment by PC-11-00** [comment]
You need to tell which on which you are facing issues.

**Comment by PC-11-00** [comment]
Come on slack

**Comment by PC-11-00** [comment]
This issue is resolved.
