### ISSUE TITLE
Blank Page Appears on Clicking Notification Button in Top Bar

### ISSUE THREAD

**Issue by piyushs131** [openMF/web-app#2016]
## Description
When clicking on the notification button in the top bar, instead of being directed to the notification page, a blank page on the top side appears.

## Steps to Reproduce

1: Navigate to the application.
2: Click on the notification button in the top bar.

## Expected Behaviour
Upon clicking the notification button, the user should be redirected to the notification page.

##Proposed Solution
To resolve this issue, we need to ensure that clicking the notification button in the top bar correctly navigates the user to the notification page.

## Settings
- Mifos X version: 
- Browser used: 

## Screenshots, if any

![Screenshot 2024-03-06 171303](https://github.com/openMF/web-app/assets/140651227/602d0a33-e1dc-48a6-a69c-136552036152)

**Comment by piyushs131** [comment]
I have recently saw this issue on the Mifos website and have already begun working on it.

**Comment by PC-11-00** [comment]
<img width="1440" alt="Screenshot 2024-03-09 at 12 41 29 PM" src="https://github.com/openMF/web-app/assets/76156941/bc40026f-fac1-41df-ab59-31510449a694">
Not an issue.
