### ISSUE TITLE
Accounting: Accounts linked to Financial Activities (Financial Activity  Mapping)

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#202]
Goal:
As an accountant, I want to map certain financial activity to particular GL account.
https://demo.openmf.org/#/financialactivityaccountmappings
![financial activity mapping](https://user-images.githubusercontent.com/23022667/43198437-4a4a6de8-902c-11e8-8645-dff9f83583df.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/106430472/Accounts+linked+to+Financial+Activities
https://demo.openmf.org/api-docs/apiLive.htm#officeglaccount

**Comment by abhaychawla** [comment]
Closed via https://github.com/openMF/web-app/pull/241
