### ISSUE TITLE
System Hangs in Creating a Savings Product

### ISSUE THREAD

**Issue by Adaks** [openMF/web-app#2020]
## Description
I just grabbed the Docker image for the web app. While trying to set up a savings product, I encountered an issue. The system hangs when I get to the `Terms` section after entering the `Nominal Annual Interest Rate`. When I click 'Next', nothing happens. Even after reloading, it takes a considerable amount of time, only to open a blank page for creating a savings product.

## Steps to Reproduce
Login to Mifos using `mifos` as username: `password` as the password. then you click on `Admin` on the top menu bar which activates a dropdown menu. In the dropdown menu select `Products`. When the page opens, click on `Savings Products`. When the page opens, click the `Create Savings Product` button. The form opens. You can click next till you reach the `Terms` portion. Type a number in the `Norminal Annual Interest Rate` and then click next.

## Expected Behaviour
The UI fails to respond until you reload and the user cannot create a savings product.

## Actual Behaviour
The UI is supposed to append a checked `Preview` portion on the step progress

## Settings
- Mifos X version: latest
- Browser used: Firefox and Chromium

**Comment by PC-11-00** [comment]
Wroking on it.
