### ISSUE TITLE
Accounting : Chart of Accounts list

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#203]
Goal:
As an accountant, I want to view  all existing chart of accounts listwise as shown here:
https://demo.openmf.org/#/accounting_coa
![chart of accounts-list view](https://user-images.githubusercontent.com/23022667/43198649-0c3894ca-902d-11e8-86f5-5f0cd26f7ae2.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67141745/Chart+of+Accounts+-+General+Ledger+Setup
https://demo.openmf.org/api-docs/apiLive.htm#glaccounts

**Comment by abhaychawla** [comment]
Closed via 6643e44afc98488c4ee3ed52972cf97782524693
