### ISSUE TITLE
Components overlapping on login screen

### ISSUE THREAD

**Issue by bhattabhi013** [openMF/web-app#2038]
## Description
Provide a brief overview of the enhancement or issue.
Due to insufficient padding, components overlap each other on the login page

## Steps to Reproduce
Visit the login page

## Expected Behaviour
Sufficient padding and space

## Actual Behaviour
Insufficient padding and components overlapping on the login screen

## Settings
- Browser used: Chrome

## Screenshots, if any
<img width="1087" alt="image" src="https://github.com/openMF/web-app/assets/47862474/8b0e9cc7-b317-49e2-86f7-f787eed823f5">

**Comment by vikashsprem** [comment]
This issue has been resolved.
