### ISSUE TITLE
Accounting: Chart of Accounts - Tree View

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#204]
Goal:
As an accountant, I want  tree view of  all GL accounts as shown here:
https://demo.openmf.org/#/accounting_coa
![coa of tree view](https://user-images.githubusercontent.com/23022667/43198858-ae350e7a-902d-11e8-8251-e61a4b677702.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67141745/Chart+of+Accounts+-+General+Ledger+Setup
https://demo.openmf.org/api-docs/apiLive.htm#glaccounts

**Comment by abhaychawla** [comment]
Closed via 6f6378aa0e06409e589615ce0b5773fc1a808fb8
