### ISSUE TITLE
Accounting: General Ledger Account

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#205]
Goal:
As an accountant, I want to have the following features for GL Accounts (chart-of-accounts):
* Create GL Account
* View GL Account
* Edit GL Account 
* Enable/Disable GL Account
* Delete GL Account
* Create Sub-ledger Account

https://demo.openmf.org/#/createglaccount
![create coa](https://user-images.githubusercontent.com/23022667/43199357-4b704cda-902f-11e8-8572-4712d587756c.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67141745/Chart+of+Accounts+-+General+Ledger+Setup
https://demo.openmf.org/api-docs/apiLive.htm#glaccounts_create

**Comment by abhaychawla** [comment]
Closed via https://github.com/openMF/web-app/pull/270
