### ISSUE TITLE
Share Account Creation Page missing labels during configuration of Terms

### ISSUE THREAD

**Issue by edcable** [openMF/web-app#2051]
## Description
During Terms workflow step of share account creation, a couple of the fields are missing their human-readable label

## Steps to Reproduce
Navigate to any account and attempt to open a new application for a share account. Navigate to second step of the flow, terms. You will see two fields that don't have their label properly displayed. 

See https://sandbox.mifos.community/#/clients/1/shares-accounts/create

## Settings
- Mifos X version: Tested on Fineract Dev Branch on https://sandbox.mifos.community
- Browser used: Chrome 

## Screenshots, if any
<img width="1204" alt="Screenshot 2024-03-21 at 2 49 45 PM" src="https://github.com/openMF/web-app/assets/823454/49c9da32-7079-421f-b345-e2aecc940d73">

**Comment by PC-11-00** [comment]
It is resolved. Thanks
