### ISSUE TITLE
Accounting: Add Accounting Rule

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#206]
Goal:
As an accountant, I want to have the following features for accounting rules by which how frequent postings need to be done:
* View all Accounting Rules
* Create Accounting Rule
* View Accounting Rule
* Edit Accounting Rule
* Delete Accounting Rule

https://demo.openmf.org/#/add_accrule
![add accounting rule](https://user-images.githubusercontent.com/23022667/43199583-1bb5c14a-9030-11e8-9e7d-90be9e4bb0ba.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/106430468/Accounting+Rules
https://demo.openmf.org/api-docs/apiLive.htm#accountingrules_create

**Comment by abhaychawla** [comment]
Closed via https://github.com/openMF/web-app/pull/272
