### ISSUE TITLE
Solving docker build issues

### ISSUE THREAD

**Issue by ichux** [openMF/web-app#2068]
**Is your feature request related to a problem? Please describe.**
The default docker-compose leads to the error show below. So many libraries need updating
![image](https://github.com/openMF/web-app/assets/30695966/7183c295-ea33-483a-9804-0c697bef1dfd)

**Describe the solution you'd like**
I want to push what I did to make mine work, then upon approval it will be adopted. 

**Describe alternatives you've considered**
Mine is the alternative I considered, which involved dynamically updating what is in the codebase

**Comment by PC-11-00** [comment]
@ichux go ahead and make a PR

**Comment by ichux** [comment]
I did it failed by saying I didn't have the rights!
