### ISSUE TITLE
Accounting: Closing Entries

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#208]
Goal:
As  an accountant, I want to have the following features for closing entries of offices:
* View all Closing Entries
* Create Closure
* View Closure 
* Edit Closure
* Delete Closure

https://demo.openmf.org/#/accounts_closure
![closing entries](https://user-images.githubusercontent.com/23022667/43199988-705d4424-9031-11e8-9cc7-5a44a519dbdc.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67895316/Closing+Entries
https://demo.openmf.org/api-docs/apiLive.htm#glclosures

**Comment by abhaychawla** [comment]
Closed via https://github.com/openMF/web-app/pull/271
