### ISSUE TITLE
Bulk JLG loan applications menu not working

### ISSUE THREAD

**Issue by ferguzon** [openMF/web-app#2080]
## Description
The bulk JLG loan applications menu is not working, therefore, it's not possible to access this option from Mifos interface. Reports of other users indicate that the API is working, so it seems to be a Mifos issue.

## Steps to Reproduce

1. Go to Institution menu, then "Groups".
2. Select a group by clicking on it, then choose the menu group (the 3 horizontal lines to the right), then applications and then click on "JLG loan applications"

## Expected Behaviour

You should be taken to the bulk JLG loan applications form to create a new application.

## Actual Behaviour

Nothing happens. You stay in the groups profile.

## Settings
- Mifos X version:  231231
- Browser used: Firefox 125.0.2 (it was also tested using Chrome)

## Screenshots, if any

![bulk](https://github.com/openMF/web-app/assets/15041881/177198cd-65cb-4613-9bac-3d1eec73fd04)

**Comment by Gprocessor** [comment]
This issue still persist in the current build
