### ISSUE TITLE
Centers: List View

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#209]
Goal:
As a loan officer, I want to view all existing centers as shown here:
https://demo.openmf.org/#/centers

 
![center list](https://user-images.githubusercontent.com/23022667/43200333-de2df362-9032-11e8-84a5-9dd768fd710e.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67895340/Manage+Centers
https://demo.openmf.org/api-docs/apiLive.htm#centers

**Comment by anweshknayak** [comment]
@santoshconflux working on this

**Comment by anweshknayak** [comment]
@santoshconflux done
