### ISSUE TITLE
Centers: Create Center Page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#210]
Goal:
As a loan officer, I need to create new center as shown here:
https://demo.openmf.org/#/createcenter
![create center](https://user-images.githubusercontent.com/23022667/43200429-30048caa-9033-11e8-9707-84dd7226a783.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67895340/Manage+Centers
https://demo.openmf.org/api-docs/apiLive.htm#centers_create

**Comment by abhaychawla** [comment]
@cabrelkemfang go ahead!

**Comment by karantakalkar** [comment]
@abhaychawla 
I have completed my last PR( #592 ) , can i work on this issue please?

**Comment by karantakalkar** [comment]
submitted PR without approval only after 48 hours.
