### ISSUE TITLE
Groups: list view

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#211]
Goal: 
As a loan officer , I want to view all groups belonging to me as shown here:
https://demo.openmf.org/#/groups
![group list](https://user-images.githubusercontent.com/23022667/43200540-7b8ce730-9033-11e8-9f7b-f415ad989e24.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67895334/Manage+Groups
https://demo.openmf.org/api-docs/apiLive.htm#groups

**Comment by anweshknayak** [comment]
@santoshconflux done
