### ISSUE TITLE
Disburse Button On checker and inbox does nothing 

### ISSUE THREAD

**Issue by Gprocessor** [openMF/web-app#2122]
## Description
The disburse button under checker and inbox does not have any effect on loans

## Steps to Reproduce
Login
Select a client via institution - client
Create a new loan account
Click the three lines menu button on the left hand side
Click the checker and inbox 
Click loan approval
Approve the loan
Click loan disburse
Select the loan and click disburse

## Expected Behaviour
The loan is supposed to be disbursed and leaves the workflow

## Actual Behaviour
Nothing happens

## Settings
- Mifos X version: 24
- Browser used: chrome,Firefox,edge

**Comment by shivam-daksh** [comment]
Hey @Gprocessor , could you please elaborate the issue through any screenshot? I'm new here.
