### ISSUE TITLE
Refactor code structure

### ISSUE THREAD

**Issue by anweshknayak** [openMF/web-app#213]
Refactor following components:

- [X] Clients
- [ ] Groups
- [ ] Centers

Related Issues:
#75 
#138 
#384

**Comment by love-opensource** [comment]
Hi! I'll like to work on this.
What I'm I required to do?

**Comment by abhaychawla** [comment]
@love-opensource You are supposed to ensure all the code in these sections is refractored according to the accounting section. Let me know if you will be able to work on this.

**Comment by karantakalkar** [comment]
not relevant anymore
