### ISSUE TITLE
Clients: Client list page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#214]
Goal:
As a loan officer, I want to view list of clients assigned to  me as shown here:
https://demo.openmf.org/#/clients

add following features in view all clients page:
- [x] use statuslookup.pipe to set styles to represent status of the client
- [x] add button to import client and create client
- [x] add server side pagination 
- [x] toggle show closed clients in table 

![client list](https://user-images.githubusercontent.com/23022667/43242804-bc7cba58-90c0-11e8-86c6-ed6ef957d504.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67895338/Manage+Clients
https://demo.openmf.org/api-docs/apiLive.htm#clients

Related suggestion for this  ticket: 
https://github.com/openMF/web-app/issues/79

**Comment by Verdiane** [comment]
Hello @abhaychawla , I will like to work on this issue
Please, What are the changes required to be done??
Thanks.

**Comment by abhaychawla** [comment]
@Verdiane This page has been already implemented. Although, it's code requires some refactoring to ensure it is not obsolete and consistent with that of the accounting section. If you choose to do this, you have to ensure that all the obsolete parts of the code being used for this page are removed and updated.

**Comment by Verdiane** [comment]
Thanks @abhaychawla , I will do the refactoring and the Updating

**Comment by Jov03** [comment]
I have updated the issue in order to track all the features which should be present in this screen

**Comment by Jov03** [comment]
Creating a separate issue for search

**Comment by abhaychawla** [comment]
Closed by https://github.com/openMF/web-app/pull/446.
