### ISSUE TITLE
Clients:  Create/Edit Client page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#215]
Goal:
 As a loan officer, I want  to on-board a client with basic details  and address  & family details  if required, as shown here:
https://demo.openmf.org/#/createclient
![create client page](https://user-images.githubusercontent.com/23022667/43242931-54371d2a-90c1-11e8-9f5e-3da87fcfb8a2.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67895338/Manage+Clients
https://demo.openmf.org/api-docs/apiLive.htm#clients_create

Suggestion related  to this  ticket:
https://github.com/openMF/web-app/issues/80

**Comment by Rishabh106** [comment]
Can I work on this issue?

**Comment by sonali623** [comment]
I would like to work on this.
What I'm I required to do?

**Comment by abhaychawla** [comment]
Go ahead. You are supposed to implement the above screen as present in the community app, in the web app.

**Comment by AashishChakravarty** [comment]
@abhaychawla Is this issue still open?

**Comment by dev-loyde** [comment]
I would like to work on this.

**Comment by dev-loyde** [comment]
@sonali623 are you still on this?
