### ISSUE TITLE
Centers: View Center page (General Tab)

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#218]
Goal:
As a loan officer, I want to see center information as shown here:
https://demo.openmf.org/#/viewcenter/1067
![view center page](https://user-images.githubusercontent.com/23022667/43243323-d6094a88-90c3-11e8-9612-c709554fda04.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67895340/Manage+Centers
https://demo.openmf.org/api-docs/apiLive.htm#centers

**Comment by cabrelkemfang** [comment]
Hello @abhaychawla I will like to work on this issue.

**Comment by abhaychawla** [comment]
Go ahead.

**Comment by karantakalkar** [comment]
@abhaychawla
i have completed my PR for issue #210 , can i work on this please?

**Comment by spider0061** [comment]
@abhaychawla I would like to work on this issue.

**Comment by karantakalkar** [comment]
@spider0061 i have proposed for this issue can you please find another one.. thanks

**Comment by spider0061** [comment]
Okay fine @karantakalkar
