### ISSUE TITLE
Loans: Loan account page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#219]
Goal:
As a loan officer, I want to view client's loan account page as shown here:
https://demo.openmf.org/#/viewloanaccount/2924
![loan account page](https://user-images.githubusercontent.com/23022667/43244597-0f03deb6-90c9-11e8-84ac-c5a9ab422f6c.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/MIFOSX/pages/21069847/Loans
https://demo.openmf.org/api-docs/apiLive.htm#loans

**Comment by jonathanzhang53** [comment]
I'll work on this. I'll try and contribute now and then to this repo by doing more of these list pages like I did during GCI.

**Comment by muskankhedia** [comment]
@abhaychawla I would like to work on this.

**Comment by muskankhedia** [comment]
@abhaychawla I was working on this issue, but I facing a problem, how can I navigate from the clients section with the loans section. I tried for different ways but facing the error `404 not found`. Can you please help me out with this?

**Comment by karantakalkar** [comment]
![Screenshot from 2020-03-06 17-57-23](https://user-images.githubusercontent.com/54709463/76083634-151aba00-5fd4-11ea-9efe-02dc3479ff1e.png)
@muskankhedia 
try this:
- add a child `view-loan-details` here in loans routing module with view loan details component
-  navigate to clients section -> select a client -> scroll down to Loan Accounts Mat table -> upon clicking a row it should navigate to the view loan details component
- got to general tab component HTML in clients module 
![Screenshot from 2020-03-06 18-05-27](https://user-images.githubusercontent.com/54709463/76084167-48aa1400-5fd5-11ea-9277-11a10c497ec5.png)
add router link in matRowdef to route to row.id/view-loan-details

**Comment by muskankhedia** [comment]
@karantakalkar I have tried all that earlier, and the page is also navigating to the particular `/loans/{loanId}` page, but then instead of loading the particular component, its displaying 404 error page. What I think is, it's because of changing the modules, its unable to find the particular route in the application.

**Comment by karantakalkar** [comment]
@muskankhedia hey i guess loans module is not defined in app.module.ts 
![Screenshot from 2020-03-06 18-19-48](https://user-images.githubusercontent.com/54709463/76084988-23b6a080-5fd7-11ea-98ea-dcb6da4f8e89.png)

**Comment by muskankhedia** [comment]
Yaa I have tried that as well earlier. Facing the same problem.

**Comment by karantakalkar** [comment]
@muskankhedia i got to route with this configuration
![Screenshot from 2020-03-06 18-55-54](https://user-images.githubusercontent.com/54709463/76087455-2ebfff80-5fdc-11ea-9923-54fa25920698.png)
![Screenshot from 2020-03-06 18-56-39](https://user-images.githubusercontent.com/54709463/76087537-5e6f0780-5fdc-11ea-960d-f854e27a2643.png)
using same component 
![Screenshot from 2020-03-06 18-57-05](https://user-images.githubusercontent.com/54709463/76087542-6038cb00-5fdc-11ea-9a98-52450cb3ddf3.png)
after declaring loans module
have you declared component in declerations?

**Comment by muskankhedia** [comment]
I had added the path 'loan' and executed 'loan/{loanid}'. Yaa I do have declared the component in the declaration. Checking the code you have written should work for me as well.

**Comment by karantakalkar** [comment]
@muskankhedia check out #384 loans module is meant to be lazy-loaded in clients module that's why there is no declaration in app.module.ts.

**Comment by muskankhedia** [comment]
@karantakalkar Yeah, I have already been through these PRs, and have seen all the changes made till now. And so asked Abhay Sir, what should be the preferable way to implement the loans module as per now.

**Comment by abhaychawla** [comment]
We will be using lazy loading for loans as its common for some parts of the institution section. You can implement lazy loading for testing this component if this is a part of the loans module but remove it while sending the PR. Include the instructions for lazy loading in the description of the PR (similar to what Jivjyot has done) so any person who wants to test has the required information. And please, call me Abhay. No need of sir.

**Comment by muskankhedia** [comment]
Yaa sure. I get the point. Will be implementing as described.
