### ISSUE TITLE
Loans:  Create/Edit loan application page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#220]
Goal:
As a loan officer, I want to create loan application for a client, as shown here:
https://demo.openmf.org/#/editloanaccount/2919
![new loan-modify loan application page](https://user-images.githubusercontent.com/23022667/43244735-730bd2e2-90c9-11e8-971e-944fb8627ff4.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/MIFOSX/pages/21069847/Loans
https://demo.openmf.org/api-docs/apiLive.htm#loans_create

**Comment by abhi40308** [comment]
@abhaychawla I would like to work on this.
