### ISSUE TITLE
Savings: New Savings/edit application page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#222]
Goal:
Savings application is shown here:
https://demo.openmf.org/#/editsavingaccount/2034
![new savings - edit savings application page](https://user-images.githubusercontent.com/23022667/43245150-e4d51720-90ca-11e8-8211-8869a789e7c2.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/MIFOSX/pages/21069845/Savings
https://demo.openmf.org/api-docs/apiLive.htm#savingsaccounts_create

**Comment by pearlMat** [comment]
I will work on this please..

**Comment by abhi40308** [comment]
@abhaychawla  Can you please check and tell the availability of this issue? Looks like @pearlMat  has not raised a pr but have done some work on this.
