### ISSUE TITLE
Shares: Create Share application page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#223]
Goal:
As an account manager, I want to create new share application as shown here:
https://demo.openmf.org/#/editshareaccount/134
![Screenshot from 2020-06-15 19-47-24](https://user-images.githubusercontent.com/54709463/84668282-13508300-af41-11ea-8d7a-247ac7ba4f57.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/MIFOS/pages/4456584/Shares+Module
https://demo.openmf.org/api-docs/apiLive.htm#shareaccounts

**Comment by pearlMat** [comment]
Hi..i would like to work on this issue.

**Comment by pearlMat** [comment]
i will do this please.
