### ISSUE TITLE
Shares: Share account page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#224]
Goal:
Able to view Share account page as shown here:
https://demo.openmf.org/#/viewshareaccount/136
![share account page](https://user-images.githubusercontent.com/23022667/43245457-f8833cb0-90cb-11e8-9313-bfa7b6c6b1f9.png)

- [x]  Transactions Tab

- [x]  Charges Tab

- [x]  Dividends Tab

Resources:
https://mifosforge.jira.com/wiki/spaces/MIFOS/pages/4456584/Shares+Module
https://demo.openmf.org/api-docs/apiLive.htm#shareaccounts

**Comment by aashish-ak** [comment]
@abhaychawla  Interested in working on this one.

**Comment by abhaychawla** [comment]
Go ahead.

**Comment by aashish-ak** [comment]
Hey @abhaychawla , In this, there are buttons which lead to different pages like `Apply Additional Shares` and `Redeem Shares` etc. So do i have to create every single page? or this page should be fine?
