### ISSUE TITLE
Fixed Deposits: FD appication submitted/approval page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#228]
Goal: 
Able to view submitted and approved FD application page as shown here:
https://demo.openmf.org/#/viewfixeddepositaccount/2065
![fd application submitted-approval page](https://user-images.githubusercontent.com/23022667/43246524-81c27de4-90cf-11e8-9a07-0d8a4aba1f8d.png)

Resources:
https://demo.openmf.org/api-docs/apiLive.htm#fdaccounts_approve
https://mifosforge.jira.com/wiki/spaces/docs/pages/73466001/Term+Deposit+Accounts+Fixed+Deposit+Recurring+Deposit

**Comment by Mutahar-Majid** [comment]
Is this issue still open? I would like to work on this.
