### ISSUE TITLE
Loans: Loan application  submitted/approval page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#229]
Goal:
As a loan officer, I  want to view submitted/approved  loan application, as shown here:
https://demo.openmf.org/#/viewloanaccount/2901
![loan application submitted-approval page](https://user-images.githubusercontent.com/23022667/43246761-489ab0a8-90d0-11e8-8188-e6fa43349cc2.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/MIFOS/pages/7700948/Loans
https://demo.openmf.org/api-docs/apiLive.htm#loans_approve

**Comment by muskankhedia** [comment]
Resolved in PR #661 

Duplicate #219
