### ISSUE TITLE
Savings: Savings application submitted/approved page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#230]
Goal:
Able  to view Savings application as shown here:
https://demo.openmf.org/#/viewsavingaccount/1541
![savings application submitteda-approved page](https://user-images.githubusercontent.com/23022667/43246901-be8960e8-90d0-11e8-8dcc-27180a36fbf5.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/MIFOS/pages/4850198/Savings
https://demo.openmf.org/api-docs/apiLive.htm#savingsaccounts_approve

**Comment by vabshere** [comment]
is this issue still open? i would like to work on this

**Comment by vabshere** [comment]
is this issue still open? i would like to work on it

**Comment by abhaychawla** [comment]
Go ahead.

**Comment by karantakalkar** [comment]
Covered by: #221
