### ISSUE TITLE
Reports: List page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#232]
Goal:
As Manager/accountant, I want to view existing reports as shown here;
https://demo.openmf.org/#/reports/all
![reports list page](https://user-images.githubusercontent.com/23022667/43247839-908f56c2-90d3-11e8-81c5-1f4a3cc10e5c.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67141764/Reports
https://demo.openmf.org/api-docs/apiLive.htm#reports_list

**Comment by jonathanzhang53** [comment]
I'll work on this. I'll try and contribute now and then to this repo by doing more of these list pages like I did during GCI.

**Comment by santoshconflux** [comment]
@jonathanzhang53 , Wait.  @abhaychawla will reply to you.

**Comment by abhaychawla** [comment]
@jonathanzhang53, No here also we have a drop-down for the same. About the structure, it would be great if you could implement it in a manner that a single component might be reused for implementation of reports. For breadcrumbs, route params might be helpful in this case.

**Comment by jonathanzhang53** [comment]
Should I look for a way to filter the mat-table based on the reportCategory property or should I make separate API requests that filter the reports? 

I've been looking into angular solutions with mat-table.

**Comment by abhaychawla** [comment]
Try to implement it in the most efficient manner you could find that is possible.

**Comment by karantakalkar** [comment]
Can i work on this?

**Comment by abhaychawla** [comment]
Go ahead.
