### ISSUE TITLE
Reports: Create Report page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#233]
Goal:
As a manager/accountant, I want to view specific report by  providing input paramters as shown here:
https://demo.openmf.org/#/run_report/Active%20Loans%20-%20Summary(Pentaho)?reportId=121&type=Pentaho
![create report page](https://user-images.githubusercontent.com/23022667/43247964-ee7833ee-90d3-11e8-8f97-f5e89af6fdd6.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67141764/Reports
https://demo.openmf.org/api-docs/apiLive.htm#reports_create

**Comment by debenick17** [comment]
If no one has started working on this issue, I will like to work on it

**Comment by abhaychawla** [comment]
Go ahead.

**Comment by debenick17** [comment]
Ok thanks

**Comment by karantakalkar** [comment]
@abhaychawla This is related to my last PR, can i work here?

**Comment by abhaychawla** [comment]
Go ahead.

**Comment by karantakalkar** [comment]
@abhaychawla 

I have a query regarding the source of _select options drop-down data_,

![Screenshot from 2020-01-11 13-21-35](https://user-images.githubusercontent.com/54709463/72201009-c9d1a880-3475-11ea-8560-c80d41af30d0.png)

For eg: the currencies data viewed upon currency dropdown.
I had been looking into Community app code to find the source of dropdown data,

**HTML (Select Options)**

![Screenshot from 2020-01-11 13-32-43](https://user-images.githubusercontent.com/54709463/72201127-ec17f600-3476-11ea-91d2-c63ffc4b3bec.png)

**JavaScript** (`reportParam.selectOptions` assignment)

![Screenshot from 2020-01-11 13-36-05](https://user-images.githubusercontent.com/54709463/72201214-b58eab00-3477-11ea-9635-a96184b19b1e.png)

`reportParam.selectOptions` is getting data from `data` Object of which i can't find the origin.

Reports API provides the parameters ( Office, Currency etc ) but not dropdown data, is there an endpoint for such data?

**References:**

- [https://github.com/openMF/community-app/blob/develop/app/views/reports/run_reports.html](url)

- [https://github.com/openMF/community-app/blob/develop/app/scripts/controllers/reports/RunReportsController.js](url)

- [https://demo.openmf.org/api-docs/apiLive.htm#reports_create](url)

**Comment by karantakalkar** [comment]
@abhaychawla 
Adding run-report functionality for table and chart type required new packages ng-csv, ng2-nvd3, nvd3 and changing d3 version from 4.x to 3.5.17 (as 4.x is incompatible with nvd3), will these changes affect travis builds?, should package.json be included in PR?
