### ISSUE TITLE
Improve status icons colour

### ISSUE THREAD

**Issue by anweshknayak** [openMF/web-app#240]
Make it a bit light or change contrasting color suiting to the material theme

![screenshot_2018-07-28 clients mifos x 2](https://user-images.githubusercontent.com/8139783/43357499-53499e5c-92a0-11e8-9964-8d1c2e95d397.png)

**Comment by Jp138233** [comment]
I will do this.

**Comment by abhaychawla** [comment]
**[Update]** Change red to a lighter shade (orange). Requested by Santosh.
