### ISSUE TITLE
Loans : Loan 'Make Repayment' page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#242]
Goal: 
As a loan officer, I want to collect the repayments from the  client as shown here:
https://demo.openmf.org/#/loanaccount/2957/repayment
![loan repayment page](https://user-images.githubusercontent.com/23022667/43457149-92c36226-94e3-11e8-80de-bc9ae833b98f.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/MIFOSX/pages/21069847/Loans
https://demo.openmf.org/api-docs/apiLive.htm#loans_transaction_repayment

**Comment by Mutahar-Majid** [comment]
Is this issue still open? I would like to work on this.
