### ISSUE TITLE
Loans: 'Prepay Loan' page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#243]
Goal:
As a loan officer, I want to prepay the loan of a client so that I can close it. Check here:
https://demo.openmf.org/#/loanaccount/2957/prepayloan

![loan prepayment page](https://user-images.githubusercontent.com/23022667/43457278-fd5d6e2e-94e3-11e8-9f4e-2a9a5d0203d6.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/MIFOSX/pages/21069847/Loans
https://demo.openmf.org/api-docs/apiLive.htm#loans_transaction_pre_close_loan

**Comment by Mutahar-Majid** [comment]
Is this issue still open? I would like to work on this.
