### ISSUE TITLE
Loans: 'Foreclosure' page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#244]
Goal:
As a loan officer, I want to foreclose the loan as shown  here:
https://demo.openmf.org/#/loanforeclosure/2957

![loan foreclosure page](https://user-images.githubusercontent.com/23022667/43457393-5bc452ca-94e4-11e8-8cd6-e7592ec7e006.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/MIFOSX/pages/21069847/Loans
https://demo.openmf.org/api-docs/apiLive.htm#loans_transaction_foreclosure

**Comment by debenick17** [comment]
@abhaychawla Can I work on this issue?

**Comment by abhaychawla** [comment]
Go ahead.

**Comment by debenick17** [comment]
Okay.
