### ISSUE TITLE
Loans: Create Guarantor page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#246]
Goal:
As a loan officer, I want to create a guarantor for the client. 
https://demo.openmf.org/#/guarantor/2957

![create guarantor page](https://user-images.githubusercontent.com/23022667/43458351-9c6d93a6-94e7-11e8-9898-50048aeccf1b.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/MIFOSX/pages/26574898/Guarantors+For+Loans
https://demo.openmf.org/api-docs/apiLive.htm#loans_recoverguarantee

**Comment by agamvrinos** [comment]
@abhaychawla Is this still available?

**Comment by abhaychawla** [comment]
Yes go ahead. Make sure you follow the guidelines while implementing it.

**Comment by agamvrinos** [comment]
@abhaychawla Sure. Can you tell me the exact steps to go the page where the "create Guarantor" page is being initiated? The provided link goes directly to that page

**Comment by Jov03** [comment]
@agamvrinos In community app:
Clients>clients>select a client>from clients loan accounts select one loan account>under more tab there is option to create loan guarantor

**Comment by agamvrinos** [comment]
@Jov03 Got it thanks. By the way, since the "loan details" page is not yet implemented in the webapp, I am assuming that you want this without the "click button" -> "go to page" functionality, right?

**Comment by abhaychawla** [comment]
Yes for the time being just implement this page.

**Comment by muskankhedia** [comment]
Resolved in PR #1059
