### ISSUE TITLE
Loans: Assign Loan Officer

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#248]
Goal:
As  a Branch  manager, I want to assign loan officer  to particular loan account.
https://demo.openmf.org/#/assignloanofficer/2957
![assign loan officer](https://user-images.githubusercontent.com/23022667/43459003-b9954256-94e9-11e8-87a3-9b241d3ea4ea.png)

Resource:
https://mifosforge.jira.com/wiki/spaces/docs/pages/72909181/How+to+Assign+a+Loan+Officer
https://demo.openmf.org/api-docs/apiLive.htm#loans_assignLoanOfficer

**Comment by aashish-ak** [comment]
Can i work on this issue??

**Comment by aashish-ak** [comment]
@abhaychawla  @santoshconflux Can you guys help me a little in brief about what are the steps that i need to need to do in order to implement this feature, i have already setup the project, i just need a beginner guide to start working on this.

**Comment by abhaychawla** [comment]
@aashish-ak Please read the contributing guidelines and the project's wiki. Take reference from the accounting section and implement this screen in a similar manner.

**Comment by aashish-ak** [comment]
@abhaychawla  For this, https://demo.openmf.org/#/viewloanaccount/3006 , a whole view-loan page needs to be implemented, so do i need to implement that whole page as it'll be really hectic as it contains too many functionalities and this issue will no longer be considered as `good first issue`, also if i need to implement that then can you mention any specific features that need to be implemented first, so i can have a headstart, i'll start working on it immediately.

**Comment by abhaychawla** [comment]
That is a separate issue. If you are working on this issue, then you are just supposed to implement the form to assign a loan officer.

**Comment by geeksaurav** [comment]
Why is this still open? And added in Goog first issue?
