### ISSUE TITLE
Savings: Transfer Fund Page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#251]
Goal:
Ability to transfer balance in one savings account to another savings account as shown here:
https://demo.openmf.org/#/accounttransfers/fromsavings/2051

![savings transfer fund page](https://user-images.githubusercontent.com/23022667/43459438-18e03b52-94eb-11e8-9b41-6d87b228b18e.png)

Resources;
https://mifosforge.jira.com/wiki/spaces/MIFOS/pages/73466208/Savings+Accounts
https://demo.openmf.org/api-docs/apiLive.htm#savingsaccounts_transactions

**Comment by CajetanRodrigues** [comment]
Can you elaborate more on what exactly is required?

**Comment by abhaychawla** [comment]
The screen is also supposed to be implemented. Make sure you try to claim a single issue at a time only and leave the others open. You may go ahead with the other issue as you asked to work it. Leave this one for the time being.
