### ISSUE TITLE
Collection Sheet

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#253]
Goal:
As a loan officer, I want to make entries and submit collection sheeet.
https://demo.openmf.org/#/entercollectionsheet
![collection sheet page](https://user-images.githubusercontent.com/23022667/43502634-6ede4b96-9579-11e8-90ab-49c81ba075e8.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/112296012/Collection+sheet
https://demo.openmf.org/api-docs/apiLive.htm#centers_generate_collectionsheet

**Comment by ramvr1256** [comment]
APIs are not giving 500 internal server error in the default.ps.mifos.io.  So not able to understand and replicate the functionality completely.

**Comment by bharathcgowda** [comment]
@anika-001  can you please analyse this issue?

**Comment by anika-001** [comment]
Yes, working on the issue.
