### ISSUE TITLE
Productive Collection Sheet

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#254]
Goal:
As a loan officer, I want to submit collection sheet for whole center.
https://demo.openmf.org/#/productivesheet/1/Head%20Office/01%20August%202018/170
![productive collection sheet page](https://user-images.githubusercontent.com/23022667/43502748-f3755fca-9579-11e8-9599-b5279d2ac06d.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/112296012/Collection+sheet
https://demo.openmf.org/api-docs/apiLive.htm#centers

**Comment by ramvr1256** [comment]
APIs are not giving 500 internal server error in the default.ps.mifos.io.  So not able to understand and replicate the functionality completely.

**Comment by bharathcgowda** [comment]
@anika-001  can you please analyse this issue?
