### ISSUE TITLE
Individual Collection Sheet

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#255]
Goal: As a loan officer, I want to make entries for individual collection sheet and submit it.
https://demo.openmf.org/#/individualcollectionsheet
![individual collection sheet page](https://user-images.githubusercontent.com/23022667/43502831-4e983bf2-957a-11e8-850b-7b2c939c4103.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/112296014/Individual+collection+sheet
https://demo.openmf.org/api-docs/apiLive.htm#save_individual_collection_sheet

**Comment by pearlMat** [comment]
I would like to work on this issue please..
