### ISSUE TITLE
Navigation Page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#256]
Goal:
As an  admin or branch manager I want to navigate from office level, to loan officers, centers, groups and clients.
https://demo.openmf.org/#/nav/offices
![navigation page](https://user-images.githubusercontent.com/23022667/43502937-b2750196-957a-11e8-9631-aaedad834e1d.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/112296008/Navigation

**Comment by love-opensource** [comment]
Hi! I want to work on this.

**Comment by abhaychawla** [comment]
@love-opensource Do not comment and try to claim multiple issues at once. You can work on a single issue at a time only. I will not allow this.

**Comment by chirag-singhal** [comment]
@abhaychawla Can i work on this issue?

**Comment by abhaychawla** [comment]
Go ahead.
