### ISSUE TITLE
Configure keyboard shortcuts and design user interface to view them

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#257]
Goal:
Configure the keyboard shortcuts for easier accessibility and provide the ability to view all the shortcuts for Mifos Web App.
https://demo.openmf.org/#/help
![help](https://user-images.githubusercontent.com/23022667/43503092-6943d4ec-957b-11e8-951f-5fc4300bf802.png)

**Comment by karantakalkar** [comment]
@abhaychawla  I will be working here.
