### ISSUE TITLE
Clients: Add new address

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#259]
Goal:
As a loan officer, I want to add new address for the client as shown here:
https://demo.openmf.org/#/address/5
![add address page](https://user-images.githubusercontent.com/23022667/43507093-c5a87680-9589-11e8-880e-676f501166d2.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67895338/Manage+Clients
https://demo.openmf.org/api-docs/apiLive.htm#client_address_create

**Comment by noaht97** [comment]
With the web app as it is right now, you are able to create and save new addresses from the view client page underneath the addresses tab. It seems like what this issue is describing is functional, so what specifically is this issue looking to address that is not already implemented?

**Comment by santoshconflux** [comment]
@noaht97 , One is 'Country' field is missing (after City Field). However, here we are thinking about redesigning our current front end 'Community App' with new looks and feels, ease of use, etc rather than addressing specific issue. 

@abhaychawla , you want to add more?

**Comment by abhaychawla** [comment]
@noaht97 Currently the wizard view has been applied in the address section, which needs to be removed. The UI needs to be updated keeping consistency with the accounting section components. Also as Santosh said, a field to specify Country needs to be added. And the functionality needs to be updated as well by using reactive forms, breadcrumbs, http module to leverage the interceptors to send requests etc. to ensure its consistency.

**Comment by noaht97** [comment]
@abhaychawla @santoshconflux Ah I see, thank you for clarifying!

**Comment by phella** [comment]
is this issue still open ?

**Comment by abhaychawla** [comment]
Yeah, go ahead.

**Comment by phella** [comment]
@abhaychawla  the form is already found http://localhost:4200/clients/address/1 
what should I update on it ?
