### ISSUE TITLE
Clients: Identities page

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#261]
Goal:
Ability  to view existing identities for the client. 
https://demo.openmf.org/#/viewclient/5

![identities page](https://user-images.githubusercontent.com/23022667/43508233-fafe71d8-958c-11e8-9679-af108edbb813.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67895338/Manage+Clients
https://demo.openmf.org/api-docs/apiLive.htm#client_identifiers_list

**Comment by aashish-ak** [comment]
Hey @abhaychawla @santoshconflux , This feature has already been implemented and working fine, i was succesfully able to create identity and view it in the Identities tab, though the breadcrumb was missing but the feature is working fine, can you tell me if there's anything left in this that i can work on?

**Comment by aashish-ak** [comment]
Same is the case with #260
