### ISSUE TITLE
Clients: Upload document page (client and loan) 

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#265]
Goal:
As a loan officer, I want to upload documents for the client. Similarly loan as well.  
https://demo.openmf.org/#/addclientdocument/5
![upload document page](https://user-images.githubusercontent.com/23022667/43522872-3d5aa3c8-95b8-11e8-9d59-e5e9eff515da.png)

Resources:
https://demo.openmf.org/api-docs/apiLive.htm#documents_create
https://mifosforge.jira.com/wiki/spaces/docs/pages/67895338/Manage+Clients

**Comment by An0u** [comment]
Has this been resolved? If not I'd like to take it up

**Comment by abhaychawla** [comment]
Go ahead.

**Comment by An0u** [comment]
@abhaychawla Is the task to implement the above in the web-app as shown in the demo? I'm unclear

**Comment by abhaychawla** [comment]
Yes, it needs to be implemented in the web-app. Please read the readme, contribution guidelines and the wiki before you start working.
