### ISSUE TITLE
Clients: view standing instruction 

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#267]
Goal:
As a loan officer, I want to view standing instruction of a client  as shown here:
https://demo.openmf.org/#/liststandinginstructions/2/5

![view standing instruction](https://user-images.githubusercontent.com/23022667/43577484-9564d352-9669-11e8-830f-9a133f02b0d3.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/73465884/Standing+Instructions
https://demo.openmf.org/api-docs/apiLive.htm#standinginstruction

**Comment by kerlynNkep** [comment]
Hello @abhaychawla  ill work on this issue instead.

**Comment by abhaychawla** [comment]
Go ahead!
