### ISSUE TITLE
Clients : Create Standing Instruction

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#268]
Goal:
As a loan officer , I want to create standing instruction as shown here:
https://demo.openmf.org/#/createstandinginstruction/2/5/fromsavings
![create standing instruction](https://user-images.githubusercontent.com/23022667/43577611-ef2c4938-9669-11e8-9015-74d5633e4c82.png)

Resources:
https://demo.openmf.org/api-docs/apiLive.htm#standinginstruction_create
https://mifosforge.jira.com/wiki/spaces/docs/pages/73465884/Standing+Instructions

**Comment by IgorWilbert** [comment]
Hey! Currently there is a lot of open issues. May I start with this one?

**Comment by santoshconflux** [comment]
@IgorWilbert , Sure. Any help needed , let me know.

**Comment by IgorWilbert** [comment]
@santoshconflux I code the component of the page, but I don't know how to access the page. I think I need to modify clients-routing.module.ts, clients.module.ts and clients.service.ts, but I don't know how to do that in Angular. Please, help me.
