### ISSUE TITLE
Clients: Take a Survey 

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#269]
Goal: 
As a loan officer, I want to take survey  for the client as shown here:
https://demo.openmf.org/#/survey/5
![take a survey page](https://user-images.githubusercontent.com/23022667/43577845-ae145da4-966a-11e8-9864-8ea92789212c.png)

Resources:
https://demo.openmf.org/api-docs/apiLive.htm#survey_create
https://mifosforge.jira.com/wiki/spaces/MIFOS/pages/73466240/Surveys

**Comment by yousefsaif** [comment]
Currently, there are a lot of open issues (133). Do you recommend I start with this one?

**Comment by abhaychawla** [comment]
Yes, you may start. But make sure that you follow the contributing guidelines. And also, features implemented in clients contain some old code which needs to be updated. Please see the accounting section for reference and implement this page accordingly.

**Comment by lkttyagi** [comment]
@abhaychawla  i think this issue is still open can i start working on it ?

**Comment by mbj36** [comment]
@lkttyagi You can start working on it.

**Comment by abhaychawla** [comment]
@Ikttyagi make sure the code is implemented according to the guidelines followed in accounting section as most of the code in clients section is obsolete. Ensure you only make changes necessary for this component.

**Comment by lkttyagi** [comment]
@abhaychawla  i have changed the client section according to guidelines followed in accounting section now i need to create survey component .can you help me with it?
![Screenshot from 2019-04-04 10-04-11](https://user-images.githubusercontent.com/14857566/55529924-59655200-56c1-11e9-853b-508095c1e780.png)

**Comment by abhaychawla** [comment]
This is not what you were supposed to do at all. You are only required to make changes in code to implement the component specific to the issue.

**Comment by lkttyagi** [comment]
@abhaychawla so I have to add a survey sub-component in view-client component only ?

**Comment by abhaychawla** [comment]
Yes. Take reference and see how its implemented in the community app and rewrite it with respect to the newer version.

**Comment by lkttyagi** [comment]
@abhaychawla Sir sorry for the mess but i changed the code as you said and its almost completed
I am able to get surveyname from API but unable to fetch question and response according to surveyname
can you help me with it ?

**Comment by abhaychawla** [comment]
@muskankhedia please comment on the issue before you start working on it.

**Comment by muskankhedia** [comment]
Yaa sure. Will surely keep that in mind.
