### ISSUE TITLE
Resources about this project

### ISSUE THREAD

**Issue by TheDApact** [openMF/web-app#299]
Hi, where can I find some context about the development of web-app and how it relates to the community-app?

**Comment by abhaychawla** [comment]
@TheDApact The web-app based on Angular 6 is a revamped version of the community-app which is based on AngularJS. You can read the project's readme, contributing guidelines and wiki.

If you have any queries, please post on our gitter channel or the mailing list. The issue thread is for reporting bugs or feature requests.

**Comment by TheDApact** [comment]
oops sorry about that and thanks!
