### ISSUE TITLE
Implement List View: Organisation

### ISSUE THREAD

**Issue by abhaychawla** [openMF/web-app#323]
**Goal:**

Implement the list view screen for Admin -> Organisation section.

https://demo.openmf.org/#/organization

![screenshot 359](https://user-images.githubusercontent.com/16948598/48671011-e317e700-eb47-11e8-817f-4974aff9a3a2.png)

**Comment by IgorWilbert** [comment]
This seems to be simple, I will give it a try. If anyone else wants to work on it, just comment.

**Comment by abhaychawla** [comment]
@IgorWilbert There is already an existing PR for this.

**Comment by vatsal3333** [comment]
Can I work on this?

**Comment by abhaychawla** [comment]
As I have already specified above there is an existing PR for this.

**Comment by sivakumarpalivela** [comment]
Is this issue free to work ?

**Comment by abhaychawla** [comment]
No.
