### ISSUE TITLE
Implement List View: Products

### ISSUE THREAD

**Issue by abhaychawla** [openMF/web-app#328]
**Goal:**

Implement the list view screen for Admin -> Products section.

https://demo.openmf.org/#/products

![screenshot 360](https://user-images.githubusercontent.com/16948598/48674067-68ae8d80-eb6e-11e8-8209-9eb9b1d14c75.png)

**Comment by jonathanzhang53** [comment]
@abhaychawla I asked a question on the GCI Task instance, but I will restate here:

I am having issue with loading in the products module with the app.module.ts file. My repository is linked below with branch 'productsmodule' being the one I am working on. When I run ng serve after adding in the import in app.module.ts, the client is stuck on the initial loading screen. I have done all of the files in products folder identical to accounting except for accounting specific elements.

https://github.com/jonathanzhang53/web-app/tree/productsmodule

I have closely followed the format of accounting module, but I am not sure where I am going wrong. I get an error which I am attaching as an image.

![error](https://user-images.githubusercontent.com/41968151/49194881-6f958700-f34a-11e8-9851-cd76f025380a.PNG)

**Comment by jonathanzhang53** [comment]
Additional Information: I have added the route to the toolbar component. Also, when I remove my changes to the app.module.ts file, the client runs fine but obviously my products list is not going to be valid (leads to 404 since never imported as module).

I think this may have something to do with the way I imported?

**Comment by abhaychawla** [comment]
@jonathanzhang53 As mentioned in the wiki here: https://github.com/openMF/web-app/wiki/Generate-a-Module, you need to import the shared module within the products module as well, so that you can use the  AngularMaterial components, Angular Font Awesome Icons and FlexLayout directives. Also, ensure that all icons you are using are imported and added to library within the `icons.module.ts` file in alphabetical order.

**Comment by abhaychawla** [comment]
Fixed via https://github.com/openMF/web-app/commit/4f1dbc582128ac02ca507d84bda60844a28475e9
