### ISSUE TITLE
Organisation Spelling to American Organization

### ISSUE THREAD

**Issue by jonathanzhang53** [openMF/web-app#330]
## Description
American English spelling is 'organization'. This may be a better fit for the app.

## Steps to Reproduce
Log into web app.
Under admin menu on the top tool bar, select and look at `organisation` title.

## Expected Behaviour
'organization'

## Actual Behaviour
'organisation'

## Screenshots, if any
![image](https://user-images.githubusercontent.com/41968151/49170652-3c2f0a00-f302-11e8-9e80-c101ba74d13c.png)

**Comment by IgorWilbert** [comment]
@jonathanzhang53 "organisation" is actually grammatically correct too. But if @abhaychawla agrees about this PR, I suggest you to change this word in the Accounting -> Charts of Accounts -> List of accounts used by the **organisation**  page in the same PR.
