### ISSUE TITLE
Incorrect Documentation in Products Directory

### ISSUE THREAD

**Issue by jonathanzhang53** [openMF/web-app#348]
## Description
incorrect documentation of function params in products.service.ts and products.routing.module.ts

## Steps to Reproduce
Go to src/app/products/products.service.ts
Go to src/app/products/products.routing.module.ts

## Expected Behaviour
No params in service file
Product mix resolver and component under wrong comments in routing file

## Actual Behaviour
Says that there are 'any' params
Product mix resolver and component should be under their respective comments

## Settings
Not Applicable

## Screenshots, if any
Not Applicable

**Comment by jonathanzhang53** [comment]
I'll fix this once #347 is merged.

**Comment by abhaychawla** [comment]
Follow the format of one of the issue templates when you create an issue.
