### ISSUE TITLE
Add the Global translations.

### ISSUE THREAD

**Issue by aashish-ak** [openMF/web-app#351]
**Is your feature request related to a problem? Please describe.**
- The community-app has the global translations feature but the web-app doesn't.

**Describe the solution you'd like**
- The app should display names according to their locale like "Navigation Page" for english locale and "Página de navegación" for espanol locale.

**Describe alternatives you've considered**
 - `locale-lang.json` should be used.

**Comment by abhaychawla** [comment]
@aashish-ak How translations will be implemented within the web-app is still a matter of ongoing discussion with the other mentors, so I am closing this issue. A separate issue will be created and this will be implemented later.
