### ISSUE TITLE
So is this a rewrite version? Do you guys have plan to make it on a blockchain?

### ISSUE THREAD

**Issue by walter211** [openMF/web-app#356]
**Is your feature request related to a problem? Please describe.**
Just want to ask how to move it on a blockchain easily

**Describe the solution you'd like**
Give a doc

**Describe alternatives you've considered**
make a demo

**Additional context**
none

**Comment by abhaychawla** [comment]
@walter211 Do not open issues for general support questions as we want to keep GitHub issues for bug reports and feature requests only. If you have got any questions, please email to our mailing list (https://sourceforge.net/projects/mifos/lists/mifos-developer). Currently, the focus is on revamping of the existing functionalities of the community app with some new additions. There isn't any plan as of now to shift it on a blockchain. If you have any suggestions/queries please email on the mailing list.
