### ISSUE TITLE
Unable to scroll on left navigation bar

### ISSUE THREAD

**Issue by jonathanzhang53** [openMF/web-app#358]
## Description
The expanded left navigation bar does not have scroll capability, and some content is hidden.

## Steps to Reproduce
Launch mifos web-app.
Log in. 
Click the right chevron at the top left to expand the nav bar.
Try to scroll.

## Expected Behaviour
You should be able to scroll in order to see all the rows in the nav bar

## Actual Behaviour
Some content is hidden because you cannot scroll

## Settings
- Mifos X version: Version 0.0.0-dev
- Browser used: Chrome

## Screenshots, if any
![image](https://user-images.githubusercontent.com/41968151/50524449-50019380-0a9b-11e9-9040-3b8ed4ea62c9.png)

**Comment by Jov03** [comment]
@jonathanzhang53 I would like to take up this issue if not already taken.

**Comment by abhaychawla** [comment]
Go ahead @Jov03!

**Comment by Jov03** [comment]
@abhaychawla thanks
