### ISSUE TITLE
Option selection covers information field

### ISSUE THREAD

**Issue by IgorWilbert** [openMF/web-app#359]
## Description
The selection pop-up covers the text field with the description of the information being selected. 

## Steps to Reproduce
- Launch mifos web-app;
- Log in;
- Navigate to the Accounting section;
- Navigate to any of the following subsections:
Frequent Postings;
Create Journal Entries;
Migrate Opening Balances;
- Try to select an option from any of the option fields (can be identified through an upside down on the rightmost corner);

## Expected Behaviour
The option selection pop-up should avoid the field with text, as can be seen in the Closing Entries section.

## Actual Behaviour
The option selection pop-up almost completely covers the field with text. This not only gives a bad look, but affects accessibility if the user forgets what he/she is selecting.

## Settings
- Mifos X version: Version 0.0.0-dev
- Browser used: Firefox

## Screenshots, if any
- Expected Behavior:
![right](https://user-images.githubusercontent.com/42987854/50540457-3171ca00-0b79-11e9-80c1-f8d496c78d37.JPG)
- Actual Behavior:
![wrong](https://user-images.githubusercontent.com/42987854/50540461-3898d800-0b79-11e9-8d7b-9460b7768747.JPG)

**Comment by abhaychawla** [comment]
@IgorWilbert Angular Material provides default behavior for these components based on the official material guidelines. Both components as you have shown here in the screenshot are different. mat-input is being used for providing an autocomplete option where the user can write as well where it is required, while mat-select is being used elsewhere. The native HTML select won't provide the same material look and feel if replaced. This doesn't seem a valid issue.

**Comment by IgorWilbert** [comment]
@abhaychawla you are right, thank you for pointing this out, and sorry for creating it. I shall close this issue then, but first could you please explain it a little better? Don't you consider the replacement of mat-select with mat-input an enhancement as the autocomplete could be useful in some cases? If not, is there any other way of changing the behaviour of mat-select so that it doesn't cover the text, or even use a different component? I really thought this could be a valid issue, because with mat-datepicker, for example, the calendar doesn't cover the text.

**Comment by abhaychawla** [comment]
There is already an ongoing issue and request for creating a search filter within the mat-select in the official angular material repository. Unless necessary we won't be replacing it right now as it is not a priority, rather wait for an official update.
