### ISSUE TITLE
Smaller window size hides top nav bar options

### ISSUE THREAD

**Issue by jonathanzhang53** [openMF/web-app#360]
## Description
Smaller window size hides top nav bar options

## Steps to Reproduce
Launch mifos web app and login
Reduce window size until the top nav bar buttons disappear and only `Institution` is visible.

## Expected Behaviour
There is some dropdown alternative to access the top nav bar options such as on community-app.
![mifosminimizebug](https://user-images.githubusercontent.com/41968151/50544407-cac0d080-0bb9-11e9-920a-be8e3be97355.gif)

## Actual Behaviour
Only `Institution` is shown and there is no way to fetch the other menu options
![image](https://user-images.githubusercontent.com/41968151/50544398-87666200-0bb9-11e9-8aa5-fadb2f842e7e.png)

## Settings
- Mifos X version: 
- Browser used: Chrome

## Screenshots, if any
See above

**Comment by abhaychawla** [comment]
@jonathanzhang53 Please investigate properly before creating an issue. In smaller screens, all the options are merged under a single heading institution. Did you check?

Invalid issue.

**Comment by jonathanzhang53** [comment]
@abhaychawla Sorry I didn't check because I didn't think everything would go under `Institution` and that the original `Institution` options would be there.
