### ISSUE TITLE
Font Awesome Error in browser console on opening the Groups component.

### ISSUE THREAD

**Issue by aashish-ak** [openMF/web-app#361]
## Description
The browser console throws 
```
GET http://localhost:4200/fontawesome-webfont.woff2?v=4.7.0 net::ERR_ABORTED 404 (Not Found)
```
this error on opening the groups component in the app.

## Steps to Reproduce
Just open the Groups component from the `Institution` tab and open the browser console using `Control + Shift +I` .

## Settings
- Mifos X version: 0.0.0-dev
- Browser used: Google Chrome

## Screenshots, if any
![bug](https://user-images.githubusercontent.com/21988675/50545335-0305f480-0c36-11e9-942e-76804a0b0803.png)

## Way to Remove the error
Just comment line 32 i.e `<i class="fa fa-circle fa-2x"> </i>` in the `groups.component.html` file to remove the error.
![fa](https://user-images.githubusercontent.com/21988675/50545342-5d06ba00-0c36-11e9-98f0-08f4bc829c09.png)

**Comment by abhaychawla** [comment]
This seems to be a network issue on your system. Anyway, there is an exiting issue and PR to update the icons to font awesome angular icons. https://github.com/openMF/web-app/issues/138 The clients, groups and centers section has obsolete code for which also there is already an existing issue.
