### ISSUE TITLE
Error in displaying dateOfBirth attribute in the client section for some clients. 

### ISSUE THREAD

**Issue by aashish-ak** [openMF/web-app#363]
## Description
In the Clients section, when you open some of the clients like `Susan Wanjiru` , `test verify`, `Pauline Wambui Chege` etc. the app throws `ERROR TypeError: Cannot read property 'reverse' of undefined` 
 error in browser console as these clients don't have their dateOfBirth stored in the database. 
## Steps to Reproduce
Open the Clients section in the `Institution` tab and then open the client `Susan Wanjiru` or `test verify` or `Pauline Wambui Chege` etc., then open the browser developer tools console using `Control + Shift + I` . You'll see the error there.

## Cause of Error
This line `this.clientInfo.dateOfBirth = this.clientInfo.dateOfBirth.reverse().join('-');` in `view-client.component.ts` should have a check whether the property `dateOfBirth` exists or not. 

## Settings
- Mifos X version: 0.0.0-dev
- Browser used: Google Chrome

## Screenshots, if any
![client9](https://user-images.githubusercontent.com/21988675/50574128-fcc77200-0e07-11e9-88fe-8d6d25429208.png)

**Comment by abhaychawla** [comment]
Part of https://github.com/openMF/web-app/issues/213. As specified in the wiki any kind of date should just be displayed for now without formatting https://github.com/openMF/web-app/wiki/Date-and-Language till the implementation is finalized.

**Comment by ridhishjain** [comment]
@abhaychawla is this issue still open or resolved in gsoc 2019?

**Comment by thesmallstar** [comment]
can I work on this? @aashish-ak

**Comment by mittulmandhan** [comment]
@abhaychawla This issue should be closed because the view-client component is revamped and this issue no longer exists.

**Comment by asraman9792** [comment]
sir is this issue open please let me know if i can contribute some

**Comment by karantakalkar** [comment]
Clients section has been revamped
