### ISSUE TITLE
Cancel button is not working in reschedule loan.

### ISSUE THREAD

**Issue by Rupeshiya** [openMF/web-app#364]
## Description
On doing cancellation of approval ,It's not doing anything

## Steps to Reproduce
Go to https://demo.openmf.org/#/tasks --> Reschedule Loan -->approve -->cancel

## Expected Behaviour
Cancel button should cancel the approval.
## Actual Behaviour
It's not cancelling the approval .

**Comment by Rupeshiya** [comment]
I would like to fix this. @edcable

**Comment by abhaychawla** [comment]
@Rupeshiya The community app is hosted at https://demo.openmf.org not the web app. Please create the issue in the correct repository if you are able to reproduce it locally.

**Comment by Rupeshiya** [comment]
@abhaychawla  In #132 description this link was given so I thought that it is for web app and there I found this issue .
