### ISSUE TITLE
Sidebar  options are not visible in two modes as described in the screenshot.

### ISSUE THREAD

**Issue by Rupeshiya** [openMF/web-app#366]
## Description
All the options of the sidebar should be visible.

## Steps to Reproduce
Go to https://openmf.github.io/web-app/home and choose colour schemes icon from navbar on right and then choose the last bottom two colour. 

## Expected Behaviour
 Options of the sidebar should be visible.
## Actual Behaviour
 Options of the sidebar not visible.
## Settings
- Mifos X version: 0.0.0
- Browser used: Chrome

## Screenshots, if any
![screenshot 94 _li](https://user-images.githubusercontent.com/31209617/51085015-40e83a00-1759-11e9-94e3-34743012a4ce.jpg)

**Comment by Jov03** [comment]
@Rupeshiya I would like to work on this issue if its not already taken.

**Comment by Rupeshiya** [comment]
What do you think @abhaychawla , should he start the work ?

**Comment by abhaychawla** [comment]
@Jov03 Go ahead. The web app has been developed in a way to allow for custom theme configuration, for which the first two themes are inspired by the logo of Mifos while the other four include the ones provided by angular-material by default. The options are not visible when we are working with the last two themes provided by angular-material which are dark. Appropriate customization needs to be made for the sidebar theme to make those option visible in case the theme is dark.

**Comment by abhaychawla** [comment]
@Rupeshiya Could you please update the description properly to reflect the version and browser you used. Also, edit the steps to reproduce with the actual steps to be followed to encounter this issue not `Have a look at the screen shot.`.
