### ISSUE TITLE
Progressive Web App Features 

### ISSUE THREAD

**Issue by Rupeshiya** [openMF/web-app#367]
**Is your feature request related to a problem? Please describe.**
No, This feature will be much helpful for the user since they can use the web app as a native app.
1. Make app installable
2. Make it send push notification.
3. Should also work offline due to some caching strategy
4. Implement Background sync, so that if anyone tries to create something and there is an internet problem so in that case that will be created after getting good internet connection automatically.

**Additional context**
Have a look at the chrome lighthouse audit for PWA.
![screenshot 95](https://user-images.githubusercontent.com/31209617/51085676-b278b600-1762-11e9-8c14-b5e172d86b34.png)

**Comment by Rupeshiya** [comment]
@abhaychawla  should I work on this ?

**Comment by abhaychawla** [comment]
Please update to provide a detailed description following the complete format for feature request issue template.

**Comment by Rupeshiya** [comment]
Updated @abhaychawla
