### ISSUE TITLE
No Description for some global configurations

### ISSUE THREAD

**Issue by luckyman20** [openMF/web-app#372]
## Description
There is no description for some global configurations in back-end so as a result we are also not having those descriptions as we are fetching descriptions from back-end only.

## Steps to Reproduce
Home -> System -> Configurations

I have opened [ticket](https://issues.apache.org/jira/browse/FINERACT-693) in Fineract for same.

**Comment by abhaychawla** [comment]
@luckyman20 Please update this issue to follow the complete template for the bug report.

**Comment by luckyman20** [comment]
This issue has been resolved and can be tested through `staging` server.

**Comment by abhaychawla** [comment]
That is fine, just update the description according to the template.
