### ISSUE TITLE
Error in  Frequent posting in accounting 

### ISSUE THREAD

**Issue by sanketco** [openMF/web-app#375]
## Description
404 error in  frequent posting 
Provide a brief overview of the enhancement or issue.

## Steps to Reproduce
Please add as much detail as possible to reproduce the error/issue.
Don't assume the reader knows anything about the Mifos X Web App.

## Settings
- Mifos X version: 
- Browser used: 

## Screenshots, if any
![screenshot 38](https://user-images.githubusercontent.com/39990230/51982211-5381a380-24bb-11e9-865b-e331c2e74776.png)

**Comment by abhaychawla** [comment]
@sanketco When you create an issue please specify a proper description and fill in all the details. The url to access frequent postings is `accounting/journal-entries/frequent-postings`.
