### ISSUE TITLE
Client-Submitted Loan or Savings Account Application - Front-end

### ISSUE THREAD

**Issue by tkngambi** [openMF/web-app#378]
**Is your feature request related to a problem? Please describe.**
I am frustrated because as a non-technical user, I would like a simpler way to capture loan applications from a web form from prospective clients.

**Describe the solution you'd like**
I am wondering if it is possible to introduce a "front-end" view that can be embedded on a website which allows prospective Clients to submit their Savings or Loan applications to be captured directly into the system as pending Applications. 

**Describe alternatives you've considered**
I have considered hiring a web developer to create this system for me via API on Mifos X platform, but it seems complex. I am hoping this will be simpler with this web app.

**Additional context**

**Comment by Jov03** [comment]
@tkngambi already an issue is open for the work you are suggesting. Web-App is re-write of community-app which implements your required features. Web-App would have these features but currently they are in development phase. You can use community app for now.

https://github.com/openMF/web-app/projects/2 : as you can see here tasks for saving and loans module are in the To-Do list already.

**Comment by abhaychawla** [comment]
@Jov03 Thanks for pointing that out. Will close this issue.
