### ISSUE TITLE
View/Edit/Delete Codes

### ISSUE THREAD

**Issue by abhaychawla** [openMF/web-app#379]
**Goal:**
As a system admin, I want to view, edit and delete codes as seen at:
https://staging.openmf.org/#/viewcode/29
![View Code](https://user-images.githubusercontent.com/16948598/58097919-1706be80-7bf6-11e9-97f1-5b84522f2cd0.PNG)
![Delete Code](https://user-images.githubusercontent.com/16948598/58097986-3f8eb880-7bf6-11e9-96e1-66b7a3ddd27f.PNG)
![Edit Code](https://user-images.githubusercontent.com/16948598/58098101-71078400-7bf6-11e9-8253-8029f82b9d48.PNG)
https://staging.openmf.org/#/editcode/46
![Add code value](https://user-images.githubusercontent.com/16948598/58098118-7a90ec00-7bf6-11e9-8b61-02d5111f38b6.PNG)

**Comment by luckyman20** [comment]
@abhaychawla I would like to work on this issue.
