### ISSUE TITLE
Spaces between columns

### ISSUE THREAD

**Issue by areeshatariq** [openMF/web-app#394]
## Description
In Journal Entries | Home / Accounting / Journal Entries : The space between the columns is not consistent. The last three columns have very less space while others have more.

## Steps to Reproduce
Open Home page, 
Go to the Accounting tab 
Click "Search Journal Entries"

## Expected Behaviour
Consistent Spaces between the columns

## Actual Behaviour
Inconsistent spaces making last 3 columns less readable

## Settings
- Browser used: Chrome

## Screenshots
![ColumnSpaces](https://user-images.githubusercontent.com/24654457/55277987-3127cd00-5328-11e9-9dab-4925a259e960.JPG)

**Comment by abhaychawla** [comment]
This is not a valid issue, the amount of space taken up by a column will depend on the length of the data.
