### ISSUE TITLE
Alignment of Column Title

### ISSUE THREAD

**Issue by areeshatariq** [openMF/web-app#395]
## Description
Alignment of the title of column "Account Code" is not left aligned while all the other titles are left aligned

## Steps to Reproduce
Go to the home page
Click "Accounting" tab
Click "Search Journal Entries"

## Expected Behaviour
Column title "Account Code" is left aligned

## Actual Behaviour
Column title "Account Code" is justified

## Settings 
- Browser used: Chrome

## Screenshots
![image](https://user-images.githubusercontent.com/24654457/55278520-2b81b580-532f-11e9-98b7-592cd427f771.png)

**Comment by abhaychawla** [comment]
I am not able to reproduce this. Please recheck. Even if this is happening this is an issue with angular material's table component and not an issue of the web-app. Its just being implemented here.
