### ISSUE TITLE
Create client link missing

### ISSUE THREAD

**Issue by tcbuzor** [openMF/web-app#433]
## Description
Provide a brief overview of the enhancement or issue.
There is no link to create a client.

## Steps to Reproduce
Install web-app and click on institution->client
A list of existing clients are displayed but there is no link to create new client.

## Expected Behaviour
There should be a link to create a client
## Actual Behaviour
Unable to create new client
## Settings
- Mifos X version: web-app 
- Browser used: 
Firefox, Chrome and safari

**Comment by Jov03** [comment]
@tcbuzor the app in under development there is an existing issue #215 for create and edit clients.
