### ISSUE TITLE
Clients: User should be able to search list of clients in clients list page

### ISSUE THREAD

**Issue by Jov03** [openMF/web-app#445]
Goal:
User should able to search the list of clients

![image](https://user-images.githubusercontent.com/15383669/61574627-e05b0080-aadf-11e9-95d7-60308a9a9c46.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67895338/Manage+Clients
https://demo.openmf.org/api-docs/apiLive.htm#clients

**Comment by muskankhedia** [comment]
@Jov03 I'd like to take this up. By the screenshot provided do you mean the search option as in community-app should be implemented in web-app.

**Comment by abhaychawla** [comment]
@muskankhedia Yes that's right. But as of now, the Clients section was revamped during GSoC.  The work done during GSoC is in a separate branch which is currently in the process of being merged with master. And also, some parts of the search feature are currently being discussed for this section in the mailing list before they can be implemented. Till that is finalized, feel free to take up any other issue.

**Comment by sonali623** [comment]
Is this issue still open? I would like to work on it.

**Comment by muskankhedia** [comment]
@sonali623 I have already worked on this issue. Can you please take up any other for now?

**Comment by asraman9792** [comment]
sir is this issue open please let me know if i can contribute some

**Comment by BLasan** [comment]
@abhaychawla  Can I work on this?
