### ISSUE TITLE
View Fixed Deposit Product

### ISSUE THREAD

**Issue by abhaychawla** [openMF/web-app#465]
**Goal:**
As a branch manager, I want to view a fixed deposit product, as seen at,

https://demo.openmf.org/#/viewfixeddepositproduct/95

![view fd product](https://user-images.githubusercontent.com/16948598/62408529-220f9f00-b5e8-11e9-9294-84c07f81c808.PNG)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/102629544/Fixed+Deposit+Products
https://demo.openmf.org/api-docs/apiLive.htm#fdproducts_retrieve

**Comment by zerefwayne** [comment]
@abhaychawla I think it would be better if I worked on the View Fixed Deposit screen before the Edit Screen. I am taking up this issue!

**Comment by abhaychawla** [comment]
Okay!

**Comment by spider0061** [comment]
Can I work on this @abhaychawlaas there is no PR on this since @zerefwayne took this issue?

**Comment by abhaychawla** [comment]
Go ahead.
