### ISSUE TITLE
Edit Fixed Deposit Product

### ISSUE THREAD

**Issue by abhaychawla** [openMF/web-app#466]
**Goal:**
As a branch manager, I want to edit a fixed deposit product, as seen at,

https://demo.openmf.org/#/editfixeddepositproduct/95

![edit fd product](https://user-images.githubusercontent.com/16948598/62408586-d14c7600-b5e8-11e9-9334-cec28c8b8594.PNG)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/102629544/Fixed+Deposit+Products
https://demo.openmf.org/api-docs/apiLive.htm#fdproducts_update

**Comment by zerefwayne** [comment]
Hey @abhaychawla, is this issue still open?

**Comment by abhaychawla** [comment]
Yes, @zerefwayne if you want to work on it go ahead.

**Comment by piculet** [comment]
Hi @abhaychawla, is this issue still open? If so, I'd like to work on it.

**Comment by abhaychawla** [comment]
Go ahead.
