### ISSUE TITLE
View Recurring Deposit Product

### ISSUE THREAD

**Issue by abhaychawla** [openMF/web-app#467]
**Goal:**
As a branch manager, I want to view a recurring deposit product, as seen at,

https://demo.openmf.org/#/viewrecurringdepositproduct/137

![view rd product](https://user-images.githubusercontent.com/16948598/62408633-62bbe800-b5e9-11e9-8fe0-b5ab7afa239e.PNG)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/102629552/Recurring+Deposit
https://demo.openmf.org/api-docs/apiLive.htm#rdproducts_retrieve

**Comment by spider0061** [comment]
Can I work on this? @abhaychawla
