### ISSUE TITLE
Edit Recurring Deposit Product

### ISSUE THREAD

**Issue by abhaychawla** [openMF/web-app#468]
**Goal:**
As a branch manager, I want to edit a fixed deposit product, as seen at,

https://demo.openmf.org/#/editrecurringdepositproduct/137

![edit rd product](https://user-images.githubusercontent.com/16948598/62408824-05756600-b5ec-11e9-81f8-e622fbeb0c04.PNG)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/102629552/Recurring+Deposit
https://demo.openmf.org/api-docs/apiLive.htm#rdproducts_update

**Comment by muskankhedia** [comment]
@abhaychawla I would like to take this up.

**Comment by abhaychawla** [comment]
@muskankhedia Go ahead, but keep in mind that this PR has a dependency on the gsoc branch. As you will be sending a PR for this on the master branch it would require a rebase before it can be merged once you get a successful review. It will only be merged after the gsoc branch is merged into master.

**Comment by muskankhedia** [comment]
@abhaychawla Will it be better if presently I will be sending the PR to the GSOC branch as it will help to prevent future conflicts and errors?

**Comment by abhaychawla** [comment]
No, it is supposed to contain the work done during the GSoC period only.

**Comment by abhaychawla** [comment]
No, its supposed to contain the work done during the gsoc period only and will be merged soon.

**Comment by muskankhedia** [comment]
@abhaychawla yes sir, got it.

**Comment by muskankhedia** [comment]
@abhaychawla I commented on this issue and was about to start working, I realised that the issue #467 should be solved before it and so I solved that. And I can work on it after the PR #531 is merged. So I then started taking other issue and working on it. Can you please guide, what should I do, should I continue working on other issues, or make a branch from the PR #531 and implement the edit feature first?

**Comment by abhaychawla** [comment]
It is up to you Muskan whichever issue you want to work on. Ultimately you might be asked to rebase your PR if it has a dependency. Just make sure you comment and work on one issue at one time and let the other issues be open for others to work on.

**Comment by muskankhedia** [comment]
Sure. For now, I have already commented on the issue #219, I think it will be better if I complete to work on that and comment on next on the issue I want to work on. Please correct me if I am wrong.

**Comment by abhaychawla** [comment]
That's fine.
