### ISSUE TITLE
font selection option feature is not available

### ISSUE THREAD

**Issue by tanujvyas10** [openMF/web-app#472]
**Is your feature request related to a problem? Please describe.**
the font selection option (in settings/home setting /themes and font) is not available 
**Describe the solution you'd like**
the font selection option should provide various font styles to the user.

**Describe alternatives you've considered**
I want to add the font style selection feature to this option so that the user can add the font style according to their choice
**image of problem**
![mifos1](https://user-images.githubusercontent.com/48439116/66118832-f5cacb80-e5f4-11e9-9347-abd12c18477e.jpg)

**final solution should look like**
![mifos2](https://user-images.githubusercontent.com/48439116/66119069-899c9780-e5f5-11e9-8840-1488e521db54.jpg)

**Comment by tanujvyas10** [comment]
@abhaychawla  @edcable  I have solved this issue. Can I create a PR for this?

**Comment by abhaychawla** [comment]
@tanujvyas10 This feature is not available because the relevant APIs required to develop the same are not yet present at the backend. We need support to save and retrieve the fonts from the backend. Please refer: https://github.com/openMF/web-app/issues/35
Closing this issue.

**Comment by tanujvyas10** [comment]
@abhaychawla Can it be consider relevent?
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48439116/68073041-84786700-fdb2-11e9-939b-e369f9b0dfad.gif)

**Comment by abhaychawla** [comment]
Are you using local storage?

**Comment by tanujvyas10** [comment]
@abhaychawla yes sir i am using localstorage

**Comment by abhaychawla** [comment]
Alright, we can have this as a temporary solution until the APIs are available. Send a PR, will have a look.

**Comment by tanujvyas10** [comment]
@abhaychawla ok sir thank you

**Comment by Abhirup-99** [comment]
@karantakalkar can I work on this?

**Comment by abhishekkumar08** [comment]
@karantakalkar , is anyone assigned or can I work on this?

**Comment by karantakalkar** [comment]
@Abhirup-99 go ahead
