### ISSUE TITLE
Cannot log-in with passwords containing '#'

### ISSUE THREAD

**Issue by MagicKriss** [openMF/web-app#473]
## Description
User with a password containing '#' can be created, but cannot be loged in.
This is because the password for authentication is sent in a non-encoded query parameter.
As a minimum, the query parameter should be encoded.
An even better solution would be to send credentials in a request body. Although the query parameter is sent over Secure HTTP, the incoming URL with parameters may still be logged in servers, and browsers may save requests in history, which raises security concerns.

## Steps to Reproduce
1. Create a user with a password containing '#' character. E.g. 'password#123'.
2. Try to log in with that user.

## Expected Behaviour
User can log in.
## Actual Behaviour
User cannot log in because '#' character and everything after that gets ignored by the browser.

**Comment by tanujvyas10** [comment]
@MagicKriss can i work on this issue
?

**Comment by MagicKriss** [comment]
Sure!

sestd., 2019. g. 19. okt., plkst. 20:27 — lietotājs tanujvyas10 (<
notifications@github.com>) rakstīja:

**Comment by abhaychawla** [comment]
@MagicKriss There is an existing issue for the same at the backend: https://issues.apache.org/jira/browse/FINERACT-629
