### ISSUE TITLE
Remove the unexpected message from view

### ISSUE THREAD

**Issue by Rupeshiya** [openMF/web-app#477]
## Description
On moving to "http://localhost:4200/clients/view/6" in development or https://openmf.github.io/web-app/clients/view/6 in production we get an unexpected message at the bottom left that should be removed.

## Steps to Reproduce
Move to http://localhost:4200/clients/view/6" in development or https://openmf.github.io/web-app/clients/view/6 in production and see the message at the bottom left corner.

## Expected Behaviour
That message should not be there.
## Actual Behaviour
Message is there. 

## Settings
- Mifos X version: 0.0.0-dev
- Browser used: Chrome/firefox

## Screenshots, if any
![open](https://user-images.githubusercontent.com/31209617/68076746-e222a880-fdde-11e9-882b-56f7a27ed360.png)

**Comment by abhaychawla** [comment]
@Rupeshiya The Clients section has been revamped during the GSoC period this year. We are yet to merge those changes in the main branch, but it will be soon. This issue no longer exists.
Closing.
