### ISSUE TITLE
Search feature is not working

### ISSUE THREAD

**Issue by tanujvyas10** [openMF/web-app#478]
**Is your feature request related to a problem? Please describe.**
The search feature is not working

**Describe the solution you'd like**
The user should type the account number or Name or any other column specification and the table element related to that should appear after filtering via the search bar.

**Screenshot**
![mifos6](https://user-images.githubusercontent.com/48439116/68081754-ff846080-fe38-11e9-87d2-fafe08d2c5f3.jpeg)
![mifos5](https://user-images.githubusercontent.com/48439116/68081755-001cf700-fe39-11e9-8f5b-33723c8d811f.jpeg)

**Comment by abhaychawla** [comment]
Searching for the client's list page is under discussion amongst the community since this year's GSoC. This isn't a valid issue. It is under discussion and will be implemented once a decision is reached.
