### ISSUE TITLE
After search click the search bar should be cleared for good user experience

### ISSUE THREAD

**Issue by Rupeshiya** [openMF/web-app#480]
## Description
After search click the search bar should be cleared

## Steps to Reproduce
Move to https://openmf.github.io/web-app/home and search, its not working and also not clearing after search.

## Expected Behaviour
After search click the search bar should be cleared
## Actual Behaviour
After search click the search bar is not cleared which decrease the user experience
## Settings
- Mifos X version: 0.0.0
- Browser used: chrome/firefox

**Comment by abhaychawla** [comment]
@Rupeshiya The web app is still under development due to which some features might not be working. This issue is irrelevant, I don't think that clearing the search box just after doing the search improves the user experience in any manner.
