### ISSUE TITLE
Sorting is not working on certain columns in audit trails

### ISSUE THREAD

**Issue by luckyman20** [openMF/web-app#483]
## Description
Sorting for columns `Status`, `Made by` and `Checker` is not working as it is not supported by backend. [Ticket ](https://issues.apache.org/jira/browse/FINERACT-799) for the same has been raised on Fineract JIRA.

## Steps to Reproduce
System -> Audit Trails -> Try sorting any of these columns

**Comment by shobhi1310** [comment]
@abhaychawla @karantakalkar 
Sir,
Can I look into this issue?
