### ISSUE TITLE
List of Users

### ISSUE THREAD

**Issue by abhaychawla** [openMF/web-app#484]
**Goal:**
As an admin, I want to view existing users as seen at,

https://demo.openmf.org/#/users/

![users list](https://user-images.githubusercontent.com/16948598/69831760-f15d1080-123b-11ea-9cfe-0e651c380711.PNG)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67141740/Users
https://demo.openmf.org/api-docs/apiLive.htm#users_list

**Comment by ridhishjain** [comment]
I see this issue is same as #486, I want to work on this issue

**Comment by abhaychawla** [comment]
@ridhishjain issues tagged with gci label are reserved as tasks for GCI students only. Please see some other issue. Also, please comment to work on a single issue at a time only not on multiple issues.
