### ISSUE TITLE
System: Entity to Entity Mapping List

### ISSUE THREAD

**Issue by abhaychawla** [openMF/web-app#485]
**Goal:**
As a system admin, I want to view all entity to entity mappings as seen at,

https://demo.openmf.org/#/entitytoentitymapping

![e2e mapping list](https://user-images.githubusercontent.com/16948598/69832258-56b20100-123e-11ea-865f-19ccfbfa48af.PNG)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/92504226/Entity+To+Entity+Mapping
API: /entitytoentitymapping

**Comment by tanujvyas10** [comment]
@abhaychawla sir, are you working on this or is this issue available for anyone who wants to work on this?

**Comment by abhaychawla** [comment]
If you want to work on this, go ahead.

**Comment by tanujvyas10** [comment]
thank you.

**Comment by tanujvyas10** [comment]
@abhaychawla ,Sir should i keep the layout in horizontal manner or should i keep the vertical layout just like the one in https://demo.openmf.org/#/entitytoentitymapping.
![enity-2-entity](https://user-images.githubusercontent.com/48439116/71579086-ee965980-2b20-11ea-9333-2408e0d54136.jpeg)

**Comment by tanujvyas10** [comment]
@abhaychawla , sir should I follow the horizontal layout method (as shown below) or should I follow the vertical layout method similar to https://demo.openmf.org/#/entitytoentitymapping or Should I provide a new page for every link in the menu of entity-to-entity mapping.
![enity-2-entity](https://user-images.githubusercontent.com/48439116/71642952-14fef500-2cd9-11ea-8a31-7599435fd68b.jpeg)

**Comment by abhaychawla** [comment]
@tanujvyas10 I didn't understand your query. You are just supposed to implement the above screen as in the community app within the web app.

**Comment by tanujvyas10** [comment]
@abhaychawla very well sir, I will certainly do this and will soon give you updates.

**Comment by abhaychawla** [comment]
If you need some clarity, please let me know. Its just Abhay.

**Comment by tanujvyas10** [comment]
@abhaychawla thanks Abhay

**Comment by tanujvyas10** [comment]
@abhaychawla , how to I get the raw-data of loan-product? 
![office-loan](https://user-images.githubusercontent.com/48439116/72093011-9a1d8600-3339-11ea-859c-73e883ed531f.jpg)

**Comment by tanujvyas10** [comment]
@abhaychawla , Please tell me, how do I get the raw-data of **office access to loan-product** ? 
![office-loan](https://user-images.githubusercontent.com/48439116/72093011-9a1d8600-3339-11ea-859c-73e883ed531f.jpg)

**Comment by tanujvyas10** [comment]
@abhaychawla , where can I find API documentation for this issue?

**Comment by abhaychawla** [comment]
You will have to look into its current implementation of the community app. Please keep in mind this issue is only for the list view and not the other component connecting to the list view.

**Comment by tanujvyas10** [comment]
@abhaychawla sorry, I didn't understand what you mean by **only for the list view**, should I use the dummy data for the table, please clarify?

**Comment by abhaychawla** [comment]
No, use the API used in the existing implementation in the community app. By list view(table), I am referring to the table in the screenshot.

**Comment by abhaychawla** [comment]
@muskankhedia Please comment on the issue before you start working on it.

**Comment by muskankhedia** [comment]
Yaa sure. Will surely keep that in mind further.
