### ISSUE TITLE
List of Templates

### ISSUE THREAD

**Issue by abhaychawla** [openMF/web-app#486]
**Goal:**
As an admin, I want to view existing templates as seen at,

https://demo.openmf.org/#/templates

![templates](https://user-images.githubusercontent.com/16948598/69832451-7269d700-123f-11ea-8385-de2c18fe367b.PNG)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/103186480/Templates
https://demo.openmf.org/api-docs/apiLive.htm#resource_templatelist

**Comment by ridhishjain** [comment]
@abhaychawla I want to work on this issue
As I am new to the code, can you tell me the path of the file where the change is required

**Comment by abhaychawla** [comment]
This issue is reserved for GCI students.
