### ISSUE TITLE
Manage Roles and Permissions: Add Role

### ISSUE THREAD

**Issue by abhaychawla** [openMF/web-app#487]
**Goal:**
As a system admin, I want to add a new role:

https://demo.openmf.org/#/admin/addrole

![add role](https://user-images.githubusercontent.com/16948598/69832819-6da62280-1241-11ea-9840-188faf637504.PNG)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67895364/Manage+Roles+and+Permissions
https://demo.openmf.org/api-docs/apiLive.htm#roles_create

**Comment by tanujvyas10** [comment]
@abhaychawla sir, are you working on this issue or is this issue open for anyone who wants to contribute?
