### ISSUE TITLE
GCI-Task support Excel export data.

### ISSUE THREAD

**Issue by giorgiozoppi** [openMF/web-app#489]
We want to provide a button + a mechanism to export from the current datatable in excel in order to create a useful listing of data. For example near Import Client, a new button with Export Client. The user story:
1.the user clicks on export client
2. the ui generate an event to the system
3. the system provides a way to export the table in excel (ie. the complete list of client) and asks the user where to save.

**Comment by abhaychawla** [comment]
Screens need to be fully developed before we can move on with the export feature.
I would again reiterate and ask you to contribute to the web app first for a significant period before creating tasks for the same.
