### ISSUE TITLE
Some action names do not filter audit trails

### ISSUE THREAD

**Issue by luckyman20** [openMF/web-app#499]
## Description
Some action names (like 'CREATE','DELETE', 'UPDATE', etc) are returning 400 bad request error when selected for filtering the audit trails. [Ticket ](https://issues.apache.org/jira/browse/FINERACT-808) for the same has been raised on Fineract JIRA.

## Steps to Reproduce
System -> Audit Trails -> Try selecting any of the above mentioned action names

**Note**: One of the working Action Name is 'ACTIVATE'.

**Comment by tawfiek** [comment]
Can I work on this ?!

**Comment by ramvr1256** [comment]
![image](https://user-images.githubusercontent.com/59759301/188367523-849b61d9-0795-42f9-b5b3-1c02c8f8acc6.png)
Working as expected.
