### ISSUE TITLE
Centers component needs refactoring

### ISSUE THREAD

**Issue by punwai** [openMF/web-app#501]
## Description

The code for this component has to be updated to make it easier to work with and match the structure of other components.

- There are no comments in the component, service, module and routing

- Incorrect indentation and white spaces.
<img width="147" alt="Screenshot 2019-12-07 at 10 03 49" src="https://user-images.githubusercontent.com/28529491/70372626-7fd72f00-18d9-11ea-94f6-b0e4243c8b2c.png">
<img width="316" alt="Screenshot 2019-12-07 at 10 03 46" src="https://user-images.githubusercontent.com/28529491/70372653-b44aeb00-18d9-11ea-884a-38d558423666.png">

- The table spacing and structure is inconsistent with other components
<img width="674" alt="Screenshot 2019-12-07 at 10 02 21" src="https://user-images.githubusercontent.com/28529491/70372659-c2990700-18d9-11ea-96d3-13751e5162b8.png">

- The component is directly making API calls from the service, make it pass through a resolver instead.
<img width="450" alt="Screenshot 2019-12-07 at 10 04 59" src="https://user-images.githubusercontent.com/28529491/70372645-9c736700-18d9-11ea-95b6-7af35d813908.png">

**Comment by punwai** [comment]
I will send a PR on this once my other PR on this same component is merged.

**Comment by punwai** [comment]
@abhaychawla do you think this is a genuine issue that would be worth working

**Comment by punwai** [comment]
@abhaychawla Will this be an issue worth working on? This is also an issue affecting the Groups component.

**Comment by abhaychawla** [comment]
@punwai, Yes the development of Groups and Centers modules started about two years ago. At that time it wasn't refactored properly to follow guidelines and remove obsolete stuff. This year Jivjyot gave Clients module a major revamp. Similar to that groups and centers also need to be updated. You can list out the issues that exist within groups and centers in two separate issues that require refactoring.

**Comment by spider0061** [comment]
@abhaychawla I would like to work on this.

**Comment by karantakalkar** [comment]
Covered mostly in #506
