### ISSUE TITLE
Add back to home button in 404 page or automatically redirect to home page after few seconds 

### ISSUE THREAD

**Issue by Rupeshiya** [openMF/web-app#503]
**Is your feature request related to a problem? Please describe.**
On moving to an error page there is no back button for coming back to home except the browser back arrow (look at https://openmf.github.io/web-app/accounting/frequent-postings)

**Describe the solution you'd like**
Add back to home button in 404 page or automatically redirect to home page after few seconds. 

**Additional context**
May help the user to take the next step i.e to move back.

**GCI**

**Comment by ridhishjain** [comment]
Can I work on this issue?

**Comment by Rupeshiya** [comment]
@ridhishjain Are you GCI participants?

**Comment by abhaychawla** [comment]
@Rupeshiya GCI tasks are not to be claimed directly from here. Also, I would again request you to try and contribute to the web app yourself first before creating the tasks for GCI in the repository.

**Comment by Rupeshiya** [comment]
@abhaychawla Plz try to look at the issues at least once then judge :pray: 
No problem, thanks for advice

**Comment by abhaychawla** [comment]
@Rupeshiya I never said the issue was invalid. I think you misunderstood something.
