### ISSUE TITLE
On clicking the delete button and hovering over the dialogue box appeared to confirm delete disappear the text due to black color on hover.

### ISSUE THREAD

**Issue by Rupeshiya** [openMF/web-app#504]
## Description
On clicking the delete button and hovering over the dialogue box appeared to confirm delete disappear the text due to black color on hover.

## Steps to Reproduce
After login, move to https://openmf.github.io/web-app/accounting/chart-of-accounts/gl-accounts/view/77 and click on delete option to reproduce.

## Expected Behaviour
Should appear the text on the button to delete or cancel.

## Actual Behaviour
Not appearing the text after clicking the delete button and turns out to be black

## Settings
- Mifos X version: 0.0.0
- Browser used: Chrome, firefox

## Screenshots, if any
![Screenshot from 2019-12-07 23-50-12](https://user-images.githubusercontent.com/31209617/70378908-599ea700-194c-11ea-8c53-749dca47eeb9.png)

**Comment by abhaychawla** [comment]
@Rupeshiya The description and title are very confusing to understand. And I am unable to reproduce this scenario. The delete dialog is shared for many components, I have verified with all the themes and didn't face this issue.
