### ISSUE TITLE
Manage Employees: View Employee

### ISSUE THREAD

**Issue by abhaychawla** [openMF/web-app#534]
**Goal:**
As an organization admin, I require the ability to view an employee as at,

https://demo.mifos.io/#/viewemployee/4

![view employee](https://user-images.githubusercontent.com/16948598/71646762-e8f56b00-2cfc-11ea-9a55-006ca7c6c001.PNG)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67141732/Manage+Employees
https://demo.openmf.org/api-docs/apiLive.htm#staff_retrieve

**Comment by OussEmaDevCode** [comment]
@abhaychawla Do we include the "Mobile Number for SMS" section ?
