### ISSUE TITLE
Products: View Product Mix

### ISSUE THREAD

**Issue by abhaychawla** [openMF/web-app#541]
**Goal:**
As a products admin, I require the ability to view a product mix's information as at,

https://demo.mifos.io/#/viewproductmix/1

![vpm](https://user-images.githubusercontent.com/16948598/71647360-c9fbd680-2d06-11ea-82f5-0ec1ceb81282.PNG)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/103186467/Product+Mix
https://demo.mifos.io/api-docs/apiLive.htm#loanproductmix_retrieve

**Comment by agamvrinos** [comment]
@abhaychawla I'll work on this.
