### ISSUE TITLE
Report Run Frequency value is not displayed in View Adhoc Query

### ISSUE THREAD

**Issue by punwai** [openMF/web-app#555]
## Description
The report run frequency is displayed as its ID rather than its value.

## Steps to Reproduce
Organization > Adhoc Query > View Adhoc Query

## Expected Behaviour
The Value of the Report Run Frequency should be displayed.

## Actual Behaviour
The ID of the Report Run Frequency is displayed rather than the value itself.

## Settings
- Mifos X version: 0.0.0-dev
- Browser used: Chrome

## Screenshots, if any
![image](https://user-images.githubusercontent.com/28529491/71894783-19973380-3147-11ea-9828-226e9df5aa57.png)

**Comment by abhaychawla** [comment]
@punwai, Please ensure from the next time if you are making a voluntary contribution, comment on the issue to inform that you are working on it before directly sending a PR.

Please update the description to specify the data under `Settings`, the screenshot should go under the heading `Screenshots` and not in between.

**Comment by abhaychawla** [comment]
@punwai I have updated for now.
