### ISSUE TITLE
After Submitting Create User form, the User is not redirected to the View User Page of the Created User

### ISSUE THREAD

**Issue by Rishabh106** [openMF/web-app#557]
**Is your feature request related to a problem? Please describe.**
After submitting create User form, the User is redirected to the Users page.

**Describe the solution you'd like**
After submitting create User form, the User must be redirected to the view User page of the created user.

**Describe alternatives you've considered**
The User should be redirected to the Users page, which is already implemented.

**Additional context**
![user_issue](https://user-images.githubusercontent.com/36294070/71907020-32c4d200-3191-11ea-9e93-574db9b95db1.gif)

**Comment by abhaychawla** [comment]
@Rishabh106, Please ensure from the next time if you are making a voluntary contribution, comment on the issue to inform that you are working on it before directly sending a PR.
