### ISSUE TITLE
SMS Campaigns: View SMS Campaign

### ISSUE THREAD

**Issue by spider0061** [openMF/web-app#563]
Add view sms campaign component so that admin can view a sms campaign.

like this:
![Screenshot from 2020-01-10 18-43-02](https://user-images.githubusercontent.com/45865775/72156886-9858ce80-33dc-11ea-8e55-cc74d7637a66.png)

useful link: https://demo.openmf.org/#/viewsmscampaign/2

**Comment by abhaychawla** [comment]
@spider0061,  Please ensure from the next time if you are making a voluntary contribution, comment on the issue to inform that you are working on it before directly sending a PR.

**Comment by spider0061** [comment]
@abhaychawla okay Sir, It was not an issue there so I created an issue first. But I will take care of it next time.
