### ISSUE TITLE
Implement Lazy Loading for all Modules

### ISSUE THREAD

**Issue by punwai** [openMF/web-app#567]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Applying lazy loading to all the modules (listed later) will majorly reduce the time which it takes the web-app to load the first time. This is very important as the app will load much faster during development after making changes to the codebase.

These are the modules that lazy loading should be implemented for:
- [ ] Accounting
- [ ] Centers
- [ ] Clients
- [ ] Groups
- [ ] Home
- [ ] Loans
- [ ] Login
- [ ] Navigation
- [ ] Self Service
- [ ] Settings
- [ ] Organization
- [ ] Products
- [ ] Templates
- [ ] Users
 
**Describe alternatives you've considered**

**Additional context**

**Comment by abhaychawla** [comment]
@punwai, Please ensure from the next time if you are making a voluntary contribution, comment on the issue to inform that you are working on it before directly sending a PR. 
Lazy loading was expected to be implemented in GSoC 19 but we were unable to reach up to that point. This will be a major update and will require a bit of discussion before we proceed properly.

**Comment by dev-loyde** [comment]
Hello @abhaychawla,  i 'll d like to work on this.

**Comment by shobhi1310** [comment]
@karantakalkar @abhaychawla 
Sir, the repository is now based on Angular 9, so what will be the use of lazy loading here now?

**Comment by mittulmandhan** [comment]
I would like to work on it
