### ISSUE TITLE
Surveys: View Survey

### ISSUE THREAD

**Issue by Rishabh106** [openMF/web-app#580]
**Goal:**
System Admins require the ability to view survey as at

https://demo.mifos.io/#/viewsurvey/2
![view_survey](https://user-images.githubusercontent.com/36294070/72687626-c8fbdf00-3b25-11ea-8d45-4dc7af4e9792.png)

**Resources:**
https://mifosforge.jira.com/wiki/spaces/MIFOS/pages/73466240/Surveys

**Comment by agamvrinos** [comment]
@Rishabh106 I'll work on this.

**Comment by DivineWisdom** [comment]
Please I would like to work on this issue, can I?

**Comment by shobhi1310** [comment]
Can the issue be a bit more elaborated, like where should this section appear and the functionalities required, or so ?
I would like to contribute and fix to this issue. 🙂

**Comment by karantakalkar** [comment]
Please work on one issue at a time I have assigned you #746

**Comment by shobhi1310** [comment]
I am trying to understand the codebase, so I am currently working out on this issue, and I am creating a view survey page as per the legacy design provided in the issue.

**Comment by karantakalkar** [comment]
Ensure design is consistent with rest of the app, design provided in the issue is only for reference

**Comment by shobhi1310** [comment]
@karantakalkar , sir please do review my PR .
