### ISSUE TITLE
org.springframework.dao.EmptyResultDataAccessException

### ISSUE THREAD

**Issue by Habeebu** [openMF/web-app#582]
I am trying to use the API, this method https://domain.com/fineract-provider/api/v1/savingsaccounts/3347/transactions/4680
But I received this error,
{
"timestamp": 1495226926465,
"status": 500,
"error": "Internal Server Error",
"exception": "org.springframework.dao.EmptyResultDataAccessException",
"message": "Incorrect result size: expected 1, actual 0"
}
Any help, I checked and there is accountId and transactionId

**Comment by karantakalkar** [comment]
Please raise a ticket on fineract for backend related issues.
