### ISSUE TITLE
View User: 'Email' is shown as blank for users without Email

### ISSUE THREAD

**Issue by Rishabh106** [openMF/web-app#584]
## Description
For users with 'autoGeneratePassword' set to false, in View User screen, Email should be shown only if it is available for the user as it is optional to enter Email with that condition.

## Steps to Reproduce
Go to Admin -> Users -> View User (any user without email)

## Expected Behaviour
'Email' text should not be shown as its data is not available for the users with 'autoGeneratePassword' set to false. if email data is not available for them.

## Actual Behaviour
'Email' text is shown even though its data is not available for the user.

## Settings
- Mifos X version: 0.0.0
- Browser used: Chrome

## Screenshots, if any
![user_email](https://user-images.githubusercontent.com/36294070/72916548-3bf49800-3d68-11ea-93e0-4d1144812cac.png)

**Comment by spider0061** [comment]
@Rishabh106 I was going through this issue and what I found was in the create user form the fields that are displayed in view user are marked as required. So, now it may be occurring for this specific user only as if a new user is created then it is sure that it will contain all the required fields which are username, first name , last name, email ,office and roles. Correct me if I am wrong :)

**Comment by Rishabh106** [comment]
> @Rishabh106 I was going through this issue and what I found was in the create user form the fields that are displayed in view user are marked as required. So, now it may be occurring for this specific user only as if a new user is created then it is sure that it will contain all the required fields which are username, first name , last name, email ,office and roles. Correct me if I am wrong :)

Actually, the email 'required' is conditional, for users with 'auto generate password' unchecked, the email is not a required form control. For others with 'auto generate password' checked, email is required.

**Comment by spider0061** [comment]
> > @Rishabh106 I was going through this issue and what I found was in the create user form the fields that are displayed in view user are marked as required. So, now it may be occurring for this specific user only as if a new user is created then it is sure that it will contain all the required fields which are username, first name , last name, email ,office and roles. Correct me if I am wrong :)
> 
> Actually, the email 'required' is conditional, for users with 'auto generate password' unchecked, the email is not a required form control. For others with 'auto generate password' checked, email is required.

My mistake I didn't see that email is conditionally required. @abhaychawla I would like to work on it.
