### ISSUE TITLE
Users: Edit User

### ISSUE THREAD

**Issue by Rishabh106** [openMF/web-app#585]
**Goal:**
Users admins require the ability to edit user as at

https://demo.mifos.io/#/edituser/2891
![edit_user](https://user-images.githubusercontent.com/36294070/72917170-54b17d80-3d69-11ea-8ac8-bbc96e02e153.png)

**Resources:**
https://mifosforge.jira.com/wiki/spaces/docs/pages/67141740/Users
https://demo.mifos.io/api-docs/apiLive.htm#users_update

**Comment by agamvrinos** [comment]
@Rishabh106 I'll work on this.

**Comment by agamvrinos** [comment]
@BLasan ?

**Comment by BLasan** [comment]
Still cannot edit users @agamvrinos

**Comment by agamvrinos** [comment]
That's because the pr has not been merged ...

**Comment by BLasan** [comment]
Yuh. It has to be merged
