### ISSUE TITLE
Charges: Edit Charge

### ISSUE THREAD

**Issue by Rishabh106** [openMF/web-app#586]
**Goal:**
Products admins require the ability to edit charge as at

https://demo.mifos.io/#/editcharge/78
![edit_charge](https://user-images.githubusercontent.com/36294070/72920356-1fa82980-3d6f-11ea-8897-3f32495964ff.png)

**Resources:**
https://mifosforge.jira.com/wiki/spaces/docs/pages/72908813/Charges
https://demo.mifos.io/api-docs/apiLive.htm#charges_update

**Comment by BLasan** [comment]
I would like to fix this issue

**Comment by BLasan** [comment]
This can be editted by the admin. Check https://demo.mifos.io/#/products and select the required item and then edit @Rishabh106

**Comment by Rishabh106** [comment]
You have to add the same component in the web app, that is the required task to do in this issue. @BLasan

**Comment by BLasan** [comment]
I'll work on this @Rishabh106

**Comment by abhaychawla** [comment]
@BLasan I see you sent so many PRs and closed them, Please don't repeat this again. This is not a test repository.

**Comment by BLasan** [comment]
@abhaychawla  Okay sir. It won't happen again
