### ISSUE TITLE
Manage Tax Configurations: View Tax Group

### ISSUE THREAD

**Issue by Rishabh106** [openMF/web-app#587]
**Goal:**
Products admins require the ability to view a tax group as at

https://demo.mifos.io/#/viewtaxgroup/20
![view_tax_group](https://user-images.githubusercontent.com/36294070/72921944-3439f100-3d72-11ea-8dd3-d0cbccd23c71.png)

**Resources:**
https://demo.mifos.io/api-docs/apiLive.htm#retrieve_taxgroup

**Comment by punwai** [comment]
Hope you don't get too tired working on all of these tasks hahaha

**Comment by Rishabh106** [comment]
These issues are not on high priority currently, I just opened them so that we're aware what to do after all the high priority issues are dealt with.

**Comment by Kajol-Kumari** [comment]
Can i work on this?
