### ISSUE TITLE
Manage Tax Configurations: Edit Tax Component

### ISSUE THREAD

**Issue by Rishabh106** [openMF/web-app#588]
**Goal:**
Products admins require the ability to edit tax component as at

https://demo.mifos.io/#/edittaxcomponent/64
![Screenshot from 2020-05-11 12-22-10](https://user-images.githubusercontent.com/54709463/81532751-8c791b00-9382-11ea-84a5-17eb1c562cde.png)

**Resources:**
https://mifosforge.jira.com/wiki/spaces/docs/pages/129957925/Manage+Tax+configuration
https://demo.mifos.io/api-docs/apiLive.htm#update_taxcomponent

**Comment by tonic889** [comment]
Hi, I'd like to take this one up if no one is working on it.

**Comment by spider0061** [comment]
@tonic889 hey are you still working on this issue or can I take up this issue as its been more than 12 days and there is no PR on it.

**Comment by tonic889** [comment]
@spider0061 I'm planning to work on it after my PR for Create Tax Component is merged. https://github.com/openMF/web-app/pull/605
I am kind of needing PR for Create tax to be merged before I can Edit Tax.

**Comment by spider0061** [comment]
@tonic889 Actually I thought you were not working on it because you commented a long time ago and I didn't see a PR. So, I wrote the code for it. Shall I submit the PR or will you work on it? I am fine if you are going to work on it.

**Comment by tonic889** [comment]
@spider0061 Go ahead and submit your PR as I haven't started on it yet.  Thanks

**Comment by spider0061** [comment]
@tonic889 Thanks I have submitted the PR.
