### ISSUE TITLE
Expand button doesn't work properly for chart of accounts

### ISSUE THREAD

**Issue by Kajol-Kumari** [openMF/web-app#593]
## Steps to Reproduce
Go to "Chart of Accounts/Home/Accounting/Chart of Accounts" and click on expand button.

## Expected Behaviour
The expand button should have expanded the list of accounts. 

## Actual Behaviour
I doesn't do anything if the list is collapsed, moreover it collapses the expanded account's list.

- Browser used: Google Chrome

## Screenrecord
https://drive.google.com/file/d/1SghpqChGxQatBv5cr4SGqFQeOyQKP1iN/view?usp=sharing

##Extra feature
All icons should have a on hover message telling a little bit about that icon.Currently only home,dashboard and navigation icon has this feature.

**Comment by Rishabh106** [comment]
This is a bug of Angular Material as stated in the code. https://github.com/openMF/web-app/blob/master/src/app/accounting/chart-of-accounts/chart-of-accounts.component.html Please look at the code before opening an issue. https://github.com/angular/components/issues/12170

**Comment by Kajol-Kumari** [comment]
yes @Rishabh106 , I missed it.Thanks for pointing out.But what about the extra feature part of having an on hover message for each icon instead of just three of them.

**Comment by abhaychawla** [comment]
Closing as irrelevant.

@Kajol-Kumari can you please elaborate on the feature request?

**Comment by Kajol-Kumari** [comment]
@abhaychawla Currently out of all the buttons/icons present on the left panel of the page, only first  three of them have the feature of showing a one word message hint of its functionality after taking the cursor on the icon/button(without clicking).So, I am requesting that each icon/button should have that feature so that new user can get a hint of what that particular button/icon is meant for.
