### ISSUE TITLE
Refactor  _helper.scss 

### ISSUE THREAD

**Issue by anweshknayak** [openMF/web-app#60]
`/src/assets/styles/_helper.scss`

- _margin.scss
- _padding.scss
- _text.scss
- _display.scss
- _align.scss

Example : https://github.com/ahmadajmi/css-helpers/tree/master/helpers

**Comment by Jp138233** [comment]
Would I be able to work on this?

**Comment by abhaychawla** [comment]
Yes, go ahead.

**Comment by spider0061** [comment]
Can I work on this issue if it is not assigned to anyone?

**Comment by abhaychawla** [comment]
Go ahead.
