### ISSUE TITLE
View Employees: Inactive Employees are not displayed

### ISSUE THREAD

**Issue by spider0061** [openMF/web-app#606]
## Steps to Reproduce
On the https://mobile.openmf.org/#/employees if an employee is inactive then it is not shown http://localhost:4200/organization/employees.

## Expected Behaviour
It should display all the employees either active or inactive like https://mobile.openmf.org/#/employees.

## Actual Behaviour
It does not display inactive employees.

## Settings
- Browser used: Mozilla Firefox

## Screenshots, if any
![Screenshot from 2020-02-16 13-30-01](https://user-images.githubusercontent.com/45865775/74601179-3ec17f00-50c1-11ea-83e1-39e952bb9ca9.png)
![Screenshot from 2020-02-16 13-30-16](https://user-images.githubusercontent.com/45865775/74601180-4123d900-50c1-11ea-9924-eabe455b548b.png)

**Comment by agamvrinos** [comment]
Hey @spider0061, I'm taking a look at this but the page does not seem to load due to a request timing out. Any thoughts on why this might be?

![image](https://user-images.githubusercontent.com/9131682/74818482-0a3b0680-52ff-11ea-8660-b4edbd105073.png)

**Comment by spider0061** [comment]
@agamvrinos Have you changed the base api url in environment.ts?

**Comment by agamvrinos** [comment]
@spider0061 No, I didn't see that mentioned anywhere. Could you point me to a related link?

**Comment by spider0061** [comment]
@agamvrinos have you got the issue?

**Comment by agamvrinos** [comment]
@spider0061 I manually changed the isActive to false for the first entry and it seems to work...

![image](https://user-images.githubusercontent.com/9131682/74828988-58a4d100-5310-11ea-9fd7-6f13655c732f.png)

**Comment by agamvrinos** [comment]
That seems to be a back-end problem since the inactive users are not fetched in the first place.

**Comment by spider0061** [comment]
@agamvrinos yeah I also think so.

**Comment by agamvrinos** [comment]
@spider0061 Pushed the fix.
