### ISSUE TITLE
Realtime Searching 

### ISSUE THREAD

**Issue by BLasan** [openMF/web-app#611]
**Description**
The searching method in the system does not filter the users or categories in a realtime manner. I think a realtime filtering and searching would be a great idea for this system as the users do not have to type whole string to get the required users. This will be more efficient than the ordinary filtering.

**Solution**
Make the searching method a real-time manner with the help of pipe service.
![Screenshot from 2020-02-20 16-56-16](https://user-images.githubusercontent.com/43112139/74929716-18be1680-5402-11ea-98ba-9a3354b77cce.png)

**Comment by BLasan** [comment]
@abhaychawla  I would like to work on this feature

**Comment by anirudhsingh20** [comment]
@abhaychawla 
Hi, I am Anirudh Singh, pursuing BTech in computer science and have good experience in MERN stack. I am looking forward for GSoC'2020 and excited to contribute to this web app. 

I have successfully run web-app locally and updated API URL in env file

any suggestions for me?
