### ISSUE TITLE
Bad UI: arrow of language select not aligned correctly

### ISSUE THREAD

**Issue by anirudhsingh20** [openMF/web-app#612]
## Description
Arrow of language select not aligned correctly (vertically)

## Steps to Reproduce
1. Login
2. Check header in desktop view and see language select.

## Expected Behaviour
![mifos-lang-fix](https://user-images.githubusercontent.com/49402380/75049926-02db4f00-54f1-11ea-83c5-aa2ceef621b7.PNG)

## Actual Behaviour

Arrow has no margin-top and very close to the language text

![mifos-lang](https://user-images.githubusercontent.com/49402380/75049877-efc87f00-54f0-11ea-96c8-375f2886adfa.PNG)

## Settings
- Mifos X version: 0.0.0 development
- Browser used: Chrome

## Additional Context

I want to work on this issue .

**Comment by gittysachin** [comment]
Hi @anirudhsingh20 
Are you still working on this issue? If not then I'd like to work on this issue.

**Comment by anirudhsingh20** [comment]
yes .

**Comment by ashutoshsenger** [comment]
I'm working on this issue now.

**Comment by DivineWisdom** [comment]
Hello has this issue been fixed? if No i would like to work on it

**Comment by ashutoshsenger** [comment]
yes it has been fixed, you can see pull request has been created already, so you can move to other issues.

**Comment by abhaychawla** [comment]
Closing this issue as it is unnecessary, we are using Angular Material components and as we have not done any customization for `mat-select` this is the current default behavior. If there is an issue with `mat-select`, it can be reported at the official Angular Material repository.
