### ISSUE TITLE
Replace font awesome icons with angular font awesome icons

### ISSUE THREAD

**Issue by vabshere** [openMF/web-app#615]
**Is your feature request related to a problem? Please describe.**
This feature request is a continuation to #138 and will increase uniformity in icons used throughout the project.

**Describe the solution you'd like**
Few files have the font awesome icons used. Simply replacing them with the angular font awesome icons syntax should work, since the library has already been added.

**Comment by spider0061** [comment]
Hi @vabshere isn't this issue same as #138. Also, that issue is open. Any specific reason to open this issue?

**Comment by vabshere** [comment]
No this issue is completely different from #138
<https://github.com/openMF/web-app/issues/138>. #138
<https://github.com/openMF/web-app/issues/138> is for replacing material
icons with angular fontawesome icons. Nothing's been said about the
"regular" fontawesome icons. So this issue is actually a suggested
enhancement similar to #138 <https://github.com/openMF/web-app/issues/138>.
Also, there are no more material icons present and #138
<https://github.com/openMF/web-app/issues/138> can be closed now.

**Comment by piculet** [comment]
Hi @vabshere, I'd like to give a shot to this issue.

**Comment by Mutahar-Majid** [comment]
Are you working on this issue #615 @vabshere ?

**Comment by vabshere** [comment]
@Mutahar-Majid i'm waiting for one of the moderators/admins to have a look at the issue first.

**Comment by Mutahar-Majid** [comment]
@vabshere  I had commented on the original issue #138 two weeks ago regarding #615 but there's still been no response.Does gsoc project announcement usually reduce  the response time ?

**Comment by vabshere** [comment]
not sure. seems plausible though

**Comment by DivineWisdom** [comment]
Hello, I would like to work on this issue, can I go ahead?
