### ISSUE TITLE
Client: View Survey Of Clients

### ISSUE THREAD

**Issue by muskankhedia** [openMF/web-app#617]
Goal:
As a loan officer, I want to view the survey taken by the client as shown here:
https://demo.mifos.io/#/clients/survey/22

![Screenshot from 2020-02-23 03-05-21](https://user-images.githubusercontent.com/36980003/75099611-9bed9100-55e9-11ea-875d-a7c928cc791a.png)

**Comment by tawfiek** [comment]
I would like to work on this

**Comment by muskankhedia** [comment]
@tawfiek Sorry but I have already worked on it.
