### ISSUE TITLE
Data Table Entities for Dark Color Scheme

### ISSUE THREAD

**Issue by sonali623** [openMF/web-app#630]
The font color of entities of data tables for the dark color scheme has to be alternate to be visible.
![mifosX](https://user-images.githubusercontent.com/44675394/75452286-0743b400-5998-11ea-88c9-97998e36ec85.PNG)

**Comment by shobhi1310** [comment]
Yes this issue is present in all the tables present in the page, for the white backgrounds, alternate contrast like black coloured text should be preferable.

**Comment by shobhi1310** [comment]
It has got to deal with choosing the contrast colour supported by that theme, which needs to be used.

**Comment by shobhi1310** [comment]
Can I look into this issue ?

**Comment by noelbejarano** [comment]
Hi, currently this issue has already been solved with the following PR: https://github.com/openMF/web-app/pull/1354.

**Comment by bharathcgowda** [comment]
fixed with the PR #1354
