### ISSUE TITLE
Implement scroll-to-top button

### ISSUE THREAD

**Issue by sonali623** [openMF/web-app#634]
**Is your feature request related to a problem? Please describe.**
The table with large entries often takes a lot of time to scroll down which might get frustrating for the user.

**Describe the solution you'd like**
Implement a scroll-to-top button. The feature is very easy to implement.

**Comment by Adarsh-NP** [comment]
its actually easy to implement this feature of scroll to top...just add the id of the top container and enable smooth scrolling to make it look good.
Correct me if I am wrong.

**Comment by sonali623** [comment]
@Adarsh-NP Yes, no doubt it is very easy.

**Comment by tawfiek** [comment]
Can I work on this ?!

**Comment by drishti307** [comment]
I would like to work on this, can I?
