### ISSUE TITLE
minor UI fixes

### ISSUE THREAD

**Issue by LunaticProgrammer** [openMF/web-app#638]
## Description
There are minor UI issues which i think would add upto the overall UX to the product one such is the behaviour of the search button.

## Expected Behaviour
 Closing of the search bar on losing focus.
## Actual Behaviour
Closes only when the user clicks on the search icon again

## Settings
- Mifos X version: 0.0.0-dev
- Browser used: Google Chrome v79

![mifos UX part](https://user-images.githubusercontent.com/30633466/75614557-fe054380-5b5f-11ea-913a-b7271574e11d.PNG)

**Comment by gagan2005** [comment]
I would like to work on this

**Comment by drishti307** [comment]
I would like to work on this issue, can I?

**Comment by gagan2005** [comment]
> I would like to work on this issue, can I?

I already sent a Pull Request for this issue
