### ISSUE TITLE
Clients Filter is not working

### ISSUE THREAD

**Issue by ashutoshsenger** [openMF/web-app#639]
Bug:
Filter is not filtering the data in the clients Section.

I am working on this 
![Screenshot at 2020-03-01 12:24:24](https://user-images.githubusercontent.com/31319848/75621245-b7433800-5bb7-11ea-9cb2-72804f7d0f11.png)
issue.

**Comment by muskankhedia** [comment]
@ashutoshsenger this is a copy of issue #445. You can look for other issues for the time.
