### ISSUE TITLE
change scroll bar in side menu.

### ISSUE THREAD

**Issue by tawfiek** [openMF/web-app#647]
## Description
change scroll bar in side-men to be thinner and match Mifos's thems 

## Expected Behaviour
change native side scroll bar to  be something like this 
![Screenshot from 2020-03-05 01-13-34](https://user-images.githubusercontent.com/27981868/75931827-96f8cf00-5e7e-11ea-8cca-175710b5a3ab.png)

## Actual Behaviour
native scroll bar in side -menu 
![Screenshot from 2020-03-05 00-53-33](https://user-images.githubusercontent.com/27981868/75931597-0cb06b00-5e7e-11ea-9eba-b5eb05294c5b.png)

## Settings
- Mifos X version: 
- Browser used:

**Comment by tawfiek** [comment]
Can I work on this ?!

**Comment by muskankhedia** [comment]
Closing the same, as the reason mentioned in the PR.
