### ISSUE TITLE
Horizontal scroll in sidebar

### ISSUE THREAD

**Issue by AashishChakravarty** [openMF/web-app#651]
## Description
remove horizontal scroll in sidebar menu

## Steps to Reproduce
Please add as much detail as possible to reproduce the error/issue.
Don't assume the reader knows anything about the Mifos X Web App.

## Expected Behaviour
![image](https://user-images.githubusercontent.com/29206561/76067578-a3cc0e80-5fb5-11ea-84a3-63355f0db76a.png)

## Actual Behaviour
![image](https://user-images.githubusercontent.com/29206561/76067741-e55cb980-5fb5-11ea-8031-774c5799a665.png)

## Settings
- Mifos X version: 
- Browser used:

**Comment by karantakalkar** [comment]
@AashishChakravarty as per guidelines please comment on the issue before submitting PR

**Comment by AashishChakravarty** [comment]
@karantakalkar Sorry, this is my fault. But I have fixed the issue.

**Comment by asraman9792** [comment]
sir is this issue open please let me know if i can contribute some

**Comment by AashishChakravarty** [comment]
@asraman9792 I have already fixed it
