### ISSUE TITLE
Create Data Table component

### ISSUE THREAD

**Issue by BLasan** [openMF/web-app#653]
Component for creating a data table is needed as in 
https://demo.mifos.io/#/createdatatable

![Screenshot from 2020-03-06 20-50-07](https://user-images.githubusercontent.com/43112139/76096473-2d96ce80-5fec-11ea-87cf-84fc85ce1c4c.png)

**Comment by BLasan** [comment]
@abhaychawla  I'll work on this

**Comment by abhaychawla** [comment]
@BLasan if you try to claim and work on multiple issues at once, your PRs won't be accepted. Please follow the guidelines and work on one issue at a time.

**Comment by abhaychawla** [comment]
This is a duplicate of #171 and already has an existing PR. Please check for existing issues before creating a new one.
