### ISSUE TITLE
Office:Edit Office

### ISSUE THREAD

**Issue by BLasan** [openMF/web-app#662]
Edit Office component is needed as in 
https://demo.mifos.io/#/editoffice/270

![Screenshot from 2020-03-11 16-22-55](https://user-images.githubusercontent.com/43112139/76409654-ae6f1500-63b4-11ea-84b7-6a6f70c96c42.png)

**Comment by BLasan** [comment]
@abhaychawla  I'll work on this

**Comment by asraman9792** [comment]
sir is this issue open please let me know if i can contribute some

**Comment by BLasan** [comment]
It's completed.Check for another issue @asraman9792

**Comment by BLasan** [comment]
You can find an issue by your self too @asraman9792
