### ISSUE TITLE
Development Server URL is not working

### ISSUE THREAD

**Issue by luckyman20** [openMF/web-app#666]
## Description
The server on which we are trying to connect the web application doesn't exist now and is now moved to `demo.mifos.io`.

**Comment by abhaychawla** [comment]
Latest development server is now at dev.mifos.io
All details are mentioned here: https://groups.google.com/forum/#!searchin/mifosdeveloper/dev.mifos.io|sort:date/mifosdeveloper/GWLEVpqiCUU/sFt_BmplBQAJ
