### ISSUE TITLE
Create fixed deposit product : giving meaningful error message

### ISSUE THREAD

**Issue by abhi40308** [openMF/web-app#668]
## Description
Currently it is difficult to create a product, there is no meaningful error message displayed if some invalid params are passed to the api. Error message in case of invalid params is : "Invalid parameters were passed in the request!", which does not give information on exactly what parameters (form fields) are not correct.

## Steps to Reproduce
Go to https://openmf.github.io/web-app/products/fixed-deposit-products/create
Try to create a product

## Expected Behaviour
There should be a meaningful error message which gives information about exactly what parameters are not valid / wrong in the request. What fields need to be changed.

## Screenshots, if any
![Screenshot 2020-03-17 at 9 51 41 PM](https://user-images.githubusercontent.com/26903230/76877957-213b2d00-689a-11ea-9366-a4b3e5f95833.png)

**Comment by abhi40308** [comment]
Something can be done like this (screen from community app / create fixed deposit product) : 
![Screenshot 2020-03-17 at 9 59 48 PM](https://user-images.githubusercontent.com/26903230/76878327-ad4d5480-689a-11ea-8d60-dd2ee2187efc.png)

**Comment by karantakalkar** [comment]
Need to add support for this in later stages.
