### ISSUE TITLE
View All Floating Rates component required

### ISSUE THREAD

**Issue by BLasan** [openMF/web-app#671]
View Floating Rates component is needed as in 
https://demo.mifos.io/#/floatingrates

![Screenshot from 2020-03-21 10-37-04](https://user-images.githubusercontent.com/43112139/77219990-3d242480-6b61-11ea-9aec-386efea4ca85.png)

**Comment by BLasan** [comment]
@abhaychawla  I'll work on this

**Comment by Jov03** [comment]
Issue already logged #194
