### ISSUE TITLE
Client: View Selected Charge component required

### ISSUE THREAD

**Issue by BLasan** [openMF/web-app#682]
A component to view selected charges is required as in
https://demo.mifos.io/#/viewclient/1/charges/493

![Screenshot from 2020-03-24 15-02-24](https://user-images.githubusercontent.com/43112139/77410221-92ba3480-6de0-11ea-887c-c646d069750a.png)

**Comment by BLasan** [comment]
@abhaychawla  I'll work on this

**Comment by muskankhedia** [comment]
@karantakalkar #688 has solved the issue, so I think we can close this. For the refactoring part that can be done with reference to another issue later.

**Comment by karantakalkar** [comment]
Ok
