### ISSUE TITLE
Unit-Testing needs to be set up.

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#686]
Currently, there are following problems with effective unit testing of components and the entire app.

1. **fix:** edit sms component spec.ts, incorrect component name 'EditSms' instead of 'EditSMS' leads to error upon running `ng test`
2. **build:** add [karma jasmine HTML reporter](https://www.npmjs.com/package/karma-jasmine-html-reporter) to get detailed error analysis.
3. **build:** (optional) add [istanbul-instrument-loader](https://github.com/webpack-contrib/istanbul-instrumenter-loader) which is a dependency of karma-coverage-istanbul-reporter which offers detailed code coverage.
4. **chore:** set up `karma.conf.js` to utlize `kjhtml` reporter, leaving options to add other reporters if necessary.
5. **feat:** set up `app-testing.module.ts` for exporting all testing modules to `spec.ts` files
6. **test:** set up all **spec.ts** files to utilize **app.testing.module** exports and other corrections necessary for clean test cases.
7. **refactor:** some changes in component.ts files may also be required to pass tests.([eg.](https://stackoverflow.com/questions/46350113/error-typeerror-cannot-read-property-0-of-undefined-angular-4))

**Comment by karantakalkar** [comment]
This is based on #684

**Comment by muskankhedia** [comment]
@karantakalkar I am already working on this and have discussed my idea in [discourse](https://discourse.mifos.org/t/implementing-extensive-unit-testing-using-selenium-and-mocha/9422) way before, for mentors to provide their opinions. Please don't work on this, as it falls under plagiarism and hurts the motive of open-source.

**Comment by karantakalkar** [comment]
@muskankhedia I ain't working on writing any more tests, and I am just initializing it after having discussed with abhay on gitter that tests may be written for features I propose, You can please go ahead and propose for testing suite

**Comment by karantakalkar** [comment]
also there is refactoring yet to be done I have only fixed a tiny bit command.

**Comment by karantakalkar** [comment]
@muskankhedia  I can still close the PR if you insist, If I had proposed to write unit tests for features I will develop without unit tests working in the app that's what caused me to submit these pr's

**Comment by muskankhedia** [comment]
@karantakalkar No issues. You can complete the refactoring part.
