### ISSUE TITLE
E2E testing needs to be set up

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#697]
`ng e2e` fails with timeout

![Screenshot from 2020-03-28 18-07-41](https://user-images.githubusercontent.com/54709463/77823191-29f3f480-711f-11ea-849f-20c727a18e02.png)

e2e directory needs refactoring
![Screenshot from 2020-03-28 18-09-25](https://user-images.githubusercontent.com/54709463/77823233-76d7cb00-711f-11ea-962d-39970f506f6d.png)
![Screenshot from 2020-03-28 18-09-39](https://user-images.githubusercontent.com/54709463/77823236-79d2bb80-711f-11ea-8b1b-8511d32aa3c4.png)

**Comment by karantakalkar** [comment]
I'm on it

**Comment by muskankhedia** [comment]
@karantakalkar I am already working on this and have discussed my idea in [discourse](https://discourse.mifos.org/t/implementing-extensive-unit-testing-using-selenium-and-mocha/9422) way before, for mentors to provide their opinions. Please don't work on this, as it falls under plagiarism and hurts the motive of open-source.

**Comment by karantakalkar** [comment]
@muskankhedia I ain't working on writing any more tests, and I am just initializing it after having discussed with abhay on gitter that tests may be written for features I propose, You can please go ahead and propose for testing suite

**Comment by karantakalkar** [comment]
I had no intentions of copying your idea and maybe simple fixes to ng test and ng e2e commands may not be entire part of your proposal

**Comment by muskankhedia** [comment]
@karantakalkar It's fine. I understand your point. You can go ahead with it.
