### ISSUE TITLE
CORS issue prevents UI from working locally

### ISSUE THREAD

**Issue by stdunbar** [openMF/web-app#701]
When running against an against a local server, CORS error prevent the application from doing anything.

## Steps to Reproduce
1. Checkout fineract 1.4.0 or develop branch from github.com/apache/fineract
2. docker run --name mysql-5.5 -p 3306:3306 -e MYSQL_ROOT_PASSWORD=mysql -d mysql:5.5
3. ./gradlew createDB -PdbName=fineract_tenants
4. ./gradlew createDB -PdbName=fineract_default
5. ./gradlew tomcatRunWAR
6. Check out web-app, master branch
7. npm install
8. ng serve
12. Open browser, go to http://localhost:4200/
13. Login with user mifos, password password

## Expected Behaviour
Login should work

## Actual Behaviour
Login fails because of CORS error:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/fineract-provider/api/v1/authentication?username=mifos&password=password. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

## Settings

- Mifos X version: fineract 1.4.0 branch or develop branch 
- Browser used: Firefox 74.0
- OS: Ubuntu

**Comment by HarimbolaSantatra** [comment]
For those who still encounter CORS issue, [here's a sample nginx configuration](https://github.com/openMF/web-app/issues/706#issuecomment-2265208025) to make it work
