### ISSUE TITLE
Templates: Edit Template

### ISSUE THREAD

**Issue by spider0061** [openMF/web-app#702]
User should be able to edit the template as in https://demo.mifos.io/#/edittemplate/18.

Related Screenshot- 
![Screenshot from 2020-03-30 12-49-34](https://user-images.githubusercontent.com/45865775/77885594-eddaa400-7284-11ea-8519-86400bc54e6b.png)

Useful Link: 
https://demo.mifos.io/#/edittemplate/18

**Comment by Aaryan-kapur** [comment]
Hey @spider0061 can I work on this!

**Comment by spider0061** [comment]
@Aaryan-kapur you can work on it as no one else is working on it currently.

**Comment by Aaryan-kapur** [comment]
Hey! @spider0061 please elaborate!!!

**Comment by spider0061** [comment]
@Aaryan-kapur when you go to templates and select a template to view. You can see that there is an edit button. Currently it is not working as the edit template component is not present. You have to work on edit template component. Take a look at other components to get an idea about how the components are built in the web app.

**Comment by BLasan** [comment]
@spider0061  Can I work on this?

**Comment by spider0061** [comment]
@BLasan yes as @Aaryan-kapur have not submitted PR and its been more than 10 days.
