### ISSUE TITLE
Recurring Deposits: Create/edit RD application page

### ISSUE THREAD

**Issue by abhi40308** [openMF/web-app#709]
Goal:
Create or edit RD application page as shown here:
https://demo.mifos.io/#/newclientrecurringdepositaccount/5
![screencapture-demo-mifos-io-2020-03-31-17_49_42](https://user-images.githubusercontent.com/26903230/78025836-5191c980-7378-11ea-99d3-c8f250412d17.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/73466001/Term+Deposit+Accounts+Fixed+Deposit+Recurring+Deposit
https://demo.openmf.org/api-docs/apiLive.htm#rdaccounts

**Comment by abhi40308** [comment]
@abhaychawla  I would like to work on this, based on my previous work here : https://github.com/openMF/web-app/issues/226. Please have a look.

**Comment by muskankhedia** [comment]
PR #999 adds the feature to create Recurring Deposit Application Page.
