### ISSUE TITLE
Navigate to Home by Logo

### ISSUE THREAD

**Issue by BLasan** [openMF/web-app#717]
It's better to have the navigation to Home by clicking Mifos Logo as in 
https://demo.mifos.io/#/home

![mifos-web-app2](https://user-images.githubusercontent.com/43112139/78423959-c9693800-7687-11ea-9c8a-2e49fcf8b913.gif)

**Comment by BLasan** [comment]
@abhaychawla  I'll work on this

**Comment by abhaychawla** [comment]
@BLasan Please update the issue description to follow proper template.

**Comment by BLasan** [comment]
> @BLasan Please update the issue description to follow proper template.

I'll update as soon as I'm possible
