### ISSUE TITLE
Center list cursor should be cursor:pointer (to indicate clickable)

### ISSUE THREAD

**Issue by BLasan** [openMF/web-app#727]
Center list cursor should be pointable to select a center as in 
https://demo.mifos.io/#/centers

![Screenshot from 2020-04-11 10-49-48](https://user-images.githubusercontent.com/43112139/79036090-42b1df00-7be2-11ea-92b8-2ac905b42dc4.png)

**Comment by BLasan** [comment]
@abhaychawla  I'll work on this

**Comment by karantakalkar** [comment]
@BLasan I guess this has been fixed by: https://github.com/openMF/web-app/pull/650

**Comment by BLasan** [comment]
@karantakalkar  Yeah. I'll close the issue
