### ISSUE TITLE
'Frequent Postings' Button in Side Panel does not redirect to correct 'Frequent Postings' URL

### ISSUE THREAD

**Issue by Rishabh106** [openMF/web-app#731]
## Description
'Frequent Postings' button in Side Panel does not redirect to the correct 'Frequent Postings' component URL.

## Steps to Reproduce
1. Go to the Home Page and expand the Side Panel.
2. Click on the 'Frequent Postings' button.

## Expected Behaviour
The button should redirect to `/accounting/journal-entries/frequent-postings`

## Actual Behaviour
The button redirects to `/accounting/frequent-postings`
## Settings
- Mifos X version: 0.0.0-dev
- Browser used: Firefox

## Screenshots, if any
![frequent_posting](https://user-images.githubusercontent.com/36294070/80101204-bbc01780-858e-11ea-9403-d499f7c62352.gif)

**Comment by BLasan** [comment]
@Rishabh106  Can I work on this?
