### ISSUE TITLE
Not able to get EMI in decimals

### ISSUE THREAD

**Issue by subsnrao** [openMF/web-app#735]
Hi,
I created the loan product with the Installment in multiples of = 1 (In the application it is not allowing to set zero or any decimal)Because of that after the loan disbursement the amount is rounding off.
For my first installment it is displaying 
Principal due = 788
Interest = 100
Outstanding 888

Expected:
Principal due = 788.49
Interest = 100
Outstanding 888.49

Regaeds,
Subbu

**Comment by BLasan** [comment]
@subsnrao  Can I work on this?

**Comment by karantakalkar** [comment]
@subsnrao Can you add more detail to the issue?

**Comment by abhaychawla** [comment]
@subsnrao Please do not open issues for general support questions as we want to keep GitHub issues for bug reports and feature requests. If you have got any questions, please email to our mailing list. Please refer the Contribution Guidelines.
