### ISSUE TITLE
Migrate Opening Balances: Design Enhancement

### ISSUE THREAD

**Issue by Rishabh106** [openMF/web-app#743]
## Description
Some parts of this component need design enhancements in order to improve its UI.

## Steps to Reproduce
1. Open Mifos X Web App.
2. Go to Accounting -> Migrate Opening Balances
3. Select an office and click Retreive.

## Expected Behaviour
1. The 'Retrieve' text should be aligned in the center of the button.
2. Currency and Opening Balances Date should be aligned properly.
3. Type, GL Code and Account text should be aligned properly with the form inputs - Debit & Credit.

## Actual Behaviour
1. The 'Retrieve' text is not aligned in the center of the button. Some part of it is occupying space outside the button(check screenshots).
2. Currency and Opening Balances Date are not aligned properly.
3. Type, GL Code and Account text are not aligned properly with the form inputs - Debit & Credit.

## Settings
- Mifos X version: 0.0.0-dev
- Browser used: Firefox

## Screenshots, if any
1. ![Screenshot_1](https://user-images.githubusercontent.com/36294070/81318376-c8bf2980-90ab-11ea-9e96-542389479f2c.png)
![Screenshot_6](https://user-images.githubusercontent.com/36294070/81319231-fd7fb080-90ac-11ea-949b-f8162bd44289.png)

2. ![Screenshot_3](https://user-images.githubusercontent.com/36294070/81319297-18522500-90ad-11ea-8c16-f59ef7c87e0c.png)

3. ![Screenshot_2](https://user-images.githubusercontent.com/36294070/81318468-edb39c80-90ab-11ea-8aab-057584f5e068.png)

**Comment by BLasan** [comment]
@Rishabh106  Can I work on this?

**Comment by Rishabh106** [comment]
@BLasan You can ask one of the project maintainers if you want to work on this issue.

**Comment by BLasan** [comment]
> @BLasan You can ask one of the project maintainers if you want to work on this issue.

Sure
@abhaychawla  Can I work on this?

**Comment by karantakalkar** [comment]
Point 2 is browser specific issue it is present in Firefox but not in Chrome.

**Comment by Rishabh106** [comment]
@karantakalkar I've been using Firefox for quite a while so couldn't test it on Chrome. Does Point 2 alignment still need some work?

**Comment by karantakalkar** [comment]
No, I have tested it on chrome it is aligned, also in HTML there doesnt seem any viable reason for misalignment, which most probably means this is problem in browser rendering.
