### ISSUE TITLE
Hovering cursor over Logo doesn't change to hand-cursor after expanding Sidenav

### ISSUE THREAD

**Issue by Rishabh106** [openMF/web-app#746]
**Is your feature request related to a problem? Please describe.**
When I expand the Sidenav and hover the cursor over the Logo & Text 'Mifos', the pointer still remains the same even though they redirect to home page.

**Describe the solution you'd like**
I would like to see the cursor change to hand-cursor as the Logo & Text are used to redirect to the home page.

**Additional context**
I've tried to show both the Logo & Text example in this GIF.
![logo_redirect](https://user-images.githubusercontent.com/36294070/81496344-a52af780-92d4-11ea-99fb-88df15b6750a.gif)

**Comment by karantakalkar** [comment]
@Rishabh106 There are a few other changes required in sidenav as well, it's better to have a checklist and a single compound PR rather than multiple PRs fixing the sidenav.

**Comment by BLasan** [comment]
@karantakalkar Can I work this?

**Comment by karantakalkar** [comment]
There are some more additions to be done to sidenav. and it would be redundant to have many prs on same feature. If you are looking for an issue I guess create-cashier and transaction list page in TCM are up for taking.

**Comment by shobhi1310** [comment]
Hello!
Can I start working on this issue, as it has a good first tag, and I am also new to open-source contributing, and would like to fix this issue. 🙄

**Comment by karantakalkar** [comment]
Go ahead

**Comment by shobhi1310** [comment]
Thanks! will start working on this issue, sorry for asking for the other issue 😅
