### ISSUE TITLE
Color of Text 'Mifos' in Sidenav does not change with change of theme

### ISSUE THREAD

**Issue by Rishabh106** [openMF/web-app#747]
**Is your feature request related to a problem? Please describe.**
When I change the theme to darker ones, the color of text 'Mifos' does not change which makes it difficult to see. This primarily occurs with 2 themes (see GIF below).

**Describe the solution you'd like**
I would like to see the color of text 'Mifos' change with the change of themes.

**Additional context**
I've tried to show the problem with both the themes in this GIF.
![text_color](https://user-images.githubusercontent.com/36294070/81496618-74e45880-92d6-11ea-98d8-89c3331a6e31.gif)

**Comment by BLasan** [comment]
@abhaychawla  Can I work on this?

**Comment by karantakalkar** [comment]
@BLasan We highly value your enthusiasm in taking on issues, but it would be of great help if you could focus on improving quality of your existing PRs as they will be merged/closed within this week.

**Comment by BLasan** [comment]
> @BLasan We highly value your enthusiasm in taking on issues, but it would be of great help if you could focus on improving quality of your existing PRs as they will be merged/closed within this week.

Sure, I'll work on it

**Comment by Abhirup-99** [comment]
@karantakalkar can I work on this? The pr for routing changes is completed and can be merged pending any changes you may suggest.

**Comment by karantakalkar** [comment]
Go ahead, I guess this is an issue with theming and I am not sure if fixing just the css is gonna be the solution.
