### ISSUE TITLE
Manage Holidays: View Holiday page

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#749]
![Screenshot from 2020-05-14 20-23-37](https://user-images.githubusercontent.com/54709463/81949802-dda63a80-9620-11ea-8920-cdb880fdafdd.png)

**Community App page:**  
https://demo.mifos.io/#/viewholiday/209

**Comment by BLasan** [comment]
@karantakalkar I'll work on this

**Comment by karantakalkar** [comment]
G ahead, please.
