### ISSUE TITLE
Use httpclient over http

### ISSUE THREAD

**Issue by anweshknayak** [openMF/web-app#75]
Currently http is deprecated. But won't cause any issue. Would be better if used httpclient.

**Comment by anweshknayak** [comment]
As per update by @abhaychawla 

> when you get time to update http to httpclient now, you could simply just send a request without setting the api prefix or headers as that will happen automatically now. This will only work with http client.

**Comment by abhaychawla** [comment]
*Clients* section of the web app requires this update.

**Comment by abhaychawla** [comment]
Closed by https://github.com/openMF/web-app/pull/411
