### ISSUE TITLE
Manage Holidays : Edit Holiday page

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#750]
![Screenshot from 2020-05-14 20-28-20](https://user-images.githubusercontent.com/54709463/81950434-8c4a7b00-9621-11ea-80a7-55734273b357.png)

**Community App Page:** 
https://demo.mifos.io/#/editholiday/209

**Comment by BLasan** [comment]
@karantakalkar Can I work on this?

**Comment by karantakalkar** [comment]
@BLasan It would be better if you get your previous PR merge ready before taking on this.

**Comment by BLasan** [comment]
> @BLasan It would be better if you get your previous PR merge ready before taking on this.

p3 labeled PRs? I'll check 'em. But I think this will not take too much time to implement. I'll refactor the PRs first :)

**Comment by karantakalkar** [comment]
No I meant view holiday only, leave p3 for now.

**Comment by BLasan** [comment]
> No I meant view holiday only, leave p3 for now.

Refactored that. You can take a look
