### ISSUE TITLE
Create Entity Data Table Checks

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#751]
![Screenshot from 2020-05-14 20-32-11](https://user-images.githubusercontent.com/54709463/81950894-25799180-9622-11ea-9832-2dced15daae1.png)

**Note: This will be implemented as a form in web app and not a dialog**

https://demo.mifos.io/#/entitydatatablechecks

**Comment by BLasan** [comment]
@karantakalkar I'll work on this

**Comment by BLasan** [comment]
@karantakalkar Do we need to implement a dialog box for creating a data table as in your screenshot? Or just redirecting to another page which consists of a create data table form?

**Comment by karantakalkar** [comment]
Another page with form.
