### ISSUE TITLE
Edit Adhoc Query page

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#752]
![Screenshot from 2020-05-14 20-37-45](https://user-images.githubusercontent.com/54709463/81951541-e6980b80-9622-11ea-80b4-38bf9b4aeeea.png)

**Community App Page**
https://demo.mifos.io/#/editadhocquery/19

**Comment by stableapple** [comment]
Can I work on this issue?

**Comment by karantakalkar** [comment]
I would recommend you to take on a good first issue eg: https://github.com/openMF/web-app/issues/770
before going on for harder ones.
