### ISSUE TITLE
Bulk Loan Reassignment

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#754]
![Screenshot from 2020-05-14 20-43-18](https://user-images.githubusercontent.com/54709463/81952106-adac6680-9623-11ea-8423-6d92092a45f1.png)

**Community App Page**
https://demo.mifos.io/#/bulkloan

**Comment by BLasan** [comment]
@karantakalkar I'll work on this

**Comment by karantakalkar** [comment]
G ahead, please
