### ISSUE TITLE
Teller Cashier Management: Allocate Cash

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#758]
![Screenshot from 2020-05-14 21-16-00](https://user-images.githubusercontent.com/54709463/81955829-375e3300-9628-11ea-8d10-3bf147de17f3.png)

https://demo.mifos.io/#/tellers/35/cashiers/21/actions/allocate

**Comment by BLasan** [comment]
@karantakalkar Can I work on this?

**Comment by karantakalkar** [comment]
Go Ahead

**Comment by BLasan** [comment]
@karantakalkar Is there a way to allocate cashiers ? I tried creating a teller but there are no cashiers

**Comment by karantakalkar** [comment]
Use demo server, navigate to teller in screenshot.
