### ISSUE TITLE
Teller Cashier Management: Settle Cash

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#759]
![Screenshot from 2020-05-14 21-17-30](https://user-images.githubusercontent.com/54709463/81956034-77bdb100-9628-11ea-9190-8086c30c7011.png)

https://demo.mifos.io/#/tellers/35/cashiers/21/actions/settle

**Comment by BLasan** [comment]
@karantakalkar I'll work on this

**Comment by karantakalkar** [comment]
Ok
