### ISSUE TITLE
Teller Cashier Management: View Cashier

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#761]
![Screenshot from 2020-05-14 21-19-35](https://user-images.githubusercontent.com/54709463/81956979-9e301c00-9629-11ea-9630-788bb0b40b4d.png)

https://demo.mifos.io/#/tellers/46/cashiers/25

**Comment by spider0061** [comment]
duplicate of #757

**Comment by karantakalkar** [comment]
They are different, I forgot to add 'list page' for 757.

**Comment by BLasan** [comment]
@karantakalkar Can I work on this?

**Comment by karantakalkar** [comment]
G ahead, please
