### ISSUE TITLE
Teller Cashier Management: Edit Cashier

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#762]
![Screenshot from 2020-05-14 21-19-45](https://user-images.githubusercontent.com/54709463/81957376-1b5b9100-962a-11ea-83ce-df8e781f7965.png)

https://demo.mifos.io/#/tellers/46/editcashier/25

**Comment by BLasan** [comment]
@karantakalkar I'll work on this

**Comment by aditya-sarkar441** [comment]
@karantakalkar I'll like to work on this.

**Comment by BLasan** [comment]
> @karantakalkar I'll like to work on this.

It's comleted. View PR #802

**Comment by aditya-sarkar441** [comment]
Okay
