### ISSUE TITLE
Collapse and Expand All button not working

### ISSUE THREAD

**Issue by muskankhedia** [openMF/web-app#763]
## Description
The expand all the collapse all button is not working as required or expected in the tree view of Charts of Accounts page.

## Steps to Reproduce
The path to the page is:
Accounting -> Charts of Accounts -> Tree View

## Expected Behaviour
The expand all button should expand all the nodes whereas collapse all should collapse it.

## Actual Behaviour
In the first instance, the expand all button is collapsing the tree and no more actions performed by the collapse all and expand all button further.

## Settings
- Mifos X version: 
- Browser used: Chrome

**Comment by karantakalkar** [comment]
Same as : #578

**Comment by muskankhedia** [comment]
> Same as : #578

No, it's different.
