### ISSUE TITLE
System: Edit Survey Component

### ISSUE THREAD

**Issue by muskankhedia** [openMF/web-app#766]
**Goal:**

System Admins require the ability to edit survey as at:
https://demo.mifos.io/#/editsurvey/1

![Screenshot from 2020-05-15 00-36-28](https://user-images.githubusercontent.com/36980003/81975080-24595c00-9644-11ea-9045-edcdb5abb832.png)

**Resource:**
[https://mifosforge.jira.com/wiki/spaces/MIFOS/pages/73466240/Surveys](https://mifosforge.jira.com/wiki/spaces/MIFOS/pages/73466240/Surveys)

**Comment by BLasan** [comment]
@muskankhedia Can I work on this?

**Comment by muskankhedia** [comment]
@BLasan sure

**Comment by mittulmandhan** [comment]
@muskankhedia @karantakalkar @Jov03  I would like to work on this Feature: Edit Survey

**Comment by karantakalkar** [comment]
Go ahead

**Comment by mittulmandhan** [comment]
There are 2 ways to implement edit page:

**1.) Reuse create-survey component**
- By reusing the existing create-survey component we only have to __initialize form fields(in ngOnInit())+Disable some read-only fields+redirect user to view-survey page(on submit event)__
- __don't need to create a new component to edit surveys__

**2.) Create a new edit-survey component**
- generate new edit-survey component from scratch
- recreating the existing functionalities of the create-survey component in the edit-survey component
- initialize form fields(in ngOnInit())+Disable some read-only fields+redirect user to view-survey page(on submit event)

__Which approach should I use?__

**Comment by karantakalkar** [comment]
2

**Comment by mittulmandhan** [comment]
👍on it

**Comment by mittulmandhan** [comment]
Am I required to copy existing code from create-survey and then add edit-survey specific functionalities
Or should I recreate the existing functionalities and UI of create-survey(self implementation) and then add edit-survey specific functionalities

**Comment by karantakalkar** [comment]
Keep the functionality/design/code consistent with create-survey.

**Comment by mittulmandhan** [comment]
Details about the resource(rest api url) for edit survey HTTP request ???

**Comment by mittulmandhan** [comment]
@karantakalkar @muskankhedia please review my PR
