### ISSUE TITLE
Product: View all Dividends

### ISSUE THREAD

**Issue by muskankhedia** [openMF/web-app#769]
**Goal:**
As a products admin, I want to view all the dividends for a particular share product,
[https://demo.mifos.io/#/dividends/82/](https://demo.mifos.io/#/dividends/82/)

![Screenshot from 2020-05-15 00-49-59](https://user-images.githubusercontent.com/36980003/81976343-04c33300-9646-11ea-9707-8500869bac25.png)

**Comment by stableapple** [comment]
Can I work on this issue?

**Comment by karantakalkar** [comment]
G Ahead, please
