### ISSUE TITLE
Product: Initiate dividend

### ISSUE THREAD

**Issue by muskankhedia** [openMF/web-app#770]
**Goal:**
As a products admin, I would like to initiate for a particular share product,
https://demo.mifos.io/#/shareproduct/82/createdividend

![Screenshot from 2020-05-15 00-51-56](https://user-images.githubusercontent.com/36980003/81976500-4522b100-9646-11ea-9a63-6ecffc915424.png)

**Comment by BLasan** [comment]
@karantakalkar Can I work on this?

**Comment by karantakalkar** [comment]
G ahead, please
