### ISSUE TITLE
Consistency in View Component paths

### ISSUE THREAD

**Issue by Rishabh106** [openMF/web-app#774]
**Is your feature request related to a problem? Please describe.**
Currently, Accounting & Self service sections of the web app use `view/:id` as the path to view components but other sections use `:id` path to view components.

**Describe the solution you'd like**
I would like the view component path to be consistent throughout the web app, i.e., change the view components paths of Accounting & Self service sections.

**Additional context**
![2](https://user-images.githubusercontent.com/36294070/82155749-b35cb300-9894-11ea-9f4e-a073b37b44c7.png)
![1](https://user-images.githubusercontent.com/36294070/82155751-b5267680-9894-11ea-9071-5a79db894ad2.png)

**Comment by abhaychawla** [comment]
Note: The approach was changed during last year's GSoC. Therefore, we require this refactoring.

**Comment by Abhirup-99** [comment]
Hi, can I work on this?

**Comment by karantakalkar** [comment]
Go ahead, refer to organization module's routing to gain context of this issue.

**Comment by Abhirup-99** [comment]
Hi @karantakalkar , I have pushed a pr for this. Do review.
