### ISSUE TITLE
Add pagination to /clients 

### ISSUE THREAD

**Issue by anweshknayak** [openMF/web-app#78]
**/clients**
- Angular material pagination

**Comment by mdew192837** [comment]
I think I can take my hand at this.

Is there anything I should be cautious of @anweshknayak ?

**Comment by mdew192837** [comment]
Also, according to https://openmf.github.io/web-app/clients, it looks like pagination already exists?

**Comment by anweshknayak** [comment]
@mdew192837 you have to use https://demo.openmf.org/api-docs/apiLive.htm#clients_list the pagination feature from the API given in link and plug into material angular pagination feature which we are using.

Also you can take a look how we are fetching API calls https://github.com/openMF/web-app/blob/master/src/app/clients/clients.service.ts

**Comment by anweshknayak** [comment]
Currently only material angular pagination layout works. It is not plugged into the API yet. For testing purpose you can set to 4 pages per list as the clients list is not populated.

**Comment by mdew192837** [comment]
@anweshknayak I don't think the link to the API docs is working. Is there an alternative?

**Comment by anweshknayak** [comment]
Check the link in the github source file I mentioned above. Use that

**Comment by mdew192837** [comment]
I'm a bit confused in regards to steps I need to implement. For example, I think I need page number, length, and a way to dynamically get the right users. I think i do that by using the offset property, but I can't seem to get pagination to work. @anweshknayak

**Comment by anweshknayak** [comment]
@mdew192837 take a look at this for inspiration https://blog.angular-university.io/angular-material-data-table/

**Comment by anweshknayak** [comment]
#115
