### ISSUE TITLE
Users: Parameter email is invalid.

### ISSUE THREAD

**Issue by spider0061** [openMF/web-app#781]
## Description
While creating a user when we click on submit button, it throws an error as " The parameter email is invalid." 

## Steps to Reproduce
Go to Admin, select users. Click on create user and fill the form. On submit it throws error.

## Expected Behaviour
Should redirect to the user created. 

## Actual Behaviour
Throws error

## Settings
- Mifos X version: 
- Browser used: Chrome

## Screenshots, if any
![Screenshot from 2020-05-18 18-54-32](https://user-images.githubusercontent.com/45865775/82218628-cecdc980-9939-11ea-9e09-ce5fcef32a83.png)
![Screenshot from 2020-05-18 18-54-40](https://user-images.githubusercontent.com/45865775/82218633-cffef680-9939-11ea-8664-62e09a18bb28.png)

**Comment by abhaychawla** [comment]
@spider0061 Test with updated backend at staging server once and check.

**Comment by spider0061** [comment]
> @spider0061 Test with updated backend at staging server once and check.

Alright

**Comment by spider0061** [comment]
> @spider0061 Test with updated backend at staging server once and check.

Currently, both mobile and staging server is throwing this error. 
![Screenshot from 2020-05-18 19-22-32](https://user-images.githubusercontent.com/45865775/82221016-0a1dc780-993d-11ea-9497-9131ca3bf03f.png)
![Screenshot from 2020-05-18 19-21-12](https://user-images.githubusercontent.com/45865775/82221018-0c802180-993d-11ea-8185-0b1c766d8482.png)
Also, there's one more error when an office doesn't have staff it throws this error:
![Screenshot from 2020-05-18 19-04-45](https://user-images.githubusercontent.com/45865775/82221088-23267880-993d-11ea-9a02-f8b5479f6416.png)

**Comment by spider0061** [comment]
@abhaychawla same error on https://staging.mifos.io/#/createuser/ and https://mobile.mifos.io/#/createuser/. It seems to be a backend problem.

**Comment by karantakalkar** [comment]
Can you check if API request parameters in commy app and web app are same or not?

**Comment by karantakalkar** [comment]
Backend related issue.
