### ISSUE TITLE
Deleted Holidays should not be visible in manage holidays list page

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#797]
![Screenshot from 2020-05-22 19-33-42](https://user-images.githubusercontent.com/54709463/82676134-824cfb80-9c63-11ea-94e3-c3518ea53904.png)

Refer Community App Page:
https://demo.mifos.io/#/holidays

**Comment by BLasan** [comment]
@karantakalkar Can I work on this?

**Comment by karantakalkar** [comment]
G ahead please

**Comment by BLasan** [comment]
@karantakalkar Data is not loading on this page
