### ISSUE TITLE
Loan Account Page Enhancements

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#81]
As shown in screenshot, Loan Details in on right side of the page and loan summary is left. 

![loanaccountpage](https://user-images.githubusercontent.com/23022667/42075164-38ee4e24-7b8d-11e8-8b48-c0b00db17b97.png)

Expected:

Keep  Loan Details at left side of the page, and Loan Summary as right side of the page. Alignments must be maintained.

**Comment by muskankhedia** [comment]
@santoshconflux If anyone is not working can I take up on this issue?
