### ISSUE TITLE
Loans: Undo Disbursal

### ISSUE THREAD

**Issue by muskankhedia** [openMF/web-app#827]
Goal:
Implement the undo disbursal loan account as shown below:

https://staging.mifos.io/#/loanaccount/25/undodisbursal
![Screenshot from 2020-05-31 22-02-19](https://user-images.githubusercontent.com/36980003/83357532-904cfb80-a38a-11ea-87f7-c082fce53d3c.png)

**Comment by Rishabh106** [comment]
@muskankhedia Can I work on this issue?

**Comment by muskankhedia** [comment]
Sure
