### ISSUE TITLE
Loans: Approve loan account 

### ISSUE THREAD

**Issue by muskankhedia** [openMF/web-app#829]
Goal:
As a loan officer, I want to approve a loan account:

https://staging.mifos.io/#/loanaccount/2/approve
![Screenshot from 2020-06-01 00-04-02](https://user-images.githubusercontent.com/36980003/83359978-91d2ef80-a39b-11ea-90c1-b01eba2a7fef.png)

**Comment by BLasan** [comment]
@muskankhedia  Can I work on this?

**Comment by muskankhedia** [comment]
Sure

**Comment by BLasan** [comment]
@muskankhedia Can we use ngModel for data binding?

**Comment by muskankhedia** [comment]
No, instead you can use reactive form wherever required.

**Comment by BLasan** [comment]
> No, instead you can use reactive form wherever required.

Can you state the relevant community app controller for this? Is it approveLoanRescheduleRequest?

**Comment by muskankhedia** [comment]
The controller used for the action buttons is `LoanAccountActionsController`, here in the switch case you can find `approve` option which handles the approve action.
