### ISSUE TITLE
Loans: Reject Loan Account

### ISSUE THREAD

**Issue by muskankhedia** [openMF/web-app#830]
Goal:
As a loan officer, I want to reject a pending loan account:

https://staging.mifos.io/#/loanaccount/2/reject
![Screenshot from 2020-06-01 00-06-06](https://user-images.githubusercontent.com/36980003/83360032-d8c0e500-a39b-11ea-9ecb-a20bcbd07bbb.png)

**Comment by BLasan** [comment]
@muskankhedia I'll work on this

**Comment by muskankhedia** [comment]
Sure
