### ISSUE TITLE
Loans: Add loan Collateral

### ISSUE THREAD

**Issue by muskankhedia** [openMF/web-app#831]
Goal:
As a loan officer, I want to add loan collateral:

https://staging.mifos.io/#/addcollateral/2
![Screenshot from 2020-06-01 00-13-34](https://user-images.githubusercontent.com/36980003/83360172-e2971800-a39c-11ea-970c-2df8181014fb.png)

**Comment by BLasan** [comment]
@muskankhedia Can I work on this?

**Comment by muskankhedia** [comment]
Sure
