### ISSUE TITLE
Loans: View Guarantors

### ISSUE THREAD

**Issue by muskankhedia** [openMF/web-app#832]
Goal:
As a loan officer, I want to view all the guarantors:

https://staging.mifos.io/#/listguarantors/2
![Screenshot from 2020-06-01 00-15-32](https://user-images.githubusercontent.com/36980003/83360212-386bc000-a39d-11ea-92a6-33b4b7780218.png)

**Comment by BLasan** [comment]
@muskankhedia Can I work on this?

**Comment by muskankhedia** [comment]
Sure.

**Comment by BLasan** [comment]
@muskankhedia CORS policy error when calling the relevant api

**Comment by muskankhedia** [comment]
Have you tried using `staging` server?

**Comment by BLasan** [comment]
yes

**Comment by muskankhedia** [comment]
I tried and it's working completely fine for me, can you send the screenshot of the API call?

**Comment by BLasan** [comment]
> I tried and it's working completely fine for me, can you send the screenshot of the API call?

![Screenshot from 2020-06-04 23-19-55](https://user-images.githubusercontent.com/43112139/83793369-108c9d00-a6ba-11ea-9658-922e909fd2b6.png)

**Comment by muskankhedia** [comment]
@BLasan I tried the same, and I am not facing any such error yet. For now, you can take up any other issue, will resolve this later.
