### ISSUE TITLE
Loans: 'Add Loan Charge' Page

### ISSUE THREAD

**Issue by muskankhedia** [openMF/web-app#845]
Goal:
As a loan officer, I want to add a loan charge.

https://staging.mifos.io/#/addloancharge/18
![Screenshot from 2020-06-07 12-06-49](https://user-images.githubusercontent.com/36980003/83962126-15b73b00-a8b8-11ea-8e5e-6c272f03c9ab.png)

**Comment by BLasan** [comment]
@muskankhedia I'll work on this
