### ISSUE TITLE
Loans: 'Waive Interest' Page

### ISSUE THREAD

**Issue by muskankhedia** [openMF/web-app#846]
Goal:
As a loan officer, I want to waive interest of a particular loan account.

https://staging.mifos.io/#/loanaccount/18/waiveinterest
![Screenshot from 2020-06-07 12-16-05](https://user-images.githubusercontent.com/36980003/83962160-b7d72300-a8b8-11ea-9afb-7dda401018e6.png)

**Comment by BLasan** [comment]
@muskankhedia I'll work on this
