### ISSUE TITLE
Loans: 'Write Off' Page

### ISSUE THREAD

**Issue by muskankhedia** [openMF/web-app#847]
Goal:
As a loan officer, I want to write off a loan account

https://staging.mifos.io/#/loanaccount/18/writeoff
![Screenshot from 2020-06-07 12-22-35](https://user-images.githubusercontent.com/36980003/83962261-b2c6a380-a8b9-11ea-88a3-3bcc644ad460.png)

**Comment by BLasan** [comment]
@muskankhedia I'll work on this

**Comment by muskankhedia** [comment]
Sure
