### ISSUE TITLE
Loans: 'Close (As rescheduled)' Page

### ISSUE THREAD

**Issue by muskankhedia** [openMF/web-app#848]
Goal:
As a loan officer, I want to close an account:

https://staging.mifos.io/#/loanaccount/18/close-rescheduled
![Screenshot from 2020-06-07 12-24-44](https://user-images.githubusercontent.com/36980003/83962336-2ec0eb80-a8ba-11ea-8e09-709c2ad6070d.png)

**Comment by BLasan** [comment]
@muskankhedia I'll work on this

**Comment by muskankhedia** [comment]
@BLasan Thank you for your interest but there needs to implement a setup for the action buttons and passing the values to maintain the consistency among all the buttons. Till then you can take up some issues other than action buttons.

**Comment by BLasan** [comment]
> @BLasan Thank you for your interest but there needs to implement a setup for the action buttons and passing the values to maintain the consistency among all the buttons. Till then you can take up some issues other than action buttons.

Sure :)
