### ISSUE TITLE
Loans: 'Disburse to Savings' Page

### ISSUE THREAD

**Issue by muskankhedia** [openMF/web-app#857]
Goal:
As a loan offficer, I want to disburse to savings

https://staging.mifos.io/#/loanaccount/71/disbursetosavings
![Screenshot from 2020-06-09 00-25-47](https://user-images.githubusercontent.com/36980003/84069269-e9024100-a9e7-11ea-87dd-e0bccf829f8b.png)

**Comment by BLasan** [comment]
@muskankhedia Can I work on this?

**Comment by muskankhedia** [comment]
Sure
