### ISSUE TITLE
Loans: 'Withdraw by Client' Page

### ISSUE THREAD

**Issue by muskankhedia** [openMF/web-app#859]
**Goal:**
As a loan officer, I want to withdraw by client

https://staging.mifos.io/#/loanaccount/63/withdrawnByApplicant
![Screenshot from 2020-06-09 00-39-08](https://user-images.githubusercontent.com/36980003/84070509-e1dc3280-a9e9-11ea-9bbd-4b3b700c0da9.png)

**Comment by BLasan** [comment]
@muskankhedia  Can I work on this?
